---
permalink: audit/common-elements-in-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, messages, message, common elements, AMID, ANID, ASES, ASQN, ATID, ATIM, ATYP, AVER, RSLT 
summary: 所有審計訊息都包含共同的元素。 
---
= 審計訊息中的常見元素
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
所有審計訊息都包含共同的元素。

[cols="1a,1a,4a"]
|===
| 程式碼 | 類型 | 描述 


 a| 
之中
 a| 
FC32
 a| 
模組 ID：產生訊息的模組 ID 的四個字元識別碼。這表示產生審計訊息的代碼段。



 a| 
安尼德
 a| 
UI32
 a| 
節點 ID：指派給產生訊息的服務的網格節點 ID。在設定和安裝StorageGRID系統時，每個服務都會指派一個唯一的識別碼。此 ID 無法變更。



 a| 
東南大學
 a| 
UI64
 a| 
審計會話標識符：在先前的版本中，此元素指示服務啟動後審計系統初始化的時間。此時間值以作業系統紀元（1970 年 1 月 1 日 00:00:00 UTC）以來的微秒為單位進行測量。

*注意：*此元素已過時，不再出現在稽核訊息中。



 a| 
美國品質協會
 a| 
UI64
 a| 
序列計數：在先前的版本中，此計數器會隨著網格節點（ANID）上產生的每個稽核訊息而遞增，並在服務重新啟動時重設為零。

*注意：*此元素已過時，不再出現在稽核訊息中。



 a| 
急性胰臟炎
 a| 
UI64
 a| 
追蹤 ID：由單一事件觸發的一組訊息共享的識別碼。



 a| 
ATIM
 a| 
UI64
 a| 
時間戳記：觸發稽核訊息的事件的產生時間，以自作業系統紀元（1970 年 1 月 1 日 00:00:00 UTC）以來的微秒為單位。請注意，大多數用於將時間戳轉換為本地日期和時間的工具都是基於毫秒的。

可能需要對記錄的時間戳進行四捨五入或截斷。審計訊息開頭出現的可讀時間 `audit.log`檔案是 ISO 8601 格式的 ATIM 屬性。日期和時間表示為 `_YYYY-MMDDTHH:MM:SS.UUUUUU_`，其中 `T`是一個文字字串字符，表示日期時間段的開始。 `_UUUUUU_`是微秒。



 a| 
典型蛋白
 a| 
FC32
 a| 
事件類型：正在記錄的事件的四個字元的識別碼。這決定了訊息的「有效負載」內容：所包含的屬性。



 a| 
斷言
 a| 
UI32
 a| 
版本：審計訊息的版本。隨著StorageGRID軟體的發展，新版本的服務可能會在審計報告中加入新功能。此欄位使 AMS 服務能夠向後相容，以處理來自舊版本服務的訊息。



 a| 
放射學研究實驗室
 a| 
FC32
 a| 
結果：事件、過程或交易的結果。如果與訊息無關，則使用 NONE 而不是 SUCS，以免訊息被意外過濾。

|===