---
permalink: audit/s3-select-request.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, S3SL, S3 Select request 
summary: 此訊息表示使用者啟動了 S3 Select 作業。 
---
= S3SL：S3 選擇請求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 Select 請求傳回給客戶端後，此訊息記錄完成。 S3SL 訊息可以包含錯誤訊息和錯誤代碼詳細資訊。請求可能未成功。

[cols="1a,1a,4a"]
|===
| 程式碼 | 場地 | 描述 


 a| 
披薩中心
 a| 
已掃描位元組數
 a| 
從儲存節點掃描（接收）的位元組數。

如果物體被壓縮，BYSC 和 BYPR 可能會有所不同。如果物件被壓縮，BYSC 將具有壓縮後的位元組數，而 BYPR 將具有解壓縮後的位元組數。



 a| 
BYPR
 a| 
已處理位元組數
 a| 
處理的位元組數。指示 S3 Select 作業實際處理或操作的「已掃描位元組數」的位元組數。



 a| 
拜耳
 a| 
傳回的位元組數
 a| 
S3 Select 作業傳回給客戶端的位元組數。



 a| 
雷普爾
 a| 
已處理的記錄
 a| 
S3 Select 作業從儲存節點接收的記錄數或行數。



 a| 
遠距放射治療
 a| 
已傳回的記錄
 a| 
S3 Select 作業傳回給客戶端的記錄數或行數。



 a| 
喬菲
 a| 
工作完成
 a| 
指示 S3 Select 作業是否已完成處理。如果為假，則作業無法完成，且錯誤欄位中可能會包含資料。客戶端可能收到了部分結果，或者根本沒有收到結果。



 a| 
里德
 a| 
請求 ID
 a| 
S3 Select 請求的識別碼。



 a| 
擴充
 a| 
執行時間
 a| 
S3 選擇作業完成所需的時間（以秒為單位）。



 a| 
急性呼吸器管理組
 a| 
錯誤訊息
 a| 
S3 Select 作業產生的錯誤訊息。



 a| 
ERTY
 a| 
錯誤類型
 a| 
S3 Select 作業產生的錯誤類型。



 a| 
ERST
 a| 
錯誤堆疊追蹤
 a| 
S3 Select 作業產生的錯誤堆疊追蹤。



 a| 
S3BK
 a| 
S3 儲存桶
 a| 
S3 儲存桶名稱。



 a| 
S3AK
 a| 
S3 存取金鑰 ID（請求傳送者）
 a| 
發送請求的使用者的 S3 存取金鑰 ID。



 a| 
S3AI
 a| 
S3 租用戶帳號 ID（請求傳送者）
 a| 
發送請求的使用者的租戶帳戶 ID。



 a| 
S3KY
 a| 
S3 鍵
 a| 
S3 密鑰名稱，不包括儲存桶名稱。

|===