---
permalink: audit/supd-s3-metadata-updated.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SUPD, S3 Metadata Updated 
summary: 當 S3 用戶端更新所攝取物件的元資料時，S3 API 會產生此訊息。如果元資料更新成功，伺服器將發出該訊息。 
---
= SUPD：S3 元資料已更新
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當 S3 用戶端更新所攝取物件的元資料時，S3 API 會產生此訊息。如果元資料更新成功，伺服器將發出該訊息。

[cols="1a,1a,4a"]
|===
| 程式碼 | 場地 | 描述 


 a| 
中央商務區
 a| 
內容區塊標識符
 a| 
所請求內容區塊的唯一識別碼。如果 CBID 未知，則該欄位設為 0。對 bucket 的操作不包含該欄位。



 a| 
CNC工具機
 a| 
一致性控制頭
 a| 
更新儲存桶的合規性設定時，Consistency-Control HTTP 請求標頭的值（如果存在於請求中）。



 a| 
全國藥品資訊中心
 a| 
連線標識符
 a| 
TCP/IP 連線的唯一系統識別碼。



 a| 
CSIZ
 a| 
內容大小
 a| 
檢索到的物件的大小（以位元組為單位）。對 bucket 的操作不包含該欄位。



 a| 
HTRH
 a| 
HTTP 請求標頭
 a| 
在配置期間選擇的已記錄 HTTP 請求標頭名稱和值的清單。

 `X-Forwarded-For`如果請求中存在，則會自動包含在內，並且 `X-Forwarded-For`值與請求發送者IP位址（SAIP審計欄位）不同。



 a| 
放射學研究實驗室
 a| 
結果代碼
 a| 
GET 事務的結果。結果總是：

SUCS：成功



 a| 
S3AI
 a| 
S3 租用戶帳號 ID（請求傳送者）
 a| 
發送請求的使用者的租戶帳戶 ID。空值表示匿名存取。



 a| 
S3AK
 a| 
S3 存取金鑰 ID（請求傳送者）
 a| 
發送請求的使用者的雜湊 S3 存取金鑰 ID。空值表示匿名存取。



 a| 
S3BK
 a| 
S3 儲存桶
 a| 
S3 儲存桶名稱。



 a| 
S3KY
 a| 
S3 鍵
 a| 
S3 密鑰名稱，不包括儲存桶名稱。對 bucket 的操作不包含該欄位。



 a| 
南卡羅來納大學
 a| 
S3 租用戶帳戶名稱（請求發送者）
 a| 
發送請求的使用者的租戶帳戶的名稱。對於匿名請求則為空。



 a| 
薩伊普
 a| 
IP位址（請求發送者）
 a| 
發出請求的客戶端應用程式的 IP 位址。



 a| 
SBAC
 a| 
S3 租用戶帳戶名稱（儲存桶擁有者）
 a| 
儲存桶擁有者的租用戶帳戶名稱。用於識別跨帳戶或匿名存取。



 a| 
SBAI
 a| 
S3 租用戶帳號 ID（儲存桶擁有者）
 a| 
目標Bucket擁有者的租戶帳戶ID。用於識別跨帳戶或匿名存取。



 a| 
SUSR
 a| 
S3 用戶 URN（請求發送者）
 a| 
租用戶帳戶 ID 和發出要求的使用者的使用者名稱。使用者可以是本機使用者或 LDAP 使用者。例如：  `urn:sgws:identity::03393893651506583485:root`

對於匿名請求則為空。



 a| 
時間
 a| 
時間
 a| 
請求的總處理時間（以微秒為單位）。



 a| 
TLIP
 a| 
受信任的負載平衡器 IP 位址
 a| 
如果請求由受信任的第 7 層負載平衡器路由，則為該負載平衡器的 IP 位址。



 a| 
唯一識別符
 a| 
通用唯一識別符
 a| 
StorageGRID系統內物件的識別碼。



 a| 
垂直整合式
 a| 
版本 ID
 a| 
已更新元資料的物件的特定版本的版本 ID。對儲存桶和未版本控制的儲存桶中的物件的操作不包含此欄位。

|===