---
settings:
  name: StorageGRID software
  search: storagegrid-enable,storagegrid,storagegrid-appliances
  internal:
    pdf_enabled: true
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    hide_language_selector: false
  versions:
  - version-number: '11.9'
    url: "/storagegrid-119"
  - version-number: '12.0'
    url: "/storagegrid"
  - version-number: '11.8'
    url: "/storagegrid-118"
  - version-number: '11.7'
    url: "/storagegrid-117"
  - version-number: '11.6'
    url: "/storagegrid-116"
  - version-number: '11.5'
    url: "/storagegrid-115"
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: StorageGRID 11.9 文檔
    url: "/index.html"
  - title: StorageGRID設備
    url: "/storagegrid-hardware.html"
  - title: 發行說明
    url: "/release-notes/index.html"
  - title: 開始
    url: "/landing-get-started/index.html"
    entries:
    - section: primer
    - section: network
    - title: 快速啟動
      url: "/primer/quick-start.html"
  - title: 安裝、升級和修補程序
    url: "/landing-install-upgrade/index.html"
    entries:
    - title: 安裝電器
      url: "/storagegrid-hardware.html"
    - section: rhel
    - section: ubuntu
    - section: vmware
    - section: upgrade
    - title: 應用StorageGRID修補程序
      entries:
      - title: 修補程式
        url: "/maintain/storagegrid-hotfix-procedure.html"
      - title: 應用修補程式後您的系統會受到怎樣的影響
        url: "/maintain/how-your-system-is-affected-when-you-apply-hotfix.html"
      - title: 取得修復所需材料
        url: "/maintain/obtaining-required-materials-for-hotfix.html"
      - title: 下載修補程式文件
        url: "/maintain/downloading-hotfix-file.html"
      - title: 在應用修補程式之前檢查系統狀況
        url: "/maintain/checking-systems-condition-before-applying-hotfix.html"
      - title: 應用修補程式
        url: "/maintain/applying-hotfix.html"
  - title: 配置和管理
    url: "/landing-configure-manage/index.html"
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: 使用StorageGRID
    url: "/landing-use/index.html"
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: 監控和故障排除
    url: "/landing-monitor-troubleshoot/index.html"
    entries:
    - section: monitor
    - section: troubleshoot
    - section: audit
  - section: expand
  - title: 維護你的電網
    url: "/landing-maintain/index.html"
    entries:
    - title: 電網維護
      url: "/maintain/index.html"
    - title: 下載恢復包
      url: "/maintain/downloading-recovery-package.html"
    - title: 退役節點或站點
      entries:
      - title: 退役節點或站點
        url: "/maintain/decommission-procedure.html"
      - title: 退役節點
        entries:
        - title: 電網節點退役
          url: "/maintain/grid-node-decommissioning.html"
        - title: 管理節點或網關節點的注意事項
          url: "/maintain/considerations-for-decommissioning-admin-or-gateway-nodes.html"
        - title: 儲存節點的注意事項
          entries:
          - title: 一般考慮
            url: "/maintain/considerations-for-decommissioning-storage-nodes.html"
          - title: ADC 仲裁
            url: "/maintain/understanding-adc-service-quorum.html"
          - title: 檢查 ILM 策略和儲存配置
            url: "/maintain/reviewing-ilm-policy-and-storage-configuration.html"
          - title: 整合儲存節點
            url: "/maintain/consolidating-storage-nodes.html"
          - title: 停用多個儲存節點
            url: "/maintain/decommissioning-multiple-storage-nodes.html"
        - title: 檢查資料修復作業
          url: "/maintain/checking-data-repair-jobs.html"
        - title: 收集所需材料
          url: "/maintain/gathering-required-materials-node-decom.html"
        - title: 訪問退役節點頁面
          url: "/maintain/accessing-decommission-nodes-page.html"
        - title: 退役斷開連接的電網節點
          url: "/maintain/decommissioning-disconnected-grid-nodes.html"
        - title: 退役已連接的電網節點
          url: "/maintain/decommissioning-connected-grid-nodes.html"
        - title: 暫停和恢復儲存節點的退役過程
          url: "/maintain/pausing-and-resuming-decommission-process-for-storage-nodes.html"
      - title: 退役現場
        entries:
        - title: 刪除網站的注意事項
          url: "/maintain/considerations-for-removing-site.html"
        - title: 收集所需材料
          url: "/maintain/gathering-required-materials-site-decom.html"
        - title: 選擇站點
          url: "/maintain/step-1-select-site.html"
        - title: 查看詳細信息
          url: "/maintain/step-2-view-details.html"
        - title: 修改 ILM 政策
          url: "/maintain/step-3-revise-ilm-policy.html"
        - title: 刪除 ILM 引用
          url: "/maintain/step-4-remove-ilm-references.html"
        - title: 解決節點衝突（並開始退役）
          url: "/maintain/step-5-resolve-node-conflicts.html"
        - title: 監控退役
          url: "/maintain/step-6-monitor-decommission.html"
    - title: 重新命名網格、站點或節點
      entries:
      - title: 使用重新命名程式
        url: "/maintain/rename-grid-site-node-overview.html"
      - title: 新增或更新顯示名稱
        url: "/maintain/rename-grid-site-node.html"
    - title: 節點程式
      entries:
      - title: 節點維護流程
        pdf-filename: 節點程式
        url: "/maintain/grid-node-procedures.html"
      - title: 伺服器管理員過程
        entries:
        - title: 查看伺服器管理員狀態和版本
          url: "/maintain/viewing-server-manager-status-and-version.html"
        - title: 查看所有服務的目前狀態
          url: "/maintain/viewing-current-status-of-all-services.html"
        - title: 啟動伺服器管理員和所有服務
          url: "/maintain/starting-server-manager-and-all-services.html"
        - title: 重新啟動伺服器管理員和所有服務
          url: "/maintain/restarting-server-manager-and-all-services.html"
        - title: 停止伺服器管理員和所有服務
          url: "/maintain/stopping-server-manager-and-all-services.html"
        - title: 查看目前服務狀態
          url: "/maintain/viewing-current-status-of-service.html"
        - title: 停止服務
          url: "/maintain/stopping-service.html"
        - title: 強制終止服務
          url: "/maintain/forcing-service-to-terminate.html"
        - title: 啟動或重新啟動服務
          url: "/maintain/starting-or-restarting-service.html"
        - title: 使用 DoNotStart 文件
          url: "/maintain/using-donotstart-file.html"
        - title: 伺服器管理員故障排除
          url: "/maintain/accessing-server-manager-log-file.html"
      - title: 重新啟動、關機和電源程序
        entries:
        - title: 執行滾動重啟
          url: "/maintain/rolling-reboot-procedure.html"
        - title: 從「任務」標籤重新啟動節點
          url: "/maintain/rebooting-grid-node-from-grid-manager.html"
        - title: 從命令 shell 重新啟動節點
          url: "/maintain/rebooting-grid-node-from-command-shell.html"
        - title: 關閉節點
          url: "/maintain/shutting-down-grid-node.html"
        - title: 關閉主機電源
          url: "/maintain/powering-down-host.html"
        - title: 關閉並打開所有節點的電源
          url: "/maintain/powering-off-and-on-all-nodes-in-grid.html"
      - title: 連接埠重映射程序
        entries:
        - title: 刪除連接埠重新映射
          url: "/maintain/removing-port-remaps.html"
        - title: 刪除裸機主機上的連接埠重新映射
          url: "/maintain/removing-port-remaps-on-bare-metal-hosts.html"
    - title: 網路程式
      entries:
      - title: 更新網格網路的子網
        url: "/maintain/updating-subnets-for-grid-network.html"
      - title: 配置 IP 位址
        entries:
        - title: IP 位址指南
          url: "/maintain/configuring-ip-addresses.html"
        - title: 更改節點網路配置
          url: "/maintain/changing-nodes-network-configuration.html"
        - title: 新增或變更管理網路上的子網路列表
          url: "/maintain/adding-to-or-changing-subnet-lists-on-admin-network.html"
        - title: 在網格網路上新增或變更子網路列表
          url: "/maintain/adding-to-or-changing-subnet-lists-on-grid-network.html"
        - title: 更改網格中所有節點的 IP 位址
          url: "/maintain/changing-ip-addresses-and-mtu-values-for-all-nodes-in-grid.html"
      - title: 將介面新增至現有節點
        entries:
        - title: Linux：新增管理或客戶端介面
          url: "/maintain/linux-adding-interfaces-to-existing-node.html"
        - title: Linux：新增中繼或存取介面
          url: "/maintain/linux-adding-trunk-or-access-interfaces-to-node.html"
        - title: VMware：新增中繼或存取介面
          url: "/maintain/vmware-adding-trunk-or-access-interfaces-to-node.html"
      - title: 配置 DNS 伺服器
        url: "/maintain/configuring-dns-servers.html"
      - title: 修改單一網格節點的DNS配置
        url: "/maintain/modifying-dns-configuration-for-single-grid-node.html"
      - title: 管理 NTP 伺服器
        url: "/maintain/configuring-ntp-servers.html"
      - title: 恢復孤立節點的網路連接
        url: "/maintain/restoring-network-connectivity-for-isolated-nodes.html"
    - title: 主機和中介軟體程序
      entries:
      - title: Linux：將網格節點遷移到新主機
        url: "/maintain/linux-migrating-grid-node-to-new-host.html"
      - title: VMware：配置虛擬機器自動重啟
        url: "/maintain/vmware-configuring-virtual-machine-for-automatic-restart.html"
  - title: 恢復或替換節點
    url: "/landing-recover/index.html"
    entries:
    - title: 網格節點復原的警告和注意事項
      url: "/maintain/warnings-and-considerations-for-grid-node-recovery.html"
    - title: 收集網格節點恢復所需的材料
      url: "/maintain/gathering-required-materials-for-grid-node-recovery.html"
    - title: 選擇節點恢復程式
      url: "/maintain/selecting-node-recovery-procedure.html"
    - title: 從儲存節點故障中恢復
      entries:
      - title: 儲存節點恢復
        url: "/maintain/recovering-from-storage-node-failures.html"
      - title: 恢復設備儲存節點
        entries:
        - title: 恢復設備儲存節點的警告
          pdf-filename: 恢復設備儲存節點
          url: "/maintain/recovering-storagegrid-appliance-storage-node.html"
        - title: 準備設備儲存節點以進行重新安裝
          url: "/maintain/preparing-appliance-storage-node-for-reinstallation.html"
        - title: 開始StorageGRID設備安裝
          url: "/maintain/starting-storagegrid-appliance-installation.html"
        - title: 監控StorageGRID設備安裝
          url: "/maintain/monitoring-storagegrid-appliance-installation-sn.html"
        - title: 選擇“開始復原”以配置設備儲存節點
          url: "/maintain/selecting-start-recovery-to-configure-appliance-storage-node.html"
        - title: 重新掛載並重新格式化裝置儲存磁碟區（手動步驟）
          url: "/maintain/remounting-and-reformatting-appliance-storage-volumes.html"
        - title: 將物件資料還原到裝置的儲存卷
          url: "/maintain/restoring-object-data-to-storage-volume-for-appliance.html"
        - title: 恢復設備儲存節點後檢查儲存狀態
          url: "/maintain/checking-storage-state-after-recovering-sga.html"
      - title: 從系統磁碟機完好的儲存磁碟區故障中恢復
        entries:
        - title: 恢復任務
          pdf-filename: 從系統磁碟機完好的儲存磁碟區故障中恢復
          url: "/maintain/recovering-from-storage-volume-failure-where-system-drive-is-intact.html"
        - title: 儲存卷恢復警告
          url: "/maintain/reviewing-warnings-about-storage-volume-recovery.html"
        - title: 識別並解除安裝故障儲存卷
          url: "/maintain/identifying-and-unmounting-failed-storage-volumes.html"
        - title: 恢復故障的儲存磁碟區並重建 Cassandra 資料庫
          url: "/maintain/recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html"
        - title: 將物件資料還原到系統磁碟機完好的儲存卷
          url: "/maintain/restoring-object-data-to-storage-volume-where-system-drive-is-intact.html"
        - title: 恢復儲存磁碟區後檢查儲存狀態
          url: "/maintain/checking-storage-state-after-recovering-storage-volumes.html"
      - title: 從系統驅動器故障中恢復
        entries:
        - title: 儲存節點系統磁碟機復原警告
          url: "/maintain/reviewing-warnings-for-system-drive-recovery.html"
        - title: 更換儲存節點
          url: "/maintain/replacing-storage-node.html"
        - title: 選擇“開始復原”以配置儲存節點
          url: "/maintain/selecting-start-recovery-to-configure-storage-node.html"
        - title: 重新掛載並重新格式化儲存磁碟區（手動步驟）
          url: "/maintain/remounting-and-reformatting-storage-volumes-manual-steps.html"
        - title: 將物件資料還原到儲存磁碟區（系統磁碟機故障）
          url: "/maintain/restoring-object-data-to-storage-volume.html"
        - title: 恢復儲存節點系統磁碟機後檢查儲存狀態
          url: "/maintain/checking-storage-state-after-recovering-storage-node-system-drive.html"
      - title: 使用網格管理器恢復物件數據
        url: "/maintain/restoring-volume.html"
      - title: 監控修復資料作業
        url: "/maintain/monitor-repairs.html"
    - title: 從管理節點故障中恢復
      entries:
      - title: 主要或非主要管理節點
        pdf-filename: 從管理節點故障中恢復
        url: "/maintain/recovering-from-admin-node-failures.html"
      - title: 從主管理節點故障中恢復
        entries:
        - title: 恢復主管理節點
          pdf-filename: 從主管理節點故障中恢復
          url: "/maintain/recovering-from-primary-admin-node-failures.html"
        - title: 從發生故障的主管理節點複製審計日誌
          url: "/maintain/copying-audit-logs-from-failed-primary-admin-node.html"
        - title: 更換主管理節點
          url: "/maintain/replacing-primary-admin-node.html"
        - title: 配置替換主管理節點
          url: "/maintain/configuring-replacement-primary-admin-node.html"
        - title: 確定主管理節點的修補程式要求
          url: "/maintain/assess-hotfix-requirement-during-primary-admin-node-recovery.html"
        - title: 在已復原的主管理節點上復原稽核日誌
          url: "/maintain/restoring-audit-log-on-recovered-primary-admin-node.html"
        - title: 恢復主管理節點時恢復管理節點資料庫
          url: "/maintain/restoring-admin-node-database-primary-admin-node.html"
        - title: 恢復主管理節點時恢復 Prometheus 指標
          url: "/maintain/restoring-prometheus-metrics-primary-admin-node.html"
      - title: 從非主管理節點故障中恢復
        entries:
        - title: 恢復非主管理節點
          pdf-filename: 從非主管理節點故障中恢復
          url: "/maintain/recovering-from-non-primary-admin-node-failures.html"
        - title: 從發生故障的非主管理節點複製審計日誌
          url: "/maintain/copying-audit-logs-from-failed-non-primary-admin-node.html"
        - title: 替換非主管理節點
          url: "/maintain/replacing-non-primary-admin-node.html"
        - title: 選擇“開始復原”以配置非主管理節點
          url: "/maintain/selecting-start-recovery-to-configure-non-primary-admin-node.html"
        - title: 在已復原的非主管理節點上復原稽核日誌
          url: "/maintain/restoring-audit-log-on-recovered-non-primary-admin-node.html"
        - title: 恢復非主管理節點時恢復管理節點資料庫
          url: "/maintain/restoring-admin-node-database-non-primary-admin-node.html"
        - title: 恢復非主管理節點時恢復 Prometheus 指標
          url: "/maintain/restoring-prometheus-metrics-non-primary-admin-node.html"
    - title: 從網關節點故障中恢復
      entries:
      - title: 更換網關節點
        url: "/maintain/replacing-gateway-node.html"
      - title: 選擇“開始恢復”以設定網關節點
        url: "/maintain/selecting-start-recovery-to-configure-gateway-node.html"
    - title: 從存檔節點故障中恢復
      entries:
      - title: 從存檔節點故障中恢復
        pdf-filename: 從存檔節點故障中恢復
        url: "/maintain/recovering-from-archive-node-failures.html"
    - title: 替換 Linux 節點
      entries:
      - title: Linux 節點替換
        pdf-filename: 替換 Linux 節點（所有網格節點類型）
        url: "/maintain/all-node-types-replacing-linux-node.html"
      - title: 部署新的 Linux 主機
        url: "/maintain/deploying-new-linux-hosts.html"
      - title: 將網格節點還原到主機
        url: "/maintain/restoring-existing-nodes.html"
      - title: 下一步：如果需要，請執行其他恢復步驟
        url: "/maintain/whats-next-performing-additional-recovery-steps-if-required.html"
    - title: 替換 VMware 節點
      url: "/maintain/all-node-types-replacing-vmware-node.html"
    - title: 用服務設備替換故障節點
      entries:
      - title: 更換指南
        pdf-filename: 用服務設備替換故障節點
        url: "/maintain/replacing-failed-node-with-services-appliance.html"
      - title: 安裝服務設備（僅限平台變更）
        url: "/maintain/installing-services-appliance-platform-change-only.html"
      - title: 準備重新安裝設備（僅限平台更換）
        url: "/maintain/preparing-appliance-for-reinstallation-platform-replacement-only.html"
      - title: 在服務設備上開始軟體安裝
        url: "/maintain/starting-software-installation-on-services-appliance-recovery.html"
      - title: 監控服務設備安裝
        url: "/maintain/monitoring-services-appliance-installation.html"
    - title: 技術支援如何恢復站點
      url: "/maintain/how-site-recovery-is-performed-by-technical-support.html"
  - title: 啟用StorageGRID
    url: "/storagegrid-enable.html"
  - title: StorageGRID和BlueXP
    url: "/storagegrid-bluexp.html"
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family
