---
permalink: upgrade/estimating-time-to-complete-upgrade.html 
sidebar: sidebar 
keywords: upgrade, time estimate, duration, cassandra upgrade 
summary: 根據升級可能需要的時間考慮何時升級。請注意在升級的每個階段可以執行和不能執行的操作。 
---
= 估計完成升級的時間
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根據升級可能需要的時間考慮何時升級。請注意在升級的每個階段可以執行和不能執行的操作。

.關於此任務
完成StorageGRID升級所需的時間取決於多種因素，例如客戶端負載和硬體效能。

表總結了主要的升級任務並列出了每個任務所需的大約時間。表格後面的步驟提供了可用於估計系統升級時間的說明。

[cols="1a,2a,2a,4a"]
|===
| 升級任務 | 描述 | 大約需要的時間 | 在此任務期間 


 a| 
執行預檢查並升級主管理節點
 a| 
執行升級預檢查，並停止、升級和重新啟動主管理節點。
 a| 
30 分鐘到 1 小時，其中服務設備節點所需的時間最多。

未解決的預檢錯誤這次將會增加。
 a| 
您無法存取主管理節點。可能會報告連線錯誤，您可以忽略。

在開始升級之前執行升級預檢查可讓您在規劃的升級維護時段之前解決任何錯誤。



 a| 
啟動升級服務
 a| 
軟體檔案分發完畢，啟動升級服務。
 a| 
每個網格節點 3 分鐘
 a| 



 a| 
升級其他網格節點
 a| 
所有其他網格節點上的軟體都將按照您批准節點的順序進行升級。系統中的每個節點將一次關閉一個。
 a| 
每個節點 15 分鐘到 1 小時，其中設備節點所需的時間最長

*注意*：對於設備節點， StorageGRID設備安裝程式會自動更新至最新版本。
 a| 
* 請勿改變網格配置。
* 請勿更改審計級別配置。
* 不要更新 ILM 配置。
* 您無法執行其他維護程序，例如修補程序、退役或擴充。


*注意*：如果您需要執行恢復，請聯絡技術支援。



 a| 
啟用功能
 a| 
新版本的新功能已啟用。
 a| 
不到5分鐘
 a| 
* 請勿改變網格配置。
* 請勿更改審計級別配置。
* 不要更新 ILM 配置。
* 您無法執行其他維護程序。




 a| 
升級資料庫
 a| 
升級過程會檢查每個節點以驗證 Cassandra 資料庫不需要更新。
 a| 
每個節點 10 秒或整個網格幾分鐘
 a| 
從StorageGRID 11.8 升級到 11.9 不需要升級 Cassandra 資料庫；但是，每個儲存節點上的 Cassandra 服務將停止並重新啟動。

對於未來的StorageGRID功能版本，Cassandra 資料庫更新步驟可能需要幾天才能完成。



 a| 
最終升級步驟
 a| 
臨時檔案已被刪除，新版本的升級已完成。
 a| 
5分鐘
 a| 
當*最終升級步驟*任務完成後，您可以執行所有維護程序。

|===
.步驟
. 估計升級所有網格節點所需的時間。
+
.. 將StorageGRID系統中的節點數乘以 1 小時/節點。
+
一般來說，設備節點的升級時間比基於軟體的節點更長。

.. 在此時間上添加 1 小時，以計算下載所需的時間 `.upgrade`文件，運行預檢驗證，並完成最後的升級步驟。


. 如果您有 Linux 節點，請為每個節點增加 15 分鐘，以計算下載和安裝 RPM 或 DEB 套件所需的時間。
. 將步驟 1 和 2 的結果相加，計算升級的總預計時間。




== 範例：升級到StorageGRID 11.9 的預計時間

假設您的系統有 14 個網格節點，其中 8 個是 Linux 節點。

. 將 14 乘以 1 小時/節點。
. 新增 1 小時以用於下載、預檢和最後步驟。
+
升級所有節點預計需要 15 小時。

. 將 8 乘以 15 分鐘/節點，以計算在 Linux 節點上安裝 RPM 或 DEB 套件的時間。
+
此步驟預計耗時 2 小時。

. 將這些值加在一起。
+
您最多需要 17 小時才能完成系統到StorageGRID 11.9.0 的升級。




NOTE: 根據需要，您可以透過批准網格節點子集在多個會話中進行升級，將維護視窗拆分為更小的視窗。例如，您可能想要在一個會話中升級網站 A 上的節點，然後在稍後的會話中升級網站 B 上的節點。如果您選擇在多個會話中執行升級，請注意，只有在所有節點都升級完成後，您才能開始使用新功能。
