---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: 了解您的StorageGRID系統在升級期間會受到怎樣的影響。 
---
= 升級期間您的系統會受到什麼影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解您的StorageGRID系統在升級期間會受到怎樣的影響。



== StorageGRID升級不會造成中斷

StorageGRID系統可以在整個升級過程中從客戶端應用程式中提取和檢索資料。如果您批准升級所有相同類型的節點（例如，儲存節點），則會一次關閉一個節點，因此不會出現所有網格節點或某種類型的所有網格節點都不可用的情況。

為了實現持續可用性，請確保您的 ILM 策略包含指定儲存每個物件的多個副本的規則。您還必須確保所有外部 S3 用戶端都配置為將請求傳送到以下之一：

* 高可用性 (HA) 群組虛擬 IP 位址
* 高可用性第三方負載平衡器
* 每個客戶端有多個網關節點
* 每個客戶端有多個儲存節點




== 客戶端應用程式可能會遭遇短期中斷

StorageGRID系統可以在整個升級過程中從用戶端應用程式中提取和檢索資料；但是，如果升級需要重新啟動這些節點上的服務，則用戶端與各個網關節點或儲存節點的連線可能會暫時中斷。升級過程完成後，連線將恢復，並且各個節點上的服務將恢復。

如果在短時間內失去連線是不可接受的，您可能需要安排停機時間來套用升級。您可以使用選擇性批准來安排某些節點的更新時間。


NOTE: 您可以使用多個網關和高可用性 (HA) 群組在升級過程中提供自動故障轉移。請參閱說明link:../admin/configure-high-availability-group.html["配置高可用性組"]。



== 設備韌體已升級

在StorageGRID 11.9 升級期間：

* 所有StorageGRID設備節點都會自動升級到StorageGRID Appliance Installer 韌體版本 3.9。
* SG6060 和 SGF6024 裝置自動升級至 BIOS 韌體版本 3B08.EX 和BMC韌體版本 4.00.07。
* SG100 和 SG1000 裝置自動升級至 BIOS 韌體版本 3B13.EC 和BMC韌體版本 4.74.07。
* SGF6112、SG6160、SG110 和 SG1100 設備自動升級到BMC韌體版本 3.16.07。




== ILM 策略根據其狀態進行不同的處理

* 升級後，有效策略將保持不變。
* 升級時僅保留最新的 10 個歷史策略。
* 如果有建議的政策，它將在升級期間被刪除。




== 可能會觸發警報

當服務啟動和停止時，以及當StorageGRID系統作為混合版本環境運行時（一些網格節點運行早期版本，而其他網格節點已升級到更高版本），可能會觸發警報。升級完成後可能會觸發其他警報。

例如，當服務停止時，您可能會看到*無法與節點通訊*警報，或當某些節點已升級至StorageGRID 11.9 但其他節點仍在執行StorageGRID 11.8 時，您可能會看到*Cassandra 通訊錯誤*警報。一般來說，升級完成後這些警報將會清除。

在升級到StorageGRID 11.9 期間儲存節點停止時，可能會觸發 *ILM 放置無法實現* 警報。升級完成後，此警報可能會持續 1 天。

升級完成後，您可以從網格管理器儀表板中選擇*最近解決的警報*或*當前警報*來查看任何與升級相關的警報。



== 產生許多 SNMP 通知

請注意，升級期間停止並重新啟動網格節點時可能會產生大量 SNMP 通知。為避免過多的通知，請在開始升級之前清除*啟用 SNMP 代理通知*複選框（*配置* > *監控* > *SNMP 代理*）以停用 SNMP 通知。然後，升級完成後重新啟用通知。



== 配置變更受到限制


NOTE: 此清單專門適用於從StorageGRID 11.8 升級到StorageGRID 11.9。如果您要升級到另一個StorageGRID版本，請參閱該版本升級說明中的受限變更清單。

直到「啟用新功能」任務完成：

* 不要進行任何網格配置變更。
* 請勿啟用或停用任何新功能。
* 不要更新 ILM 配置。否則，您可能會遇到不一致且意外的 ILM 行為。
* 不要應用修補程式或恢復網格節點。
+

NOTE: 如果您需要在升級期間恢復節點，請聯絡技術支援。

* 升級至StorageGRID 11.9 時，您不應管理 HA 群組、VLAN 介面或負載平衡器端點。
* 在升級到StorageGRID 11.9 完成之前，請勿刪除任何 HA 群組。其他 HA 群組中的虛擬 IP 位址可能變得無法存取。


直到*最終升級步驟*任務完成：

* 不要執行擴展程式。
* 不要執行退役程序。




== 您無法從租戶管理器查看儲存桶詳細資訊或管理儲存桶

在升級至StorageGRID 11.9 期間（即係統作為混合版本環境運作時），您無法使用租用戶管理器檢視儲存桶詳細資料或管理儲存桶。租戶管理器中的「儲存桶」頁面上出現下列錯誤之一：

* 升級到 11.9 時無法使用此 API。
* 升級至 11.9 時，您無法在租用戶管理員中查看儲存桶版本控制詳細資訊。


升級到 11.9 後，此錯誤將會解決。

.解決方法
在 11.9 升級過程中，請使用下列工具查看儲存桶詳細資訊或管理儲存桶，而不是使用租用戶管理員：

* 若要在儲存桶上執行標準 S3 操作，請使用link:../s3/operations-on-buckets.html["S3 REST API"]或link:../tenant/understanding-tenant-management-api.html["租戶管理 API"]。
* 若要對儲存桶執行StorageGRID自訂操作（例如，檢視和修改儲存桶一致性、啟用或停用上次存取時間更新或設定搜尋整合），請使用租用戶管理 API。

