---
permalink: upgrade/performing-upgrade.html 
sidebar: sidebar 
keywords: upgrade, how to perform a software upgrade 
summary: 您可以升級到StorageGRID 11.9 並同時套用該版本的最新修補程式。StorageGRID升級頁面提供了建議的升級路徑並直接連結到正確的下載頁面。 
---
= 執行升級
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以升級到StorageGRID 11.9 並同時套用該版本的最新修補程式。StorageGRID升級頁面提供了建議的升級路徑並直接連結到正確的下載頁面。

.開始之前
您已審查了所有註意事項並完成了所有規劃和準備步驟。



== 造訪StorageGRID升級頁面

第一步，存取網格管理器中的StorageGRID升級頁面。

.步驟
. Sign inlink:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
. 選擇*維護* > *系統* > *軟體更新*。
. 從StorageGRID升級圖塊中，選擇 *升級*。




== 選擇文件

StorageGRID升級頁面上的更新路徑指示必須安裝哪些主要版本（例如，11.9.0）和修補程式（例如，11.9.0.1）才能取得最新的StorageGRID版本。您應該按照顯示的順序安裝建議的版本和修補程式。


TIP: 如果沒有顯示更新路徑，您的瀏覽器可能無法存取NetApp支援站點，或AutoSupport頁面（*支援* > *工具* > *AutoSupport* > *設定*）上的 *檢查軟體更新*複選框可能已停用。

.步驟
. 對於*選擇檔案*步驟，檢查更新路徑。
. 從下載檔案部分，選擇每個*下載*連結以從NetApp支援網站下載所需的檔案。
+
如果沒有顯示更新路徑，請前往 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp下載： StorageGRID"^]確定是否有新版本或修補程式可用並下載所需的檔案。

+

NOTE: 如果您需要在所有 Linux 主機上下載並安裝 RPM 或 DEB 套件，您可能已經在更新路徑中列出了StorageGRID升級和修補程式檔案。

. 選擇*瀏覽*將版本升級檔上傳到StorageGRID： `NetApp_StorageGRID_11.9.0_Software_uniqueID.upgrade`
+
上傳和驗證過程完成後，檔案名稱旁邊會出現一個綠色複選標記。

. 如果您下載了修補程式文件，請選擇「*瀏覽*」上傳該文件。此修補程式將作為版本升級的一部分自動套用。
. 選擇*繼續*。




== 運行預檢

執行預檢查可讓您在開始升級電網之前檢測並解決任何升級問題。

.步驟
. 對於*執行預檢查*步驟，首先輸入網格的設定密碼。
. 選擇*下載恢復包*。
+
在升級主管理節點之前，您應該下載復原包檔案的目前副本。如果發生故障，恢復包檔案可讓您恢復系統。

. 下載文件後，請確認您可以存取其內容，包括 `Passwords.txt`文件。
. 複製下載的文件(`.zip`）到兩個安全、可靠且獨立的位置。
+

CAUTION: 復原包檔案必須是安全的，因為它包含可用於從StorageGRID系統取得資料的加密金鑰和密碼。

. 選擇*執行預檢查*，然後等待預檢查完成。
. 查看每個報告的預檢的詳細資訊並解決任何報告的錯誤。查看 https://kb.netapp.com/hybrid/StorageGRID/Maintenance/StorageGRID_11.9_software_upgrade_resolution_guide["StorageGRID軟體升級解決指南"^]適用於StorageGRID 11.9 版本。
+
您必須先解決所有預檢錯誤，然後才能升級系統。但是，您不需要在升級之前解決預檢_警告_。

+

CAUTION: 如果您開啟了任何自訂防火牆端口，則會在預檢驗證期間收到通知。您必須在繼續升級之前聯絡技術支援。

. 如果您進行了任何設定變更來解決報告的問題，請再次選擇*執行預檢查*以取得更新的結果。
+
如果所有錯誤都已解決，系統將提示您開始升級。





== 開始升級並升級主管理節點

當您開始升級時，升級預檢查將再次運行，並且主管理節點將自動升級。升級的這一部分可能需要長達 30 分鐘。


NOTE: 在主管理節點升級期間，您將無法存取任何其他網格管理器頁面。審計日誌也將不可用。

.步驟
. 選擇*開始升級*。
+
出現警告，提醒您將暫時失去對網格管理器的存取權限。

. 選擇“*確定*”確認警告並開始升級。
. 等待升級預檢查完成並等待主管理節點升級。
+

NOTE: 如果報告任何預檢錯誤，請解決它們並再次選擇*開始升級*。

+
如果網格有另一個線上且準備就緒的管理節點，則可以使用它來監視主管理節點的狀態。一旦主管理節點升級，您就可以批准其他網格節點。

. 根據需要，選擇*繼續*以存取*升級其他節點*步驟。




== 升級其他節點

您必須升級所有網格節點，但您可以執行多個升級工作階段並自訂升級順序。例如，您可能想要在一個會話中升級網站 A 上的節點，然後在稍後的會話中升級網站 B 上的節點。如果您選擇在多個會話中執行升級，請注意，只有在所有節點都升級完成後，您才能開始使用新功能。

如果節點升級的順序很重要，請一次批准一個節點或節點組，並等到每個節點的升級完成後再批准下一個節點或節點組。


NOTE: 當網格節點上開始升級時，該節點上的服務將停止。稍後，網格節點重新啟動。為了避免與節點通訊的客戶端應用程式的服務中斷，除非您確定節點已準備好停止並重新啟動，否則請勿批准節點的升級。根據需要安排維護時段或通知客戶。

.步驟
. 對於*升級其他節點*步驟，請查看摘要，其中提供了整個升級的開始時間以及每個主要升級任務的狀態。
+
** *啟動升級服務*是第一個升級任務。在此任務期間，軟體檔案被分發到網格節點，並且在每個節點上啟動升級服務。
** 當*啟動升級服務*任務完成後，*升級其他網格節點*任務將啟動，並提示您下載恢復包的新副本。


. 出現提示時，輸入您的設定密碼並下載恢復包的新副本。
+

CAUTION: 主管理節點升級後，您應該下載恢復包檔案的新副本。如果發生故障，恢復包檔案可讓您恢復系統。

. 檢視每種類型節點的狀態表。有非主要管理節點、網關節點和儲存節點的表。
+
當表格首次出現時，網格節點可能處於以下階段之一：

+
** 解壓縮升級包
** 下載
** 等待批准


. [[approval-step]]當您準備好選擇要升級的網格節點（或如果您需要取消批准選定的節點）時，請使用以下說明：
+
[cols="1a,1a"]
|===
| 任務 | 操作說明 


 a| 
搜尋要批准的特定節點，例如特定站點的所有節點
 a| 
在*搜尋*字段中輸入搜尋字串



 a| 
選擇所有節點進行升級
 a| 
選擇*批准所有節點*



 a| 
選擇所有相同類型的節點進行升級（例如，所有儲存節點）
 a| 
選擇節點類型的“*全部批准*”按鈕

如果您批准多個相同類型的節點，則將一次升級一個節點。



 a| 
選擇單一節點進行升級
 a| 
選擇節點的*核准*按鈕



 a| 
推遲所有選定節點的升級
 a| 
選擇*取消批准所有節點*



 a| 
推遲所有選定的同類型節點的升級
 a| 
選擇節點類型的「全部取消批准」按鈕



 a| 
推遲單一節點的升級
 a| 
選擇節點的*取消批准*按鈕

|===
. 等待核准的節點完成以下升級階段：
+
** 已批准並等待升級
** 停止服務
+

NOTE: 當節點的階段達到*停止服務*時，您無法刪除該節點。  *取消批准*按鈕已停用。

** 停止容器
** 清理 Docker 映像
** 升級基礎作業系統包
+

NOTE: 當設備節點到達此階段時，設備上的StorageGRID Appliance Installer 軟體將會更新。此自動化流程可確保StorageGRID Appliance Installer 版本與StorageGRID軟體版本保持同步。

** 重啟
+

NOTE: 某些設備型號可能會重新啟動多次以升級韌體和 BIOS。

** 重啟後執行步驟
** 啟動服務
** 完畢


. 重複<<approval-step,批准步驟>>根據需要多次，直到所有網格節點都升級完畢。




== 全面升級

當所有網格節點都完成升級階段後，「升級其他網格節點」任務將顯示為「已完成」。其餘升級任務在背景自動執行。

.步驟
. 一旦「啟用功能」任務完成（很快就會完成），您就可以開始使用link:whats-new.html["新功能"]在升級的StorageGRID版本中。
. 在*升級資料庫*任務期間，升級過程會檢查每個節點以驗證 Cassandra 資料庫不需要更新。
+

NOTE: 從StorageGRID 11.8 升級到 11.9 不需要升級 Cassandra 資料庫；但是，每個儲存節點上的 Cassandra 服務將停止並重新啟動。對於未來的StorageGRID功能版本，Cassandra 資料庫更新步驟可能需要幾天才能完成。

. 當*升級資料庫*任務完成後，等待幾分鐘以完成*最終升級步驟*。
. 當*最終升級步驟*完成後，升級就完成了。第一步，*選擇檔案*，重新顯示綠色成功橫幅。
. 驗證電網運作是否已恢復正常：
+
.. 檢查服務是否正常運作且沒有意外警報。
.. 確認客戶端與StorageGRID系統的連線是否如預期運作。



