---
permalink: upgrade/removed-or-deprecated-features.html 
sidebar: sidebar 
keywords:  
summary: 此版本中刪除或棄用了某些特性和功能。查看這些項目以了解升級之前是否需要更新客戶端應用程式或修改配置。 
---
= 已刪除或棄用的功能和能力
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
此版本中刪除或棄用了某些特性和功能。查看這些項目以了解升級之前是否需要更新客戶端應用程式或修改配置。



== 定義

已棄用:: 此功能*不應*在新的生產環境中使用。現有的生產環境可以繼續使用該功能。
生命終點:: 支援該功能的最新版本。在某些情況下，該功能的文件可能會在此階段被刪除。
已移除:: 第一個不支援該功能的版本。




== StorageGRID功能支援終止

棄用的功能將在 N+2 主要版本中刪除。例如，如果某個功能在版本 N（例如 6.3）中被棄用，則該功能將存在的最後一個版本是 N+1（例如 6.4）。版本 N+2（例如 6.5）是產品中不存在該功能時的第一個版本。

查看 https://mysupport.netapp.com/site/info/version-support["軟體版本支援頁面"^]了解更多。


NOTE: 在某些情況下， NetApp可能會提前終止對特定功能的支援。

[cols="2a,1a,1a,1a,3a"]
|===
| 特徵 | 已棄用 | 生命終點 | 已移除 | 早期文檔的連結 


 a| 
傳統警報（不是警報）
 a| 
11.7
 a| 
11.8
 a| 
11.9
 a| 
https://docs.netapp.com/us-en/storagegrid-118/monitor/alarms-reference.html["警訊參考（StorageGRID 11.8）"^]



 a| 
存檔節點支持
 a| 
11.7
 a| 
11.8
 a| 
11.9
 a| 
https://docs.netapp.com/us-en/storagegrid-118/maintain/considerations-for-decommissioning-admin-or-gateway-nodes.html["退役存檔節點的注意事項（StorageGRID 11.8）"^]

*注意*：在開始升級之前，您必須：

. 退役所有存檔節點。看 https://docs.netapp.com/us-en/storagegrid-118/maintain/grid-node-decommissioning.html["網格節點退役（StorageGRID 11.8 文件站點）"^]。
. 從儲存池和 ILM 策略中刪除所有存檔節點參考。看 https://kb.netapp.com/hybrid/StorageGRID/Maintenance/StorageGRID_11.9_software_upgrade_resolution_guide["NetApp知識庫： StorageGRID 11.9 軟體升級解決指南"^]。




 a| 
透過 CIFS/Samba 進行審計導出
 a| 
11.1
 a| 
11.6
 a| 
11.7
 a| 



 a| 
CLB 服務
 a| 
11.4
 a| 
11.6
 a| 
11.7
 a| 



 a| 
Docker容器引擎
 a| 
11.8
 a| 
11.9
 a| 
待定
 a| 
不再支援將 Docker 作為純軟體部署的容器引擎。Docker 將在未來的版本中被另一個容器引擎取代。請參閱link:../ubuntu/software-requirements.html#docker-versions-tested["目前支援的 Docker 版本列表"]。



 a| 
NFS 審計導出
 a| 
11.8
 a| 
11.9
 a| 
12.0
 a| 
https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-audit-client-access.html["設定 NFS 的稽核用戶端存取（StorageGRID 11.8）"^]



 a| 
Swift API 支援
 a| 
11.7
 a| 
11.9
 a| 
12.0
 a| 
https://docs.netapp.com/us-en/storagegrid-118/swift/index.html["使用 Swift REST API（StorageGRID 11.8）"^]



 a| 
RHEL 8.8
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
RHEL 9.0
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
RHEL 9.2
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
Ubuntu 18.04
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
Ubuntu 20.04
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
Debian 11
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 

|===
另請參閱：

* link:../upgrade/changes-to-grid-management-api.html["網格管理 API 的變更"]
* link:../upgrade/changes-to-tenant-management-api.html["租戶管理 API 的變更"]

