---
permalink: upgrade/troubleshooting-upgrade-issues.html 
sidebar: sidebar 
keywords: upgrade, troubleshoot, troubleshooting, errors, upgrade precheck 
summary: 如果升級時出現問題，您也許能夠自行解決問題。如果您無法解決問題，請收集盡可能多的信息，然後聯絡技術支援。 
---
= 解決升級問題
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果升級時出現問題，您也許能夠自行解決問題。如果您無法解決問題，請收集盡可能多的信息，然後聯絡技術支援。



== 升級未完成

以下部分說明如何從升級部分失敗的情況中復原。



=== 升級預檢查錯誤

為了檢測和解決問題，您可以在開始實際升級之前手動執行升級預檢查。大多數預檢錯誤都提供了有關如何解決問題的資訊。



=== 預配失敗

如果自動配置流程失敗，請聯絡技術支援。



=== 網格節點崩潰或無法啟動

如果網格節點在升級過程中崩潰或升級完成後無法成功啟動，請聯絡技術支援調查並修正任何潛在問題。



=== 提取或資料檢索中斷

如果在未升級網格節點時資料擷取或擷取意外中斷，請聯絡技術支援。



=== 資料庫升級錯誤

如果資料庫升級失敗並出現錯誤，請重試升級。如果再次失敗，請聯絡技術支援。

.相關資訊
link:checking-systems-condition-before-upgrading-software.html["升級軟體前檢查系統狀況"]



== 使用者介面問題

升級期間或升級後，您可能會遇到網格管理器或租用戶管理員的問題。



=== 網格管理器在升級過程中顯示多個錯誤訊息

如果在主管理節點升級時刷新瀏覽器或導航到另一個網格管理器頁面，您可能會看到多個「503：服務不可用」和「連接伺服器時出現問題」訊息。您可以放心地忽略這些訊息——節點升級後它們將不再出現。

如果這些訊息在您開始升級後出現超過一小時，則可能發生了一些事情，導致主管理節點無法升級。如果您無法自行解決問題，請聯絡技術支援。



=== Web 介面未如預期回應

StorageGRID軟體升級後，網格管理器或租用戶管理器可能無法如預期回應。

如果您在使用 Web 介面時遇到問題：

* 確保您使用的是link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
+

NOTE: 瀏覽器支援通常會隨著每個StorageGRID版本的發布而改變。

* 清除您的網頁瀏覽器快取。
+
清除快取會刪除先前版本的StorageGRID軟體所使用的過時資源，並允許使用者介面再次正常運作。有關說明，請參閱 Web 瀏覽器的文件。





== “Docker 映像可用性檢查”錯誤訊息

嘗試啟動升級程序時，您可能會收到一條錯誤訊息，指出“Docker 映像可用性檢查驗證套件識別出以下問題。”必須先解決所有問題，然後才能完成升級。

如果您不確定解決已發現的問題需要進行哪些更改，請聯絡技術支援。

[cols="1a,1a,1a"]
|===
| 訊息 | 原因 | 解決方案 


 a| 
無法確定升級版本。升級版本資訊文件 `{file_path}`與預期格式不符。
 a| 
升級包已損壞。
 a| 
重新上傳升級包，再試一次。如果問題仍然存在，請聯絡技術支援。



 a| 
升級版本資訊文件 `{file_path}`未找到。無法確定升級版本。
 a| 
升級包已損壞。
 a| 
重新上傳升級包，再試一次。如果問題仍然存在，請聯絡技術支援。



 a| 
無法確定目前安裝的發行版本 `{node_name}`。
 a| 
節點上的關鍵檔案已損壞。
 a| 
聯繫技術支援。



 a| 
嘗試列出版本時出現連線錯誤 `{node_name}`
 a| 
節點離線或連線中斷。
 a| 
檢查以確保所有節點均在線且可從主管理節點訪問，然後重試。



 a| 
節點的主機 `{node_name}`沒有StorageGRID `{upgrade_version}`圖像已載入。升級前必須在主機上安裝映像和服務。
 a| 
節點運作的主機上尚未安裝升級所需的 RPM 或 DEB 套件，或映像檔仍處於匯入過程中。

*注意：*此錯誤僅適用於在 Linux 上作為容器運行的節點。
 a| 
檢查以確保所有運行節點的 Linux 主機上都已安裝 RPM 或 DEB 套件。確保服務和圖像檔案的版本正確。等待幾分鐘，然後再試一次。

看link:../upgrade/linux-installing-rpm-or-deb-package-on-all-hosts.html["Linux：在所有主機上安裝 RPM 或 DEB 套件"] 。



 a| 
檢查節點時出錯 `{node_name}`
 a| 
發生了意外錯誤。
 a| 
等待幾分鐘，然後再試一次。



 a| 
運行預檢時未捕獲的錯誤。 `{error_string}`
 a| 
發生了意外錯誤。
 a| 
等待幾分鐘，然後再試一次。

|===