---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 11.9 
summary: 此版本的StorageGRID引入了以下功能。 
---
= StorageGRID 11.9 中的新功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
此版本的StorageGRID引入了以下特性和功能變化。



== 可擴展性



=== 僅資料儲存節點

為了實現更精細的擴展，您現在可以安裝link:../primer/what-storage-node-is.html#types-of-storage-nodes["僅資料儲存節點"]。當元資料處理並不重要時，您可以經濟高效地優化基礎架構。這種靈活性有助於適應不同的工作負載和成長模式。



== 雲端儲存池增強功能



=== 隨時隨地使用 IAM 角色

StorageGRID現在支援使用link:../ilm/creating-cloud-storage-pool.html["Amazon S3 中適用於雲端儲存池的 IAM 角色"]。

如果這些憑證被洩露，使用長期憑證存取 S3 儲存桶會帶來安全風險。短期憑證的有效期有限，從而降低了未經授權存取的風險。



=== S3 物件鎖定儲存桶

您現在可以link:../ilm/creating-cloud-storage-pool.html["使用 Amazon S3 端點設定雲端儲存池"]。 S3 物件鎖定有助於防止意外或惡意刪除物件。如果將資料從StorageGRID分層到 Amazon S3，則在兩個系統上啟用物件鎖可以增強整個資料生命週期的資料保護。



== 多租戶



=== 存儲桶限制

經過link:../tenant/creating-s3-bucket.html["設定 S3 儲存桶的限制"]，可以防止租戶壟斷容量。此外，不受控制的成長可能會導致意外的成本。透過定義限制，您可以更好地估算租戶儲存費用。



=== 每個租戶 5,000 個 bucket

為了增強可擴展性， StorageGRID現在最多支持link:../s3/operations-on-buckets.html["每個租戶 5,000 個 S3 儲存桶"]。每個網格最多可以有 100,000 個桶。

為了支援 5,000 個儲存桶，網格中的每個儲存節點必須至少具有 64 GB 的 RAM。



== S3 物件鎖定改進

每個租戶的配置功能提供了靈活性和資料安全性的適當平衡。現在您可以配置每個租戶的保留設定以：

* 允許或禁止合規模式
* 設定最長保留期


參考：

* link:../ilm/managing-objects-with-s3-object-lock.html["使用 S3 對象鎖管理對象"]
* link:../ilm/how-object-retention-is-determined.html#how-grid-administrators-control-object-retention["網格管理員如何控制物件保留"]
* link:../admin/creating-tenant-account.html["建立租用戶帳戶"]




== S3 相容性



=== x-amz-checksum-sha256 校驗和

* S3 REST API 現在提供對連結的支援：../s3/operations-on-objects.html[`x-amz-checksum-sha256`校驗和]。
* StorageGRID現在為 PUT、GET 和 HEAD 操作提供 SHA-256 校驗和支援​​。這些校驗和增強了資料完整性。




=== S3 協定支援的變化

* 增加了對 Amazon S3 Mountpoint 的支持，允許應用程式直接連接到 S3 儲存桶，就像它們是本機檔案系統一樣。現在您可以將StorageGRID與更多應用程式和更多用例一起使用。
* 作為新增對 Mountpoint 支援的一部分， StorageGRID 11.9 包含link:../s3/index.html#updates-to-rest-api-support["對 S3 協定支援的其他更改"]。




== 維護和可支援性



=== AutoSupport

link:../admin/what-is-autosupport.html["AutoSupport"]現在可自動為傳統設備建立硬體故障案例。



=== 擴展節點克隆操作

節點克隆可用性已擴展，以支援更大的儲存節點。



=== 改進了 ILM 對過期刪除標記的處理

ILM 攝取時間規則的時間段為數天，現在也可以刪除過期的物件刪除標記。只有在經過幾天的時間段並且目前刪除標記已過期（沒有非目前版本）時，才會刪除刪除標記。

參考link:../ilm/how-objects-are-deleted.html#delete-s3-versioned-objects["如何刪除 S3 版本控制對象"]和link:../ilm/example-8-priorities-for-s3-bucket-lifecycle-and-ilm-policy.html#example-of-bucket-lifecycle-taking-priority-over-ilm-policy["儲存桶生命週期優先於 ILM 策略的範例"]。



=== 改進節點退役

為了順利高效地過渡到StorageGRID下一代硬件，link:../maintain/grid-node-decommissioning.html["節點退役"]已得到改善。



=== 負載平衡器端點的系統日誌

負載平衡器端點存取日誌包含故障排除訊息，例如 HTTP 狀態碼。 StorageGRID現在支援link:../monitor/configure-audit-messages.html["將這些日誌匯出到外部系統日誌伺服器"]。此增強功能可實現更有效率的日誌管理以及與現有監控和警報系統的整合。



=== 維護和可支援性的額外增強

* 指標 UI 更新
* 新的作業系統資格
* 支援新的第三方元件




== 安全



=== SSH 存取金鑰輪換

電網管理員現在可以link:../admin/change-ssh-access-passwords.html["更新和輪換 SSH 金鑰"]。輪換 SSH 金鑰的能力是一種安全最佳實踐和主動防禦機制。



=== 根登入警報

當未知實體以 root 身分登入網格管理員時，link:../monitor/alerts-reference.html["觸發警報"] 。監控根 SSH 登入是保護基礎架構的主動步驟。



== 網格管理器增強功能



=== 擦除編碼設定檔頁面已移動

擦除編碼設定檔頁面現在位於 *配置* > *系統* > *擦除編碼*。它曾經位於 ILM 選單中。



=== 搜尋增強功能

這link:../primer/exploring-grid-manager.html#search-field["網格管理器中的搜尋字段"]現在包括更好的匹配邏輯，允許您透過搜尋常用縮寫和頁面內某些設定的名稱來尋找頁面。您還可以搜尋更多類型的項目，例如節點、使用者和租戶帳戶。
