---
permalink: ubuntu/creating-node-configuration-files.html 
sidebar: sidebar 
keywords: how to create ubuntu or debian node configuration files, port, remap, port remap 
summary: 節點設定檔是小型文字文件，提供StorageGRID主機服務啟動節點並將其連接到適當的網路和區塊儲存資源所需的資訊。節點設定檔用於虛擬節點，不用於設備節點。 
---
= 為 Ubuntu 或 Debian 部署建立節點配置文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
節點設定檔是小型文字文件，提供StorageGRID主機服務啟動節點並將其連接到適當的網路和區塊儲存資源所需的資訊。節點設定檔用於虛擬節點，不用於設備節點。



== 節點設定檔的位置

將每個StorageGRID節點的設定檔放在 `/etc/storagegrid/nodes`節點將運行的主機上的目錄。例如，如果您打算在 HostA 上執行一個管理節點、一個網關節點和一個儲存節點，則必須將三個節點設定檔放在 `/etc/storagegrid/nodes`在 HostA 上。

您可以使用文字編輯器（例如 vim 或 nano）直接在每個主機上建立設定文件，也可以在其他地方建立它們並將它們移至每個主機。



== 節點設定檔的命名

設定檔的名稱很重要。格式為 `node-name.conf`， 在哪裡 `node-name`是您指派給節點的名稱。此名稱出現在StorageGRID安裝程式中，用於節點維護作業，例如節點遷移。

節點名稱必須遵循以下規則：

* 必須是唯一的
* 必須以字母開頭
* 可以包含字元 A 到 Z 和 a 到 z
* 可以包含數字 0 到 9
* 可以包含一個或多個連字符 (-)
* 不得超過 32 個字符，不包括 `.conf`擴大


任何文件 `/etc/storagegrid/nodes`不遵循這些命名約定的內容將不會被主機服務解析。

如果您打算為電網採用多站點拓撲，則典型的節點命名方案可能是：

`site-nodetype-nodenumber.conf`

例如，您可以使用 `dc1-adm1.conf`對於資料中心 1 中的第一個管理節點，以及 `dc2-sn3.conf`用於資料中心 2 中的第三個儲存節點。但是，您可以使用任何您喜歡的方案，只要所有節點名稱都遵循命名規則。



== 節點設定檔的內容

設定檔包含鍵/值對，每行一個鍵和一個值。對於每個鍵/值對，請遵循以下規則：

* 鍵和值必須用等號分隔(`=`) 和可選的空格。
* 鍵中不能包含空白。
* 值可以包含嵌入空格。
* 任何前導或尾隨空格都會被忽略。


下表定義了所有受支援的鍵的值。每個鍵都有以下標識之一：

* *必需*：每個節點或指定節點類型都需要
* *最佳實務*：可選，但建議使用
* *可選*：所有節點可選




=== 管理網路金鑰



==== 管理員IP

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
此節點所屬網格的主管理節點的網格網路 IPv4 位址。對於 NODE_TYPE = VM_Admin_Node 和 ADMIN_ROLE = Primary 的網格節點，使用您為 GRID_NETWORK_IP 指定的相同值。如果省略此參數，節點將嘗試使用 mDNS 發現主管理節點。

link:how-grid-nodes-discover-primary-admin-node.html["網格節點如何發現主管理節點"]

*注意*：在主管理節點上，此值會被忽略，甚至可能被禁止。
 a| 
最佳實踐

|===


==== 管理網路配置

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
DHCP、靜態或停用
 a| 
選修的

|===


==== 管理員網絡

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
以 CIDR 表示法表示的子網路的逗號分隔列表，此節點應使用管理網路閘道與其進行通訊。

例子： `172.16.0.0/21,172.17.0.0/21`
 a| 
選修的

|===


==== 管理員網路網關

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
此節點的本機管理網路閘道的 IPv4 位址。必須位於由 ADMIN_NETWORK_IP 和 ADMIN_NETWORK_MASK 定義的子網路上。對於 DHCP 配置的網絡，此值將被忽略。

例子：

`1.1.1.1`

`10.224.4.81`
 a| 
如果 `ADMIN_NETWORK_ESL`已指定。否則為可選。

|===


==== 管理網路 IP

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
管理網路上此節點的 IPv4 位址。僅當 ADMIN_NETWORK_CONFIG = STATIC 時才需要此鍵；不要將其指定為其他值。

例子：

`1.1.1.1`

`10.224.4.81`
 a| 
當 ADMIN_NETWORK_CONFIG = STATIC 時必需。

否則為可選。

|===


==== 管理員網路MAC位址

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
容器中管理網路介面的 MAC 位址。

此字段是可選的。如果省略，則會自動產生 MAC 位址。

必須是用冒號分隔的 6 對十六進位數字。

例子： `b2:9c:02:c2:27:10`
 a| 
選修的

|===


==== 管理網路遮罩

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
管理網路上此節點的 IPv4 網路遮罩。當 ADMIN_NETWORK_CONFIG = STATIC 時指定此鍵；不要為其他值指定它。

例子：

`255.255.255.0`

`255.255.248.0`
 a| 
如果指定了 ADMIN_NETWORK_IP 且 ADMIN_NETWORK_CONFIG = STATIC，則必要。

否則為可選。

|===


==== 管理網路最大傳輸單元 (MTU)

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
管理網路上此節點的最大傳輸單元 (MTU)。如果 ADMIN_NETWORK_CONFIG = DHCP，則不要指定。如果指定，則值必須介於 1280 和 9216 之間。如果省略，則使用 1500。

如果要使用巨型幀，請將 MTU 設定為適合巨型幀的值，例如 9000。否則，保留預設值。

*重要*：網路的 MTU 值必須與節點連接到的交換器連接埠上配置的值相符。否則，可能會出現網路效能問題或資料包遺失。

例子：

`1500`

`8192`
 a| 
選修的

|===


==== 管理網路目標

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
用於StorageGRID節點管理網路存取的主機設備的名稱。僅支援網路介面名稱。通常，您使用的介面名稱與 GRID_NETWORK_TARGET 或 CLIENT_NETWORK_TARGET 指定的介面名稱不同。

*注意*：不要使用綁定或橋接設備作為網路目標。在綁定設備上設定 VLAN（或其他虛擬介面），或使用網橋和虛擬乙太網路（veth）對。

*最佳實務*：即使此節點最初沒有管理網路 IP 位址，也要指定值。然後，您可以稍後新增管理網路 IP 位址，而無需重新設定主機上的節點。

例子：

`bond0.1002`

`ens256`
 a| 
最佳實踐

|===


==== 管理網路目標類型

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
介面（這是唯一支援的值。）
 a| 
選修的

|===


==== ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
對還是錯

將該鍵設為「true」以使StorageGRID容器使用管理網路上主機目標介面的 MAC 位址。

*最佳實務：*在需要混雜模式的網路中，請改用 ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC 鍵。

有關 MAC 克隆的更多詳細資訊：

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 位址複製的注意事項與建議（Red Hat Enterprise Linux）"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 位址克隆的注意事項和建議（Ubuntu 或 Debian）"]

 a| 
最佳實踐

|===


==== 管理員角色

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
主或非主

只有當 NODE_TYPE = VM_Admin_Node 時才需要此鍵；不要為其他節點類型指定它。
 a| 
當 NODE_TYPE = VM_Admin_Node 時必需

否則為可選。

|===


=== 區塊設備密鑰



==== 區塊設備審計日誌

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
此節點將用於持久性儲存稽核日誌的區塊設備特殊檔案的路徑和名稱。

例子：

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-audit-logs`
 a| 
對於 NODE_TYPE = VM_Admin_Node 的節點是必要的。不要為其他節點類型指定它。

|===


==== BLOCK_DEVICE_RANGEDB_nnn

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
此節點將用於持久性物件儲存的區塊設備特殊檔案的路徑和名稱。僅 NODE_TYPE = VM_Storage_Node 的節點需要此鍵；不要為其他節點類型指定它。

僅 BLOCK_DEVICE_RANGEDB_000 是必需的；其餘的是可選的。為 BLOCK_DEVICE_RANGEDB_000 指定的區塊設備必須至少為 4 TB；其他的可以更小。

不要留下空隙。如果您指定 BLOCK_DEVICE_RANGEDB_005，則也必須指定 BLOCK_DEVICE_RANGEDB_004。

*注意*：為了與現有部署相容，升級的節點支援兩位數金鑰。

例子：

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-rangedb-000`
 a| 
必需的：

BLOCK_DEVICE_RANGEDB_000

選修的：

BLOCK_DEVICE_RANGEDB_001

BLOCK_DEVICE_RANGEDB_002

BLOCK_DEVICE_RANGEDB_003

BLOCK_DEVICE_RANGEDB_004

BLOCK_DEVICE_RANGEDB_005

BLOCK_DEVICE_RANGEDB_006

BLOCK_DEVICE_RANGEDB_007

BLOCK_DEVICE_RANGEDB_008

BLOCK_DEVICE_RANGEDB_009

BLOCK_DEVICE_RANGEDB_010

BLOCK_DEVICE_RANGEDB_011

BLOCK_DEVICE_RANGEDB_012

BLOCK_DEVICE_RANGEDB_013

BLOCK_DEVICE_RANGEDB_014

BLOCK_DEVICE_RANGEDB_015

|===


==== 區塊設備表

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
此節點將用於資料庫表的持久性儲存的區塊設備特殊檔案的路徑和名稱。僅 NODE_TYPE = VM_Admin_Node 的節點需要此鍵；不要為其他節點類型指定它。

例子：

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-tables`
 a| 
必需的

|===


==== 區塊設備變數本地

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
此節點將使用的區塊設備特殊檔案的路徑和名稱 `/var/local`持久性存儲。

例子：

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-var-local`
 a| 
必需的

|===


=== 用戶端網路金鑰



==== 客戶端網路配置

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
DHCP、靜態或停用
 a| 
選修的

|===


==== 用戶端網路網關

[cols="4a,2a"]
|===


 a| 
價值
 a| 
指定



 a| 
此節點的本機用戶端網路閘道的 IPv4 位址，必須位於 CLIENT_NETWORK_IP 和 CLIENT_NETWORK_MASK 定義的子網路上。對於 DHCP 配置的網絡，此值將被忽略。

例子：

`1.1.1.1`

`10.224.4.81`
 a| 
選修的

|===


==== 用戶端網路 IP

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
用戶端網路上此節點的 IPv4 位址。

僅當 CLIENT_NETWORK_CONFIG = STATIC 時才需要此鍵；不要將其指定為其他值。

例子：

`1.1.1.1`

`10.224.4.81`
 a| 
當 CLIENT_NETWORK_CONFIG = STATIC 時必需

否則為可選。

|===


==== 用戶端網路MAC位址

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
容器中用戶端網路介面的 MAC 位址。

此字段是可選的。如果省略，則會自動產生 MAC 位址。

必須是用冒號分隔的 6 對十六進位數字。

例子： `b2:9c:02:c2:27:20`
 a| 
選修的

|===


==== 客戶端網路遮罩

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
用戶端網路上此節點的 IPv4 網路遮罩。

當 CLIENT_NETWORK_CONFIG = STATIC 時指定此鍵；不要為其他值指定它。

例子：

`255.255.255.0`

`255.255.248.0`
 a| 
如果指定了 CLIENT_NETWORK_IP 且 CLIENT_NETWORK_CONFIG = STATIC，則為必要

否則為可選。

|===


==== 客戶端網路 MTU

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
客戶端網路上此節點的最大傳輸單元 (MTU)。如果 CLIENT_NETWORK_CONFIG = DHCP，則不要指定。如果指定，則值必須介於 1280 和 9216 之間。如果省略，則使用 1500。

如果要使用巨型幀，請將 MTU 設定為適合巨型幀的值，例如 9000。否則，保留預設值。

*重要*：網路的 MTU 值必須與節點連接到的交換器連接埠上配置的值相符。否則，可能會出現網路效能問題或資料包遺失。

例子：

`1500`

`8192`
 a| 
選修的

|===


==== 客戶端網路目標

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
用於StorageGRID節點客戶端網路存取的主機設備的名稱。僅支援網路介面名稱。通常，您使用的介面名稱與 GRID_NETWORK_TARGET 或 ADMIN_NETWORK_TARGET 指定的介面名稱不同。

*注意*：不要使用綁定或橋接設備作為網路目標。在綁定設備上設定 VLAN（或其他虛擬介面），或使用網橋和虛擬乙太網路（veth）對。

*最佳實務：*即使此節點最初沒有客戶端網路 IP 位址，也要指定值。然後，您可以稍後新增客戶端網路 IP 位址，而無需重新配置主機上的節點。

例子：

`bond0.1003`

`ens423`
 a| 
最佳實踐

|===


==== 用戶端網路目標類型

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
介面（這是唯一支援的值。）
 a| 
選修的

|===


==== 用戶端網路目標類型介面克隆MAC位址

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
對還是錯

將該鍵設定為「true」以使StorageGRID容器使用客戶端網路上主機目標介面的 MAC 位址。

*最佳實務：*在需要混雜模式的網路中，請改用 CLIENT_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC 鍵。

有關 MAC 克隆的更多詳細資訊：

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 位址複製的注意事項與建議（Red Hat Enterprise Linux）"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 位址克隆的注意事項和建議（Ubuntu 或 Debian）"]

 a| 
最佳實踐

|===


=== 網格網路鍵



==== 網格網路配置

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
靜態或 DHCP

如果未指定，則預設為 STATIC。
 a| 
最佳實踐

|===


==== GRID_NETWORK_GATEWAY

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
此節點的本機網格網路閘道的 IPv4 位址，必須位於由 GRID_NETWORK_IP 和 GRID_NETWORK_MASK 定義的子網路上。對於 DHCP 配置的網絡，此值將被忽略。

如果網格網路是沒有網關的單一子網，請使用子網路的標準網關位址（XYZ1）或此節點的 GRID_NETWORK_IP 值；任一值將簡化未來潛在的網格網路擴充。
 a| 
必需的

|===


==== 網格網路IP

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
網格網路上此節點的 IPv4 位址。僅當 GRID_NETWORK_CONFIG = STATIC 時才需要此鍵；不要將其指定為其他值。

例子：

`1.1.1.1`

`10.224.4.81`
 a| 
當 GRID_NETWORK_CONFIG = STATIC 時必需

否則為可選。

|===


==== 網格網路MAC位址

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
容器中網格網路介面的 MAC 位址。

必須是用冒號分隔的 6 對十六進位數字。

例子： `b2:9c:02:c2:27:30`
 a| 
選修的

如果省略，則會自動產生 MAC 位址。

|===


==== 網格網路遮罩

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
網格網路上此節點的 IPv4 網路遮罩。當 GRID_NETWORK_CONFIG = STATIC 時指定此鍵；不要為其他值指定它。

例子：

`255.255.255.0`

`255.255.248.0`
 a| 
當指定 GRID_NETWORK_IP 且 GRID_NETWORK_CONFIG = STATIC 時必要。

否則為可選。

|===


==== GRID_NETWORK_MTU

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
網格網路上此節點的最大傳輸單元 (MTU)。如果 GRID_NETWORK_CONFIG = DHCP，則不要指定。如果指定，則值必須介於 1280 和 9216 之間。如果省略，則使用 1500。

如果要使用巨型幀，請將 MTU 設定為適合巨型幀的值，例如 9000。否則，保留預設值。

*重要*：網路的 MTU 值必須與節點連接到的交換器連接埠上配置的值相符。否則，可能會出現網路效能問題或資料包遺失。

*重要*：為了獲得最佳網路效能，所有節點都應在其網格網路介面上配置相似的 MTU 值。如果各節點上的網格網路的 MTU 設定有顯著差異，則會觸發*網格網路 MTU 不符*警報。所有網路類型的 MTU 值不必相同。

例子：

`1500`

`8192`
 a| 
選修的

|===


==== 網格網路目標

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
用於StorageGRID節點網格網路存取的主機設備的名稱。僅支援網路介面名稱。通常，您使用的介面名稱與為 ADMIN_NETWORK_TARGET 或 CLIENT_NETWORK_TARGET 指定的介面名稱不同。

*注意*：不要使用綁定或橋接設備作為網路目標。在綁定設備上設定 VLAN（或其他虛擬介面），或使用網橋和虛擬乙太網路（veth）對。

例子：

`bond0.1001`

`ens192`
 a| 
必需的

|===


==== 網格網路目標類型

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
介面（這是唯一支援的值。）
 a| 
選修的

|===


==== GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
對還是錯

將該鍵的值設為“true”，以使StorageGRID容器使用網格網路上主機目標介面的 MAC 位址。

*最佳實務：*在需要混雜模式的網路中，請改用 GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC 鍵。

有關 MAC 克隆的更多詳細資訊：

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 位址複製的注意事項與建議（Red Hat Enterprise Linux）"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 位址克隆的注意事項和建議（Ubuntu 或 Debian）"]

 a| 
最佳實踐

|===


=== 安裝密碼密鑰（臨時）



==== 自訂臨時密碼哈希

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
對於主管理節點，在安裝期間為StorageGRID安裝 API 設定預設臨時密碼。

*注意*：僅在主管理節點上設定安裝密碼。如果您嘗試在另一個節點類型上設定密碼，則節點設定檔的驗證將會失敗。

安裝完成後，設定此值不會產生任何效果。

如果省略此鍵，則預設不設定臨時密碼。或者，您可以使用StorageGRID安裝 API 設定臨時密碼。

必須是 `crypt()`SHA-512 密碼雜湊及其格式 `$6$<salt>$<password hash>`密碼長度至少為 8 個字元且不超過 32 個字元。

可以使用 CLI 工具產生此哈希，例如 `openssl passwd`SHA-512 模式下的命令。
 a| 
最佳實踐

|===


=== 介面關鍵



==== 介面目標_nnnn

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
您想要新增至此節點的額外介面的名稱和可選描述。您可以為每個節點新增多個額外的介面。

對於 _nnnn_，為您要新增的每個 INTERFACE_TARGET 條目指定一個唯一的編號。

對於該值，請指定裸機主機上的實體介面的名稱。然後，可選擇新增逗號並提供介面的描述，該描述顯示在 VLAN 介面頁面和 HA 群組頁面上。

例子： `INTERFACE_TARGET_0001=ens256, Trunk`

如果新增中繼介面，則必須在StorageGRID中設定 VLAN 介面。如果新增存取接口，則可以將該介面直接新增至 HA 群組；無需設定 VLAN 介面。
 a| 
選修的

|===


=== 最大 RAM 鍵



==== 最大記憶體

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
此節點允許消耗的最大 RAM 量。如果省略此鍵，則節點沒有記憶體限制。為生產級節點設定此欄位時，請指定一個至少比系統總 RAM 少 24 GB 且少 16 到 32 GB 的值。

*注意*：RAM 值會影響節點的實際元資料保留空間。查看link:../admin/managing-object-metadata-storage.html["元資料保留空間的描述"]。

該欄位的格式為 `_numberunit_`， 在哪裡 `_unit_`可以 `b`， `k` ， `m` ， 或者 `g`。

例子：

`24g`

`38654705664b`

*注意*：如果您想使用此選項，您必須啟用核心對記憶體 cgroups 的支援。
 a| 
選修的

|===


=== 節點類型鍵



==== 節點類型

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
節點類型：

* VM_Admin_Node
* VM_儲存_節點
* VM_Archive_Node
* VM_API_網關

 a| 
必需的

|===


==== 儲存類型

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
定義儲存節點包含的物件類型。有關更多信息，請參閱link:../primer/what-storage-node-is.html#types-of-storage-nodes["儲存節點的類型"] 。僅 NODE_TYPE = VM_Storage_Node 的節點需要此鍵；不要為其他節點類型指定它。儲存類型：

* 合併
* 數據
* 元數據


*注意*：如果未指定 STORAGE_TYPE，則儲存節點類型預設為組合（資料和元資料）。
 a| 
選修的

|===


=== 連接埠重新映射鍵



==== 連接埠重新映射

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
重新映射節點用於內部網格節點通訊或外部通訊的任何連接埠。如果企業網路政策限制StorageGRID使用的一個或多個端口，則需要重新映射端口，如link:../network/internal-grid-node-communications.html["內部網格節點通信"]或者link:../network/external-communications.html["外部溝通"]。

*重要*：不要重新映射您計劃用於配置負載平衡器端點的連接埠。

*注意*：如果僅設定了 PORT_REMAP，則您指定的對應將用於入站和出站通訊。如果也指定了 PORT_REMAP_INBOUND，則 PORT_REMAP 僅適用於出站通訊。

使用的格式為： `_network type_/_protocol_/_default port used by grid node_/_new port_` ， 在哪裡 `_network type_`是網格、管理員或客戶端，並且 `_protocol_`是 tcp 還是 udp。

例子： `PORT_REMAP = client/tcp/18082/443`

您也可以使用逗號分隔的清單重新對應多個連接埠。

例子： `PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80`
 a| 
選修的

|===


==== 連接埠重新映射入站

[cols="4a,2a"]
|===
| 價值 | 指定 


 a| 
將入站通訊重新對應到指定連接埠。如果您指定了 PORT_REMAP_INBOUND 但沒有指定 PORT_REMAP 的值，則該連接埠的出站通訊將保持不變。

*重要*：不要重新映射您計劃用於配置負載平衡器端點的連接埠。

使用的格式為： `_network type_/_protocol_/_remapped port_/_default port used by grid node_` ， 在哪裡 `_network type_`是網格、管理員或客戶端，並且 `_protocol_`是 tcp 還是 udp。

例子： `PORT_REMAP_INBOUND = grid/tcp/3022/22`

您也可以使用逗號分隔的清單重新對應多個入站連接埠。

例子： `PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22`
 a| 
選修的

|===