---
permalink: harden/hardening-guidelines-for-storagegrid-networks.html 
sidebar: sidebar 
keywords: hardening guidelines, networks, networking, security 
summary: StorageGRID系統每個網格節點最多支援三個網路接口，可讓您為每個單獨的網格節點配置網路以滿足您的安全性和存取要求。 
---
= StorageGRID網路強化指南
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID系統每個網格節點最多支援三個網路接口，可讓您為每個單獨的網格節點配置網路以滿足您的安全性和存取要求。

有關StorageGRID網路的詳細信息，請參閱link:../network/storagegrid-network-types.html["StorageGRID網路類型"]。



== 網格網路指南

您必須為所有內部StorageGRID流量配置一個網格網路。所有網格節點都在網格網路上，並且它們必須能夠與所有其他節點通訊。

配置網格網路時，請遵循下列準則：

* 確保網路安全，免受不受信任的用戶端（例如開放網路上的用戶端）的攻擊。
* 如果可能的話，請將網格網路專門用於內部流量。管理網路和客戶端網路都有額外的防火牆限制，可以阻止外部流量流向內部服務。支援使用網格網路進行外部客戶端流量，但這種使用方式提供的保護層較少。
* 如果StorageGRID部署跨越多個資料中心，請在網格網路上使用虛擬私人網路 (VPN) 或等效網路為內部流量提供額外保護。
* 某些維護程序需要在主管理節點和所有其他網格節點之間的連接埠 22 上進行安全外殼 (SSH) 存取。使用外部防火牆限制對受信任用戶端的 SSH 存取。




== 管理網路指南

管理網路通常用於管理任務（使用網格管理器或 SSH 的受信任員工）以及與其他受信任服務（如 LDAP、DNS、NTP 或 KMS（或 KMIP 伺服器））進行通訊。但是， StorageGRID內部並不會強制執行這種用法。

如果您使用管理網絡，請遵循以下準則：

* 阻止管理網路上的所有內部流量連接埠。查看link:../network/internal-grid-node-communications.html["內部連接埠列表"]。
* 如果不受信任的用戶端可以存取管理網絡，請使用外部防火牆阻止對管理網路上的StorageGRID的存取。




== 客戶網路指南

客戶端網路通常用於租戶和與外部服務（例如 CloudMirror 複製服務或其他平台服務）進行通訊。但是， StorageGRID內部並不會強制執行這種用法。

如果您使用客戶端網絡，請遵循以下準則：

* 阻止客戶端網路上的所有內部流量連接埠。查看link:../network/internal-grid-node-communications.html["內部連接埠列表"]。
* 僅在明確配置的端點上接受入站用戶端流量。查看有關link:../admin/manage-firewall-controls.html["管理防火牆控制"]。

