---
permalink: network/linux-deployments.html 
sidebar: sidebar 
keywords: linux network, container engine, red hat enterprise linux rhel network, ubuntu network 
summary: 為了提高效率、可靠性和安全性， StorageGRID系統作為容器引擎的集合在 Linux 上運作。  StorageGRID系統中不需要與容器引擎相關的網路配置。 
---
= Linux 部署
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
為了提高效率、可靠性和安全性， StorageGRID系統作為容器引擎的集合在 Linux 上運作。  StorageGRID系統中不需要與容器引擎相關的網路配置。

使用非綁定設備（例如 VLAN 或虛擬乙太網路 (veth) 對）作為容器網路介面。在節點設定檔中將此設備指定為網路介面。


CAUTION: 請勿直接使用綁定或橋接設備作為容器網路介面。這樣做可能會阻止節點啟動，因為在容器命名空間中使用 macvlan 與綁定和橋接設備存在核心問題。

請參閱安裝說明link:../rhel/index.html["紅帽企業 Linux"]或者link:../ubuntu/index.html["Ubuntu 或 Debian"]部署。



== 容器引擎部署的主機網路配置

在容器引擎平台上開始StorageGRID部署之前，請確定每個節點將使用哪些網路（網格、管理、客戶端）。您必須確保每個節點的網路介面都配置在正確的虛擬或實體主機介面上，並且每個網路都有足夠的頻寬。



=== 實體主機

如果您使用實體主機來支援網格節點：

* 確保所有主機的每個節點介面都使用相同的主機介面。此策略簡化了主機配置並支援未來的節點遷移。
* 取得實體主機本身的 IP 位址。
+

NOTE: 主機上的實體介面可供主機本身以及主機上執行的一個或多個節點使用。使用此介面指派給主機或節點的任何 IP 位址都必須是唯一的。主機和節點不能共享IP位址。

* 向主機開放所需的連接埠。
* 如果您打算在StorageGRID中使用 VLAN 接口，則主機必須具有一個或多個中繼介面以提供對所需 VLAN 的存取。這些介面可以作為 eth0、eth2 或附加介面傳遞到節點容器中。若要新增中繼或存取接口，請參閱以下內容：
+
** *RHEL（安裝節點之前）*：link:../rhel/creating-node-configuration-files.html["建立節點設定檔"]
** *Ubuntu 或 Debian（安裝節點之前）*：link:../ubuntu/creating-node-configuration-files.html["建立節點設定檔"]
** *RHEL、Ubuntu 或 Debian（安裝節點後）*：link:../maintain/linux-adding-trunk-or-access-interfaces-to-node.html["Linux：為節點新增主幹或存取介面"]






=== 最小頻寬建議

下表提供了每種類型的StorageGRID節點和每種類型的網路的最低 LAN 頻寬建議。您必須為每個實體或虛擬主機配備足夠的網路頻寬，以滿足您計劃在該主機上執行的StorageGRID節點總數和類型的整體最低頻寬需求。

[cols="1a,1a,1a,1a"]
|===
| 節點類型 3+| 網路類型 


 a| 
 a| 
網格
 a| 
行政
 a| 
用戶端



 a| 
 a| 
*最低 LAN 頻寬*



 a| 
行政
 a| 
10 Gbps
 a| 
1 Gbps
 a| 
1 Gbps



 a| 
閘道
 a| 
10 Gbps
 a| 
1 Gbps
 a| 
10 Gbps



 a| 
儲存
 a| 
10 Gbps
 a| 
1 Gbps
 a| 
10 Gbps



 a| 
檔案
 a| 
10 Gbps
 a| 
1 Gbps
 a| 
10 Gbps

|===

NOTE: 此表不包括存取共用儲存所需的 SAN 頻寬。如果您使用透過乙太網路（iSCSI 或 FCoE）存取的共用存儲，則應在每個主機上配置單獨的實體介面以提供足夠的 SAN 頻寬。為了避免引入瓶頸，給定主機的 SAN 頻寬應大致與該主機上執行的所有儲存節點的總儲存節點網路頻寬相符。

根據您計劃在每個主機上執行的StorageGRID節點的數量和類型，使用該表確定每個主機上要設定的最小網路介面數量。

例如，要在單一主機上執行一個管理節點、一個網關節點和一個儲存節點：

* 在管理節點上連接網格和管理網路（需要 10 + 1 = 11 Gbps）
* 連接網關節點上的電網和客戶端網路（需要 10 + 10 = 20 Gbps）
* 連接儲存節點上的電網網路（需要 10 Gbps）


在這種情況下，您應該提供至少 11 + 20 + 10 = 41 Gbps 的網路頻寬，可以透過兩個 40 Gbps 介面或五個 10 Gbps 介面來滿足，可能會聚合成中繼，然後由承載主機所在實體資料中心本地的網格、管理和客戶端子網路的三個或更多客戶 VLAN 共用。

有關在StorageGRID叢集中的主機上設定實體和網路資源以準備StorageGRID部署的一些建議方法，請參閱下列內容：

* link:../rhel/configuring-host-network.html["設定主機網路（Red Hat Enterprise Linux）"]
* link:../ubuntu/configuring-host-network.html["設定主機網路（Ubuntu 或 Debian）"]

