= 什麼是 S3 物件鎖？
:allow-uri-read: 




== 什麼是 S3 物件鎖？

StorageGRID S3 物件鎖定功能是一種物件保護解決方案，相當於 Amazon Simple Storage Service (Amazon S3) 中的 S3 物件鎖定。

當為StorageGRID系統啟用全域 S3 物件鎖定設定時，S3 租用戶帳戶可以建立啟用或未啟用 S3 物件鎖定的儲存桶。如果儲存桶啟用了 S3 物件鎖，則需要儲存桶版本控制，並且會自動啟用。

*沒有 S3 物件鎖的儲存桶*只能包含未指定保留設定的物件。任何攝取的物件都不會有保留設定。

*具有 S3 物件鎖定的儲存桶*可以包含由 S3 用戶端應用程式指定的具有或不具有保留設定的物件。一些攝取的物件將具有保留設定。

*配置了 S3 物件鎖定和預設保留的儲存桶*可以擁有指定了保留設定的上傳物件和不帶保留設定的新物件。新物件使用預設設置，因為尚未在物件層級配置保留設定。

實際上，當配置預設保留時，所有新攝取的物件都有保留設定。沒有物件保留設定的現有物件不受影響。



=== 保留模式

StorageGRID S3 物件鎖定功能支援兩種保留模式，以對物件套用不同層級的保護。這些模式相當於 Amazon S3 保留模式。

* 在合規模式下：
+
** 在達到保留截止日期之前，無法刪除該物件。
** 物件的保留截止日期可以增加，但不能減少。
** 在達到該日期之前，不能刪除物件的保留截止日期。


* 在治理模式下：
+
** 具有特殊權限的使用者可以在請求中使用繞過標頭來修改某些保留設定。
** 這些用戶可以在達到保留截止日期之前刪除物件版本。
** 這些使用者可以增加、減少或刪除物件的保留期限。






=== 物件版本的保留設定

如果在建立儲存桶時啟用了 S3 物件鎖定，則使用者可以使用 S3 用戶端應用程式選擇性地為新增至儲存桶的每個物件指定以下保留設定：

* *保留模式*：合規或治理。
* *保留至日期*：如果對象版本的保留至日期在未來，則可以檢索該對象，但不能刪除它。
* *合法保留*：對物件版本套用合法保留會立即鎖定該物件。例如，您可能需要對與調查或法律糾紛相關的對象實施法律保留。合法保留沒有到期日，但會一直有效，直到明確取消。合法保留與保留截止日期無關。
+

NOTE: 如果某個物件處於合法保留之下，則無論其保留模式為何，任何人都無法刪除該物件。

+
有關對象設定的詳細信息，請參閱link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 設定 S3 物件鎖"]。





=== 儲存桶的預設保留設定

如果在建立儲存桶時啟用了 S3 物件鎖定，使用者可以選擇為儲存桶指定以下預設設定：

* *預設保留模式*：合規或治理。
* *預設保留期*：新增至此儲存桶的新物件版本應保留多長時間（從新增之日起）。


預設儲存桶設定僅適用於沒有自己的保留設定的新物件。新增或變更這些預設設定時，現有的儲存桶物件不會受到影響。

看link:../tenant/creating-s3-bucket.html["建立 S3 儲存桶"]和link:../tenant/update-default-retention-settings.html["更新 S3 物件鎖定預設保留"]。
