---
permalink: tenant/creating-another-users-s3-access-keys.html 
sidebar: sidebar 
keywords: how to create other user S3 access key 
summary: 如果您正在使用 S3 租用戶並且擁有適當的權限，則可以為其他使用者建立 S3 存取金鑰，例如需要存取儲存體桶和物件的應用程式。 
---
= 建立另一個使用者的 S3 存取金鑰
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您正在使用 S3 租用戶並且擁有適當的權限，則可以為其他使用者建立 S3 存取金鑰，例如需要存取儲存體桶和物件的應用程式。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您屬於具有link:tenant-management-permissions.html["Root存取權限"]。


.關於此任務
您可以為其他使用者建立一個或多個 S3 存取金鑰，以便他們可以為其租用戶帳戶建立和管理儲存桶。建立新的存取金鑰後，使用新的存取金鑰 ID 和秘密存取金鑰更新應用程式。為了安全起見，不要建立超過使用者所需的金鑰，並刪除未使用的金鑰。如果您只有一個密鑰並且它即將過期，請在舊密鑰過期之前建立新密鑰，然後刪除舊密鑰。

每個密鑰可以有特定的到期時間或沒有到期時間。請遵循以下有關到期時間的準則：

* 設定密鑰的過期時間，以限制使用者在一定時間內的存取。如果存取密鑰 ID 和秘密存取密鑰意外洩露，設定較短的到期時間可以幫助降低風險。過期的密鑰將自動刪除。
* 如果您的環境中的安全風險較低，且您不需要定期建立新金鑰，則不必為金鑰設定到期時間。如果您稍後決定建立新密鑰，請手動刪除舊密鑰。



CAUTION: 可以使用租用戶管理員中顯示的該使用者的存取金鑰 ID 和秘密存取金鑰來存取屬於該使用者的 S3 儲存桶和物件。因此，請像保護密碼一樣保護存取金鑰。定期輪換存取金鑰，從帳戶中刪除任何未使用的金鑰，並且切勿與其他使用者共用。

.步驟
. 選擇*存取管理* > *使用者*。
. 選擇您想要管理其 S3 存取金鑰的使用者。
+
出現使用者詳細資料頁面。

. 選擇*存取金鑰*，然後選擇*建立金鑰*。
. 執行下列操作之一：
+
** 選擇「不設定過期時間」來建立不會過期的密鑰。  (預設)
** 選擇*設定到期時間*，並設定到期日期和時間。
+

NOTE: 到期日最長為當期起五年。到期時間可以從當前時間開始至少一分鐘。



. 選擇*建立存取金鑰*。
+
出現「下載存取金鑰」對話框，其中列出存取金鑰 ID 和秘密存取金鑰。

. 將存取金鑰 ID 和秘密存取金鑰複製到安全位置，或選擇 *下載 .csv* 以儲存包含存取金鑰 ID 和秘密存取金鑰的電子表格檔案。
+

CAUTION: 複製或下載此資訊之前，請勿關閉此對話方塊。對話方塊關閉後，您無法複製或下載金鑰。

. 選擇*完成*。
+
新密鑰列在使用者詳細資料頁面的存取密鑰標籤上。

. 如果您的租用戶帳戶具有 *使用網格聯合連線* 權限，則可以選擇使用租用戶管理 API 將 S3 存取金鑰從來源網格上的租用戶手動複製到目標網格上的租用戶。看link:grid-federation-clone-keys-with-api.html["使用 API 克隆 S3 存取金鑰"] 。

