---
permalink: tenant/creating-s3-bucket.html 
sidebar: sidebar 
keywords: how to create S3 bucket 
summary: 您可以使用租用戶管理器為物件資料建立 S3 儲存桶。 
---
= 建立 S3 儲存桶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用租用戶管理器為物件資料建立 S3 儲存桶。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您屬於具有 Root 存取權或管理所有儲存桶的使用者群組link:tenant-management-permissions.html["允許"]。這些權限將覆蓋群組或儲存桶策略中的權限設定。
+

NOTE: 設定或修改儲存桶或物件的 S3 物件鎖定屬性的權限可以透過以下方式授予link:../s3/bucket-and-group-access-policies.html["儲存桶策略或群組策略"]。

* 如果您打算為儲存桶啟用 S3 物件鎖定，則網格管理員已為StorageGRID系統啟用全域 S3 物件鎖定設置，並且您已查看了 S3 物件鎖定儲存桶和物件的要求。
* 如果每個租戶有 5,000 個儲存桶，則網格中的每個儲存節點至少有 64 GB 的 RAM。
+

NOTE: 每個網格最多可以有 100,000 個桶。





== 訪問嚮導

.步驟
. 從儀表板中選擇 *查看儲存桶*，或選擇 *儲存（S3）* > *儲存桶*。
. 選擇*建立儲存桶*。




== 輸入詳細信息

.步驟
. 輸入儲存桶的詳細資訊。
+
[cols="1a,3a"]
|===
| 場地 | 描述 


 a| 
儲存桶名稱
 a| 
符合以下規則的儲存桶的名稱：

** 每個StorageGRID系統中必須是唯一的（而不僅僅是在租用戶帳戶內是唯一的）。
** 必須符合 DNS 標準。
** 必須包含至少 3 個字元且不超過 63 個字元。
** 每個標籤必須以小寫字母或數字開頭和結尾，並且只能使用小寫字母、數字和連字符。
** 虛擬託管樣式請求中不得包含句點。句點將導致伺服器通配符憑證驗證出現問題。


有關詳細信息，請參閱 https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["Amazon Web Services (AWS) 有關儲存桶命名規則的文檔"^]。

*注意*：建立儲存桶後，您無法變更儲存桶名稱。



 a| 
地區
 a| 
儲存桶的區域。

您的StorageGRID管理員管理可用區域。儲存桶的區域會影響應用於物件的資料保護策略。預設情況下，所有儲存桶均在 `us-east-1`地區。

*注意*：建立儲存桶後，您無法變更區域。

|===
. 選擇*繼續*。




== 管理設定

.步驟
. （可選）為儲存桶啟用物件版本控制。
+
如果您想要將每個物件的每個版本儲存在此儲存桶中，請啟用物件版本控制。然後，您可以根據需要檢索物件的先前版本。如果儲存桶將用於跨網格複製，則必須啟用物件版本控制。

. 如果啟用了全域 S3 物件鎖定設置，則可以選擇為儲存桶啟用 S3 物件鎖定，以使用一次寫入多次讀取 (WORM) 模型儲存物件。
+
只有當您需要將物件保留固定時間（例如，為了滿足某些監管要求）時，才會為儲存桶啟用 S3 物件鎖定。S3 物件鎖定是一種永久性設置，可協助您防止物件在固定時間內或無限期內被刪除或覆蓋。

+

CAUTION: 一旦為儲存桶啟用 S3 物件鎖定設置，就無法停用它。任何擁有正確權限的人都可以將物件新增到此儲存桶中，並且不能更改。您可能無法刪除這些物件或儲存桶本身。

+
如果您為儲存桶啟用 S3 物件鎖定，則儲存桶版本控制將自動啟用。

. 如果您選擇了“啟用 S3 物件鎖定”，則可以選擇為此儲存桶啟用“預設保留”。
+

NOTE: 您的網格管理員必須授予您以下權限link:../tenant/using-s3-object-lock.html["使用 S3 Object Lock 的特定功能"]。

+
當啟用*預設保留*時，新增至儲存桶的新物件將自動受到保護，免遭刪除或覆蓋。*預設保留*設定不適用於具有自己的保留期的物件。

+
.. 如果啟用了*預設保留*，請為儲存桶指定*預設保留模式*。
+
[cols="1a,2a"]
|===
| 預設保留模式 | 描述 


 a| 
治理
 a| 
*** 使用者 `s3:BypassGovernanceRetention`許可可以使用 `x-amz-bypass-governance-retention: true`請求標頭以繞過保留設定。
*** 這些用戶可以在達到保留截止日期之前刪除物件版本。
*** 這些使用者可以增加、減少或刪除物件的保留期限。




 a| 
遵守
 a| 
*** 在達到保留截止日期之前，無法刪除該物件。
*** 物件的保留截止日期可以增加，但不能減少。
*** 在達到該日期之前，不能刪除物件的保留截止日期。


*注意*：您的電網管理員必須允許您使用合規模式。

|===
.. 如果啟用了*預設保留*，請指定儲存桶的*預設保留期*。
+
*預設保留期*表示從提取新物件開始，新增至此儲存桶的新物件應保留多長時間。指定一個小於或等於網格管理員設定的租用戶最大保留期的值。

+
網格管理員建立租用戶時會設定最大保留期，其值可以是 1 天到 100 年。當您設定_預設_保留期時，它不能超過為最大保留期設定的值。如果需要，請您的網格管理員增加或減少最長保留期。



. [[capacity-limit]]可選，選擇*啟用容量限制*。
+
容量限制是此儲存桶中物件可用的最大容量。該值代表邏輯量（物件大小），而不是物理量（磁碟上的大小）。

+
如果沒有設定限制，則該儲存桶的容量是無限的。請參閱link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["容量限制使用情況"]了解更多。

. 選擇*建立儲存桶*。
+
儲存桶已建立並新增至「儲存桶」頁面上的表格中。

. 或者，選擇“前往儲存桶詳細資料頁面”link:viewing-s3-bucket-details.html["查看儲存桶詳細信息"]並執行額外的配置。

