---
permalink: tenant/creating-groups-for-swift-tenant.html 
sidebar: sidebar 
keywords: how to create Swift tenant groups 
summary: 您可以透過匯入聯合群組或建立本機群組來管理 Swift 租用戶帳戶的存取權。至少一個群組必須具有 Swift 管理員權限，這是管理 Swift 租用戶帳戶的容器和物件所必需的。 
---
= 為 Swift 租用戶建立群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以透過匯入聯合群組或建立本機群組來管理 Swift 租用戶帳戶的存取權。至少一個群組必須具有 Swift 管理員權限，這是管理 Swift 租用戶帳戶的容器和物件所必需的。


NOTE: 對 Swift 用戶端應用程式的支援已被棄用，並將在未來的版本中刪除。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您屬於具有link:tenant-management-permissions.html["Root存取權限"]。
* 如果您計劃匯入聯合群組，則必須link:using-identity-federation.html["配置身份聯合"]，且聯合群組已存在於配置的身份來源中。




== 存取建立群組精靈

.步驟
第一步，存取建立群組精靈。

. 選擇*存取管理* > *群組*。
. 選擇*建立群組*。




== 選擇群組類型

您可以建立本機群組或匯入聯合群組。

.步驟
. 選擇「*本機群組*」標籤來建立本機群組，或選擇「*聯合群組*」標籤來從先前配置的身分來源匯入群組。
+
如果您的StorageGRID系統啟用了單一登入 (SSO)，則屬於本機群組的使用者將無法登入租用戶管理器，但他們可以根據群組權限使用用戶端應用程式來管理租用戶的資源。

. 輸入群組的名稱。
+
** *本機群組*：輸入顯示名稱和唯一名稱。您可以稍後編輯顯示名稱。
** *聯合組*：輸入唯一名稱。對於 Active Directory，唯一名稱是與 `sAMAccountName`屬性。對於 OpenLDAP，唯一名稱是與 `uid`屬性。


. 選擇*繼續*。




== 管理群組權限

群組權限控制使用者可以在租用戶管理員和租用戶管理 API 中執行哪些任務。

.步驟
. 對於*存取模式*，請選擇以下之一：
+
** *讀寫*（預設）：使用者可以登入租用戶管理員並管理租用戶設定。
** *只讀*：使用者只能查看設定和功能。他們無法在租用戶管理員或租用戶管理 API 中進行任何變更或執行任何操作。本機只讀使用者可以更改自己的密碼。
+

NOTE: 如果使用者屬於多個群組，並且任何群組設定為唯讀，則該使用者將對所有選定的設定和功能具有唯讀存取權限。



. 如果群組使用者需要登入租用戶管理員或租用戶管理 API，請選取 *Root 存取* 複選框。
. 選擇*繼續*。




== 設定 Swift 組策略

Swift 使用者需要管理員權限才能驗證 Swift REST API 來建立容器和提取物件。

. 如果群組使用者需要使用 Swift REST API 來管理容器和對象，請選取 *Swift 管理員* 複選框。
. 如果您正在建立本機群組，請選擇*繼續*。如果您正在建立聯合群組，請選擇*建立群組*和*完成*。




== 新增使用者（僅限本地群組）

您可以儲存群組而不新增用戶，也可以選擇新增任何已存在的本機用戶。

.步驟
. 或者，為此群組選擇一個或多個本機使用者。
+
如果您尚未建立本機用戶，您可以在用戶頁面上將此群組新增至用戶。看link:../tenant/managing-local-users.html["管理本地用戶"] 。

. 選擇*建立群組*和*完成*。
+
您建立的群組將出現在群組清單中。


