---
permalink: tenant/creating-your-own-s3-access-keys.html 
sidebar: sidebar 
keywords: how to create your own S3 access key 
summary: 如果您使用 S3 租用戶並且擁有適當的權限，則可以建立自己的 S3 存取金鑰。您必須擁有存取金鑰才能存取您的儲存桶和物件。 
---
= 建立您自己的 S3 存取金鑰
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用 S3 租用戶並且擁有適當的權限，則可以建立自己的 S3 存取金鑰。您必須擁有存取金鑰才能存取您的儲存桶和物件。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您屬於具有link:tenant-management-permissions.html["管理您自己的 S3 憑證或 Root 存取權限"]。


.關於此任務
您可以建立一個或多個 S3 存取金鑰，以便為您的租用戶帳戶建立和管理儲存桶。建立新的存取金鑰後，使用新的存取金鑰 ID 和秘密存取金鑰更新應用程式。為了安全起見，請不要建立超過所需數量的金鑰，並刪除不使用的金鑰。如果您只有一個密鑰並且它即將過期，請在舊密鑰過期之前建立新密鑰，然後刪除舊密鑰。

每個密鑰可以有特定的到期時間或沒有到期時間。請遵循以下有關到期時間的準則：

* 為您的金鑰設定到期時間，以限制您在特定時間段內的存取。如果您的存取金鑰 ID 和秘密存取金鑰意外洩露，設定較短的到期時間可以幫助降低您的風險。過期的密鑰將自動刪除。
* 如果您的環境中的安全風險較低，且您不需要定期建立新金鑰，則不必為金鑰設定到期時間。如果您稍後決定建立新密鑰，請手動刪除舊密鑰。



CAUTION: 您可以使用租用戶管理員中顯示的您帳戶的存取金鑰 ID 和秘密存取金鑰存取屬於您帳戶的 S3 儲存桶和物件。因此，請像保護密碼一樣保護存取金鑰。定期輪換存取金鑰，從您的帳戶中刪除任何未使用的金鑰，並且切勿與其他使用者共用。

.步驟
. 選擇*儲存 (S3)* > *我的存取金鑰*。
+
出現「我的造訪金鑰」頁面並列出所有現有的存取金鑰。

. 選擇*建立金鑰*。
. 執行下列操作之一：
+
** 選擇「*不設定過期時間*」來建立不會過期的金鑰。  (預設)
** 選擇*設定到期時間*，並設定到期日期和時間。
+

NOTE: 到期日最長為當期起五年。到期時間可以從當前時間開始至少一分鐘。



. 選擇*建立存取金鑰*。
+
出現「下載存取金鑰」對話框，其中列出您的存取金鑰 ID 和秘密存取金鑰。

. 將存取金鑰 ID 和秘密存取金鑰複製到安全位置，或選擇 *下載 .csv* 以儲存包含存取金鑰 ID 和秘密存取金鑰的電子表格檔案。
+

CAUTION: 複製或下載此資訊之前，請勿關閉此對話方塊。對話方塊關閉後，您無法複製或下載金鑰。

. 選擇*完成*。
+
新密鑰列在「我的存取密鑰」頁面上。

. 如果您的租用戶帳戶具有 *使用網格聯合連線* 權限，則可以選擇使用租用戶管理 API 將 S3 存取金鑰從來源網格上的租用戶手動複製到目標網格上的租用戶。看link:grid-federation-clone-keys-with-api.html["使用 API 克隆 S3 存取金鑰"] 。

