---
permalink: tenant/deleting-s3-bucket.html 
sidebar: sidebar 
keywords: how to delete S3 bucket 
summary: 您可以使用租用戶管理員刪除空的 S3 儲存桶。 
---
= 刪除 S3 儲存桶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用租用戶管理員刪除一個或多個空的 S3 儲存桶。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您屬於具有link:tenant-management-permissions.html["管理所有 bucket 或 Root 存取權限"]。這些權限將覆蓋群組或儲存桶策略中的權限設定。
* 您要刪除的儲存桶是空的。如果要刪除的儲存桶不為空，link:../tenant/deleting-s3-bucket-objects.html["從儲存桶中刪除對象"] 。


.關於此任務
這些說明描述如何使用租用戶管理員刪除 S3 儲存桶。您也可以使用link:understanding-tenant-management-api.html["租戶管理 API"]或link:../s3/operations-on-buckets.html["S3 REST API"]。

如果 S3 儲存桶包含物件、非目前物件版本或刪除標記，則您無法刪除它。有關如何刪除 S3 版本控制對象的信息，請參閱link:../ilm/how-objects-are-deleted.html["如何刪除對象"]。

.步驟
. 從儀表板中選擇 *查看儲存桶*，或選擇 *儲存（S3）* > *儲存桶*。
+
出現「儲存桶」頁面並顯示所有現有的 S3 儲存桶。

. 使用*操作*選單或特定儲存桶的詳細資訊頁面。
+
[role="tabbed-block"]
====
.操作選單
--
.. 選取要刪除的每個儲存桶的複選框。
.. 選擇*操作* > *刪除儲存桶*。


--
.詳細資訊頁面
--
.. 選擇一個儲存桶名稱以顯示其詳細資訊。
.. 選擇*刪除儲存桶*。


--
====
. 當出現確認對話框時，選擇*是*。
+
StorageGRID確認每個儲存桶為空，然後刪除每個儲存桶。此操作可能需要幾分鐘。

+
如果儲存桶不為空，則會出現錯誤訊息。你必須link:../tenant/deleting-s3-bucket-objects.html["刪除儲存桶中的所有物件和所有刪除標記"]然後您才可以刪除該儲存桶。


