---
permalink: tenant/enabling-or-disabling-last-access-time-updates.html 
sidebar: sidebar 
keywords: how to enable or disable last access time updates 
summary: '當網格管理員為StorageGRID系統建立資訊生命週期管理 (ILM) 規則時，他們可以選擇指定使用物件的最後存取時間來確定是否將該物件移至不同的儲存位置。如果您正在使用 S3 租用戶，則可以透過為 S3 儲存桶中的物件啟用上次存取時間更新來利用此類規則。' 
---
= 啟用或停用上次訪問時間更新
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當網格管理員為StorageGRID系統建立資訊生命週期管理 (ILM) 規則時，他們可以選擇指定使用物件的最後存取時間來確定是否將該物件移至不同的儲存位置。如果您正在使用 S3 租用戶，則可以透過為 S3 儲存桶中的物件啟用上次存取時間更新來利用此類規則。

這些說明僅適用於包含至少一條 ILM 規則的StorageGRID系統，該規則使用 *上次存取時間* 選項作為進階篩選器或參考時間。如果您的StorageGRID系統不包含這樣的規則，您可以忽略這些說明。看link:../ilm/using-last-access-time-in-ilm-rules.html["在 ILM 規則中使用上次存取時間"]了解詳情。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您屬於具有link:tenant-management-permissions.html["管理所有 bucket 或 Root 存取權限"]。這些權限將覆蓋群組或儲存桶策略中的權限設定。


.關於此任務
*上次造訪時間*是 ILM 規則的*參考時間*放置指令可用的選項之一。將規則的參考時間設定為上次存取時間，可讓網格管理員根據上次擷取（讀取或檢視）物件的時間來指定將物件放置在特定的儲存位置。

例如，為了確保最近查看的物件保留在更快的儲存中，網格管理員可以建立 ILM 規則，指定以下內容：

* 過去一個月檢索到的物件應保留在本機儲存節點上。
* 過去一個月內未被取回的物品應移至異地。


預設情況下，上次訪問時間的更新是禁用的。如果您的StorageGRID系統包含使用 *上次存取時間* 選項的 ILM 規則，並且您希望此選項應用於此儲存桶中的對象，則必須啟用對該規則中指定的 S3 儲存桶的上次存取時間更新。


CAUTION: 檢索物件時更新最後存取時間可能會降低StorageGRID效能，尤其是對於小物件。

上次存取時間更新會對效能產生影響，因為StorageGRID每次擷取物件時都必須執行以下額外步驟：

* 使用新的時間戳更新對象
* 將物件新增至 ILM 佇列，以便可以根據目前 ILM 規則和策略重新評估它們


此表總結了當上次存取時間已停用或啟用時應用於儲存桶中所有物件的行為。

[cols="1a,1a,1a,1a,1a"]
|===


.2+| 請求類型 2+| 上次訪問時間禁用時的行為（預設） 2+| 啟用上次造訪時間時的行為 


| 上次造訪時間已更新？ | 物件已新增至 ILM 評估佇列？ | 上次造訪時間已更新？ | 物件已新增至 ILM 評估佇列？ 


 a| 
請求檢索物件、其存取控制清單或其元數據
 a| 
不
 a| 
不
 a| 
是的
 a| 
是的



 a| 
請求更新物件的元數據
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的



 a| 
請求列出物件或物件版本
 a| 
不
 a| 
不
 a| 
不
 a| 
不



 a| 
請求將物件從一個儲存桶複製到另一個儲存桶
 a| 
* 不，對於來源副本
* 是的，對於目標副本

 a| 
* 不，對於來源副本
* 是的，對於目標副本

 a| 
* 是的，對於來源副本
* 是的，對於目標副本

 a| 
* 是的，對於來源副本
* 是的，對於目標副本




 a| 
請求完成分段上傳
 a| 
是的，對於組裝好的物體
 a| 
是的，對於組裝好的物體
 a| 
是的，對於組裝好的物體
 a| 
是的，對於組裝好的物體

|===
.步驟
. 從儀表板中選擇 *查看儲存桶*，或選擇 *儲存（S3）* > *儲存桶*。
. 從表格中選擇儲存桶名稱。
+
出現儲存桶詳細資訊頁面。

. 從*Bucket options*選項卡中，選擇*Last access time updates*折疊面板。
. 啟用或停用上次造訪時間更新。
. 選擇“儲存變更”。

