---
permalink: tenant/index.html 
sidebar: sidebar 
keywords: use tenant account 
summary: '租用戶帳戶可讓您使用簡單儲存服務 (S3) REST API 或 Swift REST API 在StorageGRID系統中儲存和擷取物件。' 
---
= 使用租用戶帳戶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
租用戶帳戶可讓您使用簡單儲存服務 (S3) REST API 或 Swift REST API 在StorageGRID系統中儲存和擷取物件。



== 什麼是租戶帳戶？

每個租用戶帳戶都有自己的聯合或本機群組、使用者、S3 儲存桶或 Swift 容器和物件。

租用戶帳戶可用於依不同實體隔離儲存的物件。例如，多個租用戶帳戶可用於下列任一用例：

* *企業用例：*如果在企業內部使用StorageGRID系統，則網格的物件儲存可能會由組織內的不同部門隔離。例如，可能有行銷部門、客戶支援部門、人力資源部門等的租戶帳戶。
+

NOTE: 如果您使用 S3 用戶端協議，您也可以使用 S3 儲存桶和儲存桶策略在企業各部門之間隔離物件。您不需要建立單獨的租用戶帳戶。請參閱實施說明link:../s3/bucket-and-group-access-policies.html["S3 儲存桶和儲存桶策略"]了解更多。

* *服務提供者用例：*如果服務提供者正在使用StorageGRID系統，則網格的物件儲存可能會由租用儲存的不同實體隔離。例如，可能有公司 A、公司 B、公司 C 等的租戶帳戶。




== 如何建立租用戶帳戶

租戶帳戶由link:../admin/managing-tenants.html["使用網格管理器的StorageGRID網格管理員"]。建立租用戶帳戶時，網格管理員指定以下內容：

* 基本資訊包括租用戶名稱、用戶端類型（S3）和可選儲存配額。
* 租用戶帳戶的權限，例如租用戶帳戶是否可以使用 S3 平台服務、設定自己的身分來源、使用 S3 Select 或使用網格聯合連線。
* 租用戶的初始根存取權限，取決於StorageGRID系統是否使用本機群組和使用者、身分聯合或單一登入 (SSO)。


此外，如果 S3 租用戶帳戶需要遵守法規要求，網格管理員可以為StorageGRID系統啟用 S3 物件鎖定設定。啟用 S3 物件鎖定後，所有 S3 租用戶帳戶都可以建立和管理相容的儲存桶。



=== 配置 S3 租戶

經過link:../admin/creating-tenant-account.html["S3 租用戶帳戶已建立"]，您可以存取租用戶管理員來執行下列任務：

* 設定身份聯合（除非身份來源與網格共享）
* 管理群組和用戶
* 使用網格聯合進行帳戶克隆和跨網格複製
* 管理 S3 存取密鑰
* 建立和管理 S3 儲存桶
* 使用 S3 平台服務
* 使用 S3 Select
* 監控儲存使用情況



TIP: 雖然您可以使用租用戶管理器建立和管理 S3 儲存桶，但您必須使用link:../s3/index.html["S3 用戶端"]或者link:use-s3-console.html["S3 控制台"]攝取和管理物件。
