---
permalink: tenant/specifying-urn-for-platform-services-endpoint.html 
sidebar: sidebar 
keywords: how to specify platform services urn 
summary: '建立平台服務端點時，必須指定唯一資源名稱 (URN)。當您為平台服務建立配置 XML 時，您將使用 URN 來引用端點。每個端點的 URN 必須是唯一的。' 
---
= 指定平台服務端點的 URN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
建立平台服務端點時，必須指定唯一資源名稱 (URN)。當您為平台服務建立配置 XML 時，您將使用 URN 來引用端點。每個端點的 URN 必須是唯一的。

StorageGRID會在您建立平台服務端點時進行驗證。在建立平台服務端點之前，請確認端點中指定的資源存在並且可以存取。



== URN 元素

平台服務端點的 URN 必須以 `arn:aws`或者 `urn:mysite`，如下圖所示：

* 如果服務託管在 Amazon Web Services (AWS) 上，請使用 `arn:aws`
* 如果服務託管在 Google Cloud Platform (GCP) 上，請使用 `arn:aws`
* 如果服務在本機上託管，請使用 `urn:mysite`


例如，如果您要為StorageGRID上託管的 CloudMirror 端點指定 URN，則 URN 可能以 `urn:sgws`。

URN 的下一個元素指定平台服務的類型，如下所示：

[cols="2a,1a"]
|===
| 服務 | 類型 


 a| 
CloudMirror 複製
 a| 
`s3`



 a| 
通知
 a| 
`sns`或者 `kafka`



 a| 
搜尋集成
 a| 
`es`

|===
例如，要繼續指定StorageGRID上託管的 CloudMirror 端點的 URN，您可以新增 `s3`要得到 `urn:sgws:s3`。

URN 的最後一個元素標識目標 URI 處的特定目標資源。

[cols="1a,2a"]
|===
| 服務 | 特定資源 


 a| 
CloudMirror 複製
 a| 
`bucket-name`



 a| 
通知
 a| 
`sns-topic-name`或者 `kafka-topic-name`



 a| 
搜尋集成
 a| 
`domain-name/index-name/type-name`

*注意：*如果 Elasticsearch 叢集未配置為自動建立索引，則必須在建立端點之前手動建立索引。

|===


== AWS 和 GCP 上託管的服務的 URN

對於 AWS 和 GCP 實體，完整的 URN 是有效的 AWS ARN。例如：

* CloudMirror 複製：
+
[listing]
----
arn:aws:s3:::bucket-name
----
* 通知：
+
[listing]
----
arn:aws:sns:region:account-id:topic-name
----
* 搜尋整合：
+
[listing]
----
arn:aws:es:region:account-id:domain/domain-name/index-name/type-name
----
+

NOTE: 對於 AWS 搜尋整合終端節點， `domain-name`必須包含文字字串 `domain/`，如下圖所示。





== 本地代管服務的 URN

當使用本機託管服務而不是雲端服務時，您可以以任何方式指定 URN，以建立有效且唯一的 URN，只要 URN 在第三個和最後一個位置包含所需的元素。您可以將可選指示的元素留空，也可以以任何有助於識別資源並使 URN 唯一的方式來指定它們。例如：

* CloudMirror 複製：
+
[listing]
----
urn:mysite:s3:optional:optional:bucket-name
----
+
對於託管在StorageGRID上的 CloudMirror 端點，您可以指定以 開頭有效的 URN `urn:sgws` ：

+
[listing]
----
urn:sgws:s3:optional:optional:bucket-name
----
* 通知：
+
指定 Amazon Simple Notification Service 終端節點：

+
[listing]
----
urn:mysite:sns:optional:optional:sns-topic-name
----
+
指定 Kafka 端點：

+
[listing]
----
urn:mysite:kafka:optional:optional:kafka-topic-name
----
* 搜尋整合：
+
[listing]
----
urn:mysite:es:optional:optional:domain-name/index-name/type-name
----
+

NOTE: 對於本地託管的搜尋整合端點， `domain-name`只要端點的 URN 是唯一的，元素可以是任何字串。


