---
permalink: tenant/tenant-management-permissions.html 
sidebar: sidebar 
keywords: tenant management permissions 
summary: 在建立租用戶群組之前，請考慮要指派給該群組哪些權限。租用戶管理權限決定使用者可以使用租用戶管理員或租用戶管理 API 執行哪些任務。一個使用者可以屬於一個或多個群組。如果使用者屬於多個群組，則權限是累積的。 
---
= 租用戶管理權限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在建立租用戶群組之前，請考慮要指派給該群組哪些權限。租用戶管理權限決定使用者可以使用租用戶管理員或租用戶管理 API 執行哪些任務。一個使用者可以屬於一個或多個群組。如果使用者屬於多個群組，則權限是累積的。

若要登入租用戶管理員或使用租用戶管理 API，使用者必須屬於具有至少一個權限的群組。所有可以登入的使用者都可以執行以下任務：

* 查看儀表板
* 更改自己的密碼（針對本機用戶）


對於所有權限，群組的存取模式設定決定使用者是否可以變更設定和執行操作，或者是否只能查看相關設定和功能。


NOTE: 如果使用者屬於多個群組，並且任何群組設定為唯讀，則該使用者將對所有選定的設定和功能具有唯讀存取權限。

您可以為群組指派以下權限。請注意，S3 租用戶和 Swift 租用戶具有不同的群組權限。

[cols="1a,3a,3a"]
|===
| 允許 | 描述 | 細節 


 a| 
Root 存取權限
 a| 
提供對租用戶管理器和租用戶管理 API 的完全存取權。
 a| 
Swift 使用者必須具有 Root 存取權限才能登入租用戶帳戶。



 a| 
行政人員
 a| 
僅限 Swift 租戶。提供此租用戶帳戶的 Swift 容器和物件的完全存取權限
 a| 
Swift 使用者必須具有 Swift 管理員權限才能使用 Swift REST API 執行任何操作。



 a| 
管理您自己的 S3 憑證
 a| 
允許使用者建立和刪除自己的 S3 存取密鑰。
 a| 
沒有此權限的使用者看不到 *儲存 (S3)* > *我的 S3 存取金鑰* 選單選項。



 a| 
查看所有儲存桶
 a| 
*S3 租用戶*：允許使用者查看所有儲存桶和儲存桶配置。

*Swift 租用戶*：允許 Swift 使用者使用租用戶管理 API 查看所有容器和容器配置。
 a| 
沒有查看所有儲存桶或管理所有儲存桶權限的使用者看不到*儲存桶*選單選項。

此權限已被「管理所有儲存桶」權限取代。它不會影響 S3 用戶端或 S3 控制台使用的 S3 儲存桶或群組原則。

您只能從租用戶管理 API 將此權限指派給 Swift 群組。您不能使用租用戶管理員將此權限指派給 Swift 群組。



 a| 
管理所有儲存桶
 a| 
*S3 租用戶*：允許使用者使用租用戶管理器和租用戶管理 API 建立和刪除 S3 儲存桶，並管理租用戶帳戶中所有 S3 儲存桶的設置，而無需考慮 S3 儲存桶或群組原則。

*Swift 租用戶*：允許 Swift 使用者使用租用戶管理 API 控制 Swift 容器的一致性。
 a| 
沒有查看所有儲存桶或管理所有儲存桶權限的使用者看不到*儲存桶*選單選項。

此權限取代了查看所有儲存桶的權限。它不會影響 S3 用戶端或 S3 控制台使用的 S3 儲存桶或群組原則。

您只能從租用戶管理 API 將此權限指派給 Swift 群組。您不能使用租用戶管理員將此權限指派給 Swift 群組。



 a| 
管理端點
 a| 
允許使用者使用租用戶管理器或租用戶管理 API 建立或編輯平台服務端點，這些端點用作StorageGRID平台服務的目標。
 a| 
沒有此權限的使用者看不到*平台服務端點*選單選項。



 a| 
使用 S3 控制台選項卡
 a| 
與查看所有儲存桶或管理所有儲存桶權限結合使用時，可讓使用者從儲存桶詳細資料頁面上的 S3 控制台標籤檢視和管理物件。
 a| 

|===