---
permalink: tenant/understanding-search-integration-service.html 
sidebar: sidebar 
keywords: how to understand search integration service 
summary: 如果您想要對物件元資料使用外部搜尋和資料分析服務，則可以為 S3 儲存桶啟用搜尋整合。 
---
= 了解搜尋整合服務
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想要對物件元資料使用外部搜尋和資料分析服務，則可以為 S3 儲存桶啟用搜尋整合。

搜尋整合服務是一種自訂StorageGRID服務，每當建立或刪除對象，或更新其元資料或標籤時，它都會自動且非同步地將 S3 對像元資料傳送到目標端點。然後，您可以使用目標服務提供的複雜搜尋、資料分析、視覺化或機器學習工具來搜尋、分析和洞察您的物件資料。

例如，您可以設定儲存桶以將 S3 物件元資料傳送到遠端 Elasticsearch 服務。然後，您可以使用 Elasticsearch 跨儲存桶執行搜索，並對物件元資料中存在的模式執行複雜的分析。

儘管可以在啟用了 S3 物件鎖定的儲存桶上配置 Elasticsearch 集成，但物件的 S3 物件鎖定元資料（包括保留截止日期和合法保留狀態）將不會包含在傳送至 Elasticsearch 的元資料中。


NOTE: 由於搜尋整合服務會導致物件元資料被傳送到目的地，因此其配置 XML 被稱為「_metadata_通知配置 XML」。此配置 XML 與用於啟用_事件_通知的「通知配置 XML」不同。



== 搜尋整合和 S3 儲存桶

您可以為任何版本化或未版本化的儲存桶啟用搜尋整合服務。透過將元資料通知配置 XML 與指定要操作的物件以及物件元資料的目的地的儲存桶關聯起來，可以配置搜尋整合。

元資料通知以 JSON 文件的形式生成，該文件以儲存桶名稱、物件名稱和版本 ID（如果有）命名。每個元資料通知除了包含物件的所有標籤和使用者元資料之外，還包含該物件的一組標準系統元資料。


NOTE: 對於標籤和使用者元數據， StorageGRID將日期和數字作為字串或 S3 事件通知傳遞給 Elasticsearch。若要設定 Elasticsearch 將這些字串解釋為日期或數字，請按照 Elasticsearch 的動態欄位對應和對應日期格式的說明進行操作。在配置搜尋整合服務之前，您必須在索引上啟用動態欄位對應。文檔被索引後，您無法在索引中編輯文檔的欄位類型。



== 搜尋通知

每當出現以下情況時，就會產生元資料通知並排隊等待傳送：

* 已建立一個物件。
* 物件被刪除，包括由於網格的 ILM 策略操作而刪除物件的情況。
* 新增、更新或刪除物件元資料或標籤。更新時總是會發送完整的元資料和標籤集——而不僅僅是更改的值。


將元資料通知配置 XML 新增至儲存桶後，系統會為您建立的任何新物件以及透過更新其資料、使用者元資料或標籤而修改的任何物件傳送通知。但是，不會針對儲存桶中已經存在的任何物件發送通知。為了確保儲存桶中所有物件的物件元資料都傳送到目標，您應該執行下列其中一項操作：

* 在建立儲存桶之後和新增任何物件之前立即配置搜尋整合服務。
* 對儲存桶中已有的所有物件執行操作，該操作將觸發元資料通知訊息傳送至目標。




== 搜尋集成服務和 Elasticsearch

StorageGRID搜尋整合服務支援 Elasticsearch 叢集作為目標。與其他平台服務一樣，目的地在端點中指定，該端點的 URN 用於服務的配置 XML。使用 https://imt.netapp.com/matrix/#welcome["NetApp互通性表工具"^]確定支援的 Elasticsearch 版本。
