---
permalink: tenant/understanding-cloudmirror-replication-service.html 
sidebar: sidebar 
keywords: cloudmirror replication 
summary: 如果您希望StorageGRID將新增至儲存桶的指定物件複製到一個或多個目標儲存桶，則可以為 S3 儲存桶啟用 CloudMirror 複製。 
---
= 了解 CloudMirror 複製服務
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您希望StorageGRID將新增至儲存桶的指定物件複製到一個或多個外部目標儲存桶，則可以為 S3 儲存桶啟用 CloudMirror 複製。

例如，您可以使用 CloudMirror 複製將特定客戶記錄鏡像到 Amazon S3，然後利用 AWS 服務對您的資料執行分析。


NOTE: 如果來源儲存桶啟用了 S3 物件鎖，則不支援 CloudMirror 複製。



== CloudMirror 和 ILM

CloudMirror 複製獨立於網格的活動 ILM 策略運作。 CloudMirror 服務會在物件儲存到來源儲存桶時進行複製，並儘快將其傳送到目標儲存桶。當物件攝取成功時，就會觸發複製物件的傳遞。



== CloudMirror 和跨網格複製

CloudMirror 複製與跨網格複製功能有重要的相似之處和差異。請參閱link:../admin/grid-federation-compare-cgr-to-cloudmirror.html["比較跨網格複製和 CloudMirror 複製"] 。



== CloudMirror 和 S3 儲存桶

CloudMirror 複製通常配置為使用外部 S3 儲存桶作為目標。但是，您也可以設定複製以使用另一個StorageGRID部署或任何與 S3 相容的服務。

現有儲存桶:: 當您為現有儲存桶啟用 CloudMirror 複製時，僅複製新增至該儲存桶的新物件。儲存桶中任何現有的物件都不會被複製。若要強制複製現有對象，您可以透過執行物件複製來更新現有物件的元資料。
+
--

NOTE: 如果您使用 CloudMirror 複製將物件複製到 Amazon S3 目標，請注意 Amazon S3 將每個 PUT 請求標頭內的使用者定義元資料的大小限制為 2 KB。如果某個物件的使用者定義元資料大於 2 KB，則不會複製該物件。

--
多個目標儲存桶:: 若要將單一儲存桶中的物件複製到多個目標儲存桶，請在複製配置 XML 中為每個規則指定目標。您不能同時將一個物件複製到多個儲存桶。
版本控製或非版本控制的儲存桶:: 您可以在版本化或非版本化儲存桶上設定 CloudMirror 複製。目標儲存桶可以是版本化的，也可以是非版本化的。您可以使用版本化儲存桶和非版本化儲存桶的任意組合。例如，您可以指定一個受版本控制的儲存桶作為不受版本控制的來源儲存桶的目標，反之亦然。您也可以在未版本控制的儲存桶之間進行複製。




== 刪除、複製循環和事件

刪除行為:: 與Amazon S3服務的刪除行為相同，跨區域複製（CRR）。刪除來源儲存桶中的物件並不會刪除目標儲存桶中的複製物件。如果來源儲存桶和目標儲存桶都已版本化，則會複製刪除標記。如果目標儲存桶未進行版本控制，則刪除來源儲存體桶中的物件不會將刪除標記複製到目標儲存桶或刪除目標物件。
防止複製循環:: 當物件被複製到目標儲存桶時， StorageGRID會將它們標記為「副本」。目標StorageGRID桶不會再次複製標記為副本的對象，從而保護您免受意外複製循環的影響。此副本標記是StorageGRID內部的，並且不會阻止您在使用 Amazon S3 儲存桶作為目標時利用 AWS CRR。
+
--

NOTE: 用於標記副本的自訂標頭是 `x-ntap-sg-replica`。此標記可防止鏡像層疊。  StorageGRID確實支援兩個網格之間的雙向 CloudMirror。

--
目標儲存桶中的事件:: 無法保證目標儲存桶中事件的唯一性和順序。為了確保傳送成功，可能會將來源物件的多個相同副本傳送到目標。在極少數情況下，當從兩個或多個不同的StorageGRID站點同時更新同一個物件時，目標儲存桶上的操作順序可能與來源儲存桶上的事件順序不符。

