---
permalink: tenant/using-s3-object-lock.html 
sidebar: sidebar 
keywords: how to use s3 object lock 
summary: 如果儲存桶和物件必須符合保留的監管要求，則可以使用 S3 物件鎖。 
---
= 使用 S3 對象鎖保留對象
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果儲存桶和物件必須符合保留的監管要求，則可以使用 S3 物件鎖。


NOTE: 您的網格管理員必須授予您使用 S3 物件鎖定的特定功能的權限。



== 什麼是 S3 物件鎖？

StorageGRID S3 物件鎖定功能是一種物件保護解決方案，相當於 Amazon Simple Storage Service (Amazon S3) 中的 S3 物件鎖定。

當為StorageGRID系統啟用全域 S3 物件鎖定設定時，S3 租用戶帳戶可以建立啟用或未啟用 S3 物件鎖定的儲存桶。如果儲存桶啟用了 S3 物件鎖，則需要儲存桶版本控制，並且會自動啟用。

*沒有 S3 物件鎖的儲存桶*只能包含未指定保留設定的物件。任何攝取的物件都不會有保留設定。

*具有 S3 物件鎖定的儲存桶*可以包含由 S3 用戶端應用程式指定的具有或不具有保留設定的物件。一些攝取的物件將具有保留設定。

*配置了 S3 物件鎖定和預設保留的儲存桶*可以擁有指定了保留設定的上傳物件和不帶保留設定的新物件。新物件使用預設設置，因為尚未在物件層級配置保留設定。

實際上，當配置預設保留時，所有新攝取的物件都有保留設定。沒有物件保留設定的現有物件不受影響。



=== 保留模式

StorageGRID S3 物件鎖定功能支援兩種保留模式，以對物件套用不同層級的保護。這些模式相當於 Amazon S3 保留模式。

* 在合規模式下：
+
** 在達到保留截止日期之前，無法刪除該物件。
** 物件的保留截止日期可以增加，但不能減少。
** 在達到該日期之前，不能刪除物件的保留截止日期。


* 在治理模式下：
+
** 具有特殊權限的使用者可以在請求中使用繞過標頭來修改某些保留設定。
** 這些用戶可以在達到保留截止日期之前刪除物件版本。
** 這些使用者可以增加、減少或刪除物件的保留期限。






=== 物件版本的保留設定

如果在建立儲存桶時啟用了 S3 物件鎖定，則使用者可以使用 S3 用戶端應用程式選擇性地為新增至儲存桶的每個物件指定以下保留設定：

* *保留模式*：合規或治理。
* *保留至日期*：如果對象版本的保留至日期在未來，則可以檢索該對象，但不能刪除它。
* *合法保留*：對物件版本套用合法保留會立即鎖定該物件。例如，您可能需要對與調查或法律糾紛相關的對象實施法律保留。合法保留沒有到期日，但會一直有效，直到明確取消。合法保留與保留截止日期無關。
+

NOTE: 如果某個物件處於合法保留之下，則無論其保留模式為何，任何人都無法刪除該物件。

+
有關對象設定的詳細信息，請參閱link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 設定 S3 物件鎖"]。





=== 儲存桶的預設保留設定

如果在建立儲存桶時啟用了 S3 物件鎖定，使用者可以選擇為儲存桶指定以下預設設定：

* *預設保留模式*：合規或治理。
* *預設保留期*：新增至此儲存桶的新物件版本應保留多長時間（從新增之日起）。


預設儲存桶設定僅適用於沒有自己的保留設定的新物件。新增或變更這些預設設定時，現有的儲存桶物件不會受到影響。

看link:../tenant/creating-s3-bucket.html["建立 S3 儲存桶"]和link:../tenant/update-default-retention-settings.html["更新 S3 物件鎖定預設保留"]。



== S3 物件鎖定任務

以下針對網格管理員和租用戶用戶的清單包含使用 S3 物件鎖定功能的進階任務。

網格管理員::
+
--
* 為整個StorageGRID系統啟用全域 S3 物件鎖定設定。
* 確保資訊生命週期管理 (ILM) 政策符合規定；也就是說，它們滿足link:../ilm/managing-objects-with-s3-object-lock.html["啟用 S3 物件鎖的儲存桶的要求"]。
* 根據需要，允許租戶使用合規性作為保留模式。否則，只允許治理模式。
* 根據需要，為租戶設定最長保留期。


--
租戶用戶::
+
--
* 查看具有 S3 物件鎖的儲存桶和物件的注意事項。
* 根據需要聯絡網格管理員啟用全域S3物件鎖定設定並設定權限。
* 建立啟用 S3 物件鎖的儲存桶。
* 或者，配置儲存桶的預設保留設定：
+
** 預設保留模式：治理或合規（如果電網管理員允許）。
** 預設保留期：必須小於或等於網格管理員設定的最大保留期。


* 使用 S3 用戶端應用程式新增物件並選擇性地設定特定於物件的保留：
+
** 保留模式。如果電網管理員允許，則進行治理或合規。
** 保留截止日期：必須小於或等於網格管理員設定的最長保留期限。




--




== 啟用 S3 物件鎖定的儲存桶的要求

* 如果為StorageGRID系統啟用了全域 S3 物件鎖定設置，則您可以使用租用戶管理器、租用戶管理 API 或 S3 REST API 建立啟用了 S3 物件鎖定的儲存桶。
* 如果您打算使用 S3 物件鎖，則必須在建立儲存桶時啟用 S3 物件鎖。您無法為現有儲存桶啟用 S3 物件鎖定。
* 當為儲存桶啟用 S3 物件鎖定時， StorageGRID會自動為該儲存桶啟用版本控制。您無法停用 S3 物件鎖定或暫停儲存桶的版本控制。
* 或者，您可以使用租用戶管理器、租用戶管理 API 或 S3 REST API 為每個儲存桶指定預設保留模式和保留期限。儲存桶的預設保留設定僅適用於新增至儲存體桶且沒有自己的保留設定的新物件。您可以透過在上傳每個物件版本時為其指定保留模式和保留截止日期來覆寫這些預設值。
* 啟用 S3 物件鎖的儲存桶支援儲存桶生命週期配置。
* 啟用了 S3 物件鎖的儲存桶不支援 CloudMirror 複製。




== 啟用 S3 物件鎖的儲存桶中的物件要求

* 為了保護物件版本，您可以為儲存桶指定預設保留設置，也可以為每個物件版本指定保留設定。可以使用 S3 用戶端應用程式或 S3 REST API 指定物件級保留設定。
* 保留設定適用於單一物件版本。物件版本可以同時具有保留截止日期和合法保留設置，或者只具有其中之一，或者兩者都不具有。為物件指定保留期限或合法保留設定僅保護請求中指定的版本。您可以建立該物件的新版本，同時該物件的先前版本仍保持鎖定狀態。




== 啟用 S3 物件鎖的儲存桶中物件的生命週期

啟用 S3 物件鎖定後，儲存在儲存桶中的每個物件都會經歷以下階段：

. *物件攝取*
+
當物件版本新增至啟用了 S3 物件鎖定的儲存桶時，將套用下列保留設定：

+
** 如果為物件指定了保留設置，則套用物件層級的設定。任何預設儲存桶設定都將被忽略。
** 如果沒有為物件指定保留設置，則套用預設儲存桶設定（如果存在）。
** 如果沒有為物件或儲存桶指定保留設置，則該物件不受 S3 物件鎖定保護。


+
如果套用了保留設置，則物件和任何 S3 使用者定義的元資料都受到保護。

. *物件保留和刪除*
+
StorageGRID會儲存每個受保護物件的多個副本，並保留指定的期限。物件副本的確切數量和類型以及儲存位置由活動 ILM 策略中的相容規則決定。受保護物件是否可以在達到保留期限之前被刪除取決於其保留模式。

+
** 如果某個物件處於合法保留之下，則無論其保留模式為何，任何人都無法刪除該物件。






== 我還能管理舊版合規儲存桶嗎？

S3 物件鎖定功能取代了先前StorageGRID版本中提供的合規性功能。如果您使用先前版本的StorageGRID建立了相容儲存桶，則可以繼續管理這些儲存桶的設定；但是，您無法再建立新的相容儲存桶。有關說明，請參閱https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp知識庫：如何在StorageGRID 11.5 中管理舊版相容儲存桶"^]。
