---
permalink: rhel/configuring-host-storage.html 
sidebar: sidebar 
keywords: how to configure host storage 
summary: 您必須為每個主機指派區塊儲存磁碟區。 
---
= 配置主機儲存
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須為每個主機指派區塊儲存磁碟區。

.開始之前
您已閱讀了以下主題，它們提供了完成此任務所需的資訊：

* link:storage-and-performance-requirements.html["儲存和效能要求"]
* link:node-container-migration-requirements.html["節點容器遷移要求"]


.關於此任務
將區塊儲存磁碟區 (LUN) 指派給主機時，請使用「儲存需求」中的表格決定以下內容：

* 每個主機所需的磁碟區數（基於將在該主機上部署的節點數量和類型）
* 每個磁碟區的儲存類別（即係統資料或物件資料）
* 每卷大小


在主機上部署StorageGRID節點時，您將使用此資訊以及 Linux 指派給每個實體磁碟區的持久名稱。


NOTE: 您不需要對任何這些磁碟區進行分割、格式化或掛載；您只需要確保它們對主機可見。


NOTE: 僅元資料儲存節點只需要一個物件資料 LUN。

避免使用「原始」特殊設備文件(`/dev/sdb`（例如）在編寫卷名清單時。這些檔案可能會在主機重新啟動後發生變化，這會影響系統的正常運作。如果您正在使用 iSCSI LUN 和裝置對應器多路徑，請考慮在 `/dev/mapper`目錄，特別是當您的 SAN 拓撲包括到共用儲存的冗餘網路路徑時。或者，您可以使用系統建立的軟鏈接 `/dev/disk/by-path/`用於您的持久設備名稱。

例如：

[listing]
----
ls -l
$ ls -l /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:00:07.1-ata-2 -> ../../sr0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:1:0 -> ../../sdb
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:2:0 -> ../../sdc
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:3:0 -> ../../sdd
----
每次安裝的結果都會有所不同。

為每個區塊儲存磁碟區指派友善名稱，以簡化初始StorageGRID安裝和未來的維護程序。如果您使用裝置映射器多路徑驅動程式對共用儲存磁碟區進行冗餘訪問，則可以使用 `alias`你的領域 `/etc/multipath.conf`文件。

例如：

[listing]
----
multipaths {
     multipath {
          wwid 3600a09800059d6df00005df2573c2c30
          alias docker-storage-volume-hostA
     }
     multipath {
          wwid 3600a09800059d6df00005df3573c2c30
          alias sgws-adm1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df4573c2c30
          alias sgws-adm1-audit-logs
     }
     multipath {
          wwid 3600a09800059d6df00005df5573c2c30
          alias sgws-adm1-tables
     }
     multipath {
          wwid 3600a09800059d6df00005df6573c2c30
          alias sgws-gw1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-rangedb-0
     }
     …
----
以這種方式使用別名字段會導致別名在 `/dev/mapper`主機上的目錄，可讓您在設定或維護作業需要指定區塊儲存磁碟區時指定一個友善且易於驗證的名稱。


NOTE: 如果您要設定共用儲存體以支援StorageGRID節點遷移並使用裝置映射器多路徑，則可以建立並安裝通用 `/etc/multipath.conf`在所有同地主機上。只需確保在每個主機上使用不同的容器引擎儲存磁碟區。使用別名並在每個容器引擎儲存磁碟區 LUN 的別名中包含目標主機名稱將使其易於記憶，因此建議這樣做。


NOTE: 不再支援將 Docker 作為純軟體部署的容器引擎。Docker 將在未來的版本中被另一個容器引擎取代。

.相關資訊
link:configuring-docker-storage-volume.html["配置容器引擎儲存卷"]
