---
permalink: admin/admin-group-permissions.html 
sidebar: sidebar 
keywords: admin group permissions 
summary: 建立管理員使用者群組時，您可以選擇一個或多個權限來控制對網格管理器特定功能的存取。然後，您可以將每個使用者指派到一個或多個管理群組，以確定該使用者可以執行哪些任務。 
---
= 管理員群組權限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
建立管理員使用者群組時，您可以選擇一個或多個權限來控制對網格管理器特定功能的存取。然後，您可以將每個使用者指派到一個或多個管理群組，以確定該使用者可以執行哪些任務。

您必須為每個群組指派至少一個權限；否則，屬於該群組的使用者將無法登入網格管理器或網格管理 API。

預設情況下，屬於具有至少一個權限的群組的任何使用者都可以執行以下任務：

* Sign in入網格管理器
* 查看儀表板
* 查看節點頁面
* 查看當前和已解決的警報
* 更改自己的密碼（僅限本地用戶）
* 查看配置和維護頁面上提供的某些信息




== 權限與存取模式的交互

對於所有權限，群組的*存取模式*設定決定使用者是否可以變更設定和執行操作，或者是否只能查看相關設定和功能。如果使用者屬於多個群組，並且任何群組設定為*只讀*，則該使用者將對所有選定的設定和功能具有唯讀存取權限。

以下部分描述了建立或編輯管理員群組時可以指派的權限。任何未明確提及的功能都需要*Root 存取*權限。



== Root 存取權限

此權限提供對所有網格管理功能的存取。



== 更改租用戶 root 密碼

此權限提供對租用戶頁面上的*更改 root 密碼*選項的存取權限，讓您可以控制誰可以更改租用戶本地 root 使用者的密碼。啟用 S3 金鑰導入功能時，此權限也用於遷移 S3 金鑰。沒有此權限的使用者無法看到*更改 root 密碼*選項。


NOTE: 若要授予包含「變更根密碼」選項的「租用戶」頁面的存取權限，也需指派「租用戶帳號」權限。



== 電網拓撲頁面配置

此權限提供對 *SUPPORT* > *Tools* > *Grid topology* 頁面上的配置標籤的存取權限。


NOTE: 網格拓撲頁面已被棄用，並將在未來版本中刪除。



== 工業光魔

此權限提供對以下 *ILM* 選單選項的存取：

* 規則
* 政策
* 策略標籤
* 儲存池
* 儲存等級
* 區域
* 對像元資料查找



NOTE: 使用者必須具備*其他電網配置*和*電網拓撲頁面配置*權限才能管理儲存等級。



== 維護

使用者必須具有維護權限才能使用這些選項：

* *配置* > *存取控制*：
+
** 電網密碼


* *配置* > *網路*：
+
** S3 端點域名


* *維護* > *任務*：
+
** 退休
** 擴張
** 對象存在性檢查
** 恢復


* *維護* > *系統*：
+
** 恢復包
** 軟體更新


* *支援* > *工具*：
+
** 紀錄




沒有維護權限的使用者可以查看但不能編輯以下頁面：

* *維護* > *網路*：
+
** DNS 伺服器
** 網格網絡
** NTP 伺服器


* *維護* > *系統*：
+
** 執照


* *配置* > *網路*：
+
** S3 端點域名


* *配置* > *安全*：
+
** 證書


* *配置* > *監控*：
+
** 審計和系統日誌伺服器






== 管理警報

此權限提供對管理警報選項的存取。使用者必須擁有此權限才能管理靜默、警報通知和警報規則。



== 指標查詢

此權限提供以下存取權限：

* *支援* > *工具* > *指標*頁面
* 使用網格管理 API 的 *Metrics* 部分自訂 Prometheus 指標查詢
* 包含指標的網格管理器儀表闆卡




== 對像元資料查找

此權限提供對 *ILM* > *物件元資料查找* 頁面的存取權限。



== 其他電網配置

此權限提供對其他網格配置選項的存取。


TIP: 要查看這些附加選項，使用者還必須具有*網格拓撲頁面配置*權限。

* 工業光魔（ILM）：
+
** 儲存等級


* *配置* > *系統*：
* *支援* > *其他*：
+
** 鏈路成本






== 儲存設備管理員

此權限提供：

* 透過網格管理器存取儲存設備上的 E 系列SANtricity系統管理器。
* 能夠在支援這些操作的裝置的「管理磁碟機」標籤上執行故障排除和維護任務。




== 租戶帳戶

此權限提供以下功能：

* 造訪租戶頁面，您可以在其中建立、編輯和刪除租戶帳戶
* 查看現有的流量分類策略
* 查看包含租戶詳細資訊的網格管理器儀表闆卡

