---
permalink: admin/benefits-of-active-idle-and-concurrent-http-connections.html 
sidebar: sidebar 
keywords: active http connection benefits, idle http connection benefits, concurrent http connection benefits 
summary: 如何設定 HTTP 連線會影響StorageGRID系統的效能。配置會根據 HTTP 連線是處於活動狀態還是空閒狀態或您是否有並發的多個連線而有所不同。 
---
= 活動、空閒和並發 HTTP 連線的優勢
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如何設定 HTTP 連線會影響StorageGRID系統的效能。配置會根據 HTTP 連線是處於活動狀態還是空閒狀態或您是否有並發的多個連線而有所不同。

您可以確定以下類型的 HTTP 連線的效能優勢：

* 空閒 HTTP 連接
* 活動的 HTTP 連接
* 並發 HTTP 連接




== 保持空閒 HTTP 連線開放的好處

即使客戶端應用程式處於空閒狀態，您也應該保持 HTTP 連線打開，以允許客戶端應用程式透過開啟的連線執行後續交易。根據系統測量和整合經驗，您應該保持空閒 HTTP 連線最多開放 10 分鐘。  StorageGRID可能會自動關閉保持開啟狀態並空閒超過 10 分鐘的 HTTP 連線。

開啟和空閒的 HTTP 連線具有以下優點：

* 減少從StorageGRID系統決定必須執行 HTTP 交易到StorageGRID系統可以執行交易的延遲
+
減少延遲是主要優勢，尤其是建立 TCP/IP 和 TLS 連線所需的時間。

* 透過使用先前執行的傳輸來啟動 TCP/IP 慢啟動演算法來提高資料傳輸速率
* 即時通知中斷客戶端應用程式和StorageGRID系統之間連接的幾類故障情況


確定保持空閒連線開啟的時間長度是與現有連線相關的慢啟動的好處與將連線理想地分配給內部系統資源之間的權衡。



== 主動 HTTP 連線的好處

對於直接連接到儲存節點，您應該將活動 HTTP 連線的持續時間限制為最多 10 分鐘，即使 HTTP 連線持續執行交易。

確定連接保持開啟的最長持續時間是連接持久性的好處和將連接理想地分配到內部系統資源之間的權衡。

對於客戶端與儲存節點的連接，限制活動的 HTTP 連接具有以下好處：

* 實現StorageGRID系統內的最佳負載平衡。
+
隨著時間的推移，由於負載平衡要求的變化，HTTP 連接可能不再是最佳的。當用戶端應用程式為每個交易建立單獨的 HTTP 連線時，系統會執行最佳的負載平衡，但這會抵消與持久連線相關的更有價值的效益。

* 允許客戶端應用程式將 HTTP 事務定向到具有可用空間的 LDR 服務。
* 允許啟動維護程序。
+
某些維護程序僅在所有正在進行的 HTTP 連線完成後才啟動。



對於與負載平衡器服務的用戶端連接，限制開啟連線的持續時間對於允許某些維護程序及時啟動很有用。如果用戶端連線的持續時間不受限制，則活動連線可能需要幾分鐘才能自動終止。



== 並發 HTTP 連線的好處

您應該保持與StorageGRID系統的多個 TCP/IP 連線處於開啟狀態以允許並行，從而提高效能。最佳並行連線數取決於多種因素。

並發 HTTP 連線具有以下優勢：

* 減少延遲
+
交易可以立即開始，而不必等待其他交易完成。

* 提高吞吐量
+
StorageGRID系統可以執行並行事務並增加總事務吞吐量。



客戶端應用程式應該建立多個 HTTP 連線。當客戶端應用程式必須執行事務時，它可以選擇並立即使用任何目前未處理交易的已建立連線。

在效能開始下降之前，每個StorageGRID系統的拓撲對於並發事務和連接都有不同的峰值吞吐量。峰值吞吐量取決於運算資源、網路資源、儲存資源和 WAN 鏈路等因素。  StorageGRID系統支援的伺服器和服務的數量以及應用程式的數量也是影響因素。

StorageGRID系統通常支援多個客戶端應用程式。在確定客戶端應用程式使用的最大並發連線數時，應牢記這一點。如果用戶端應用程式由多個軟體實體組成，每個實體都與StorageGRID系統建立連接，則應將跨實體的所有連接加起來。在以下情況下，您可能需要調整最大並發連線數：

* StorageGRID系統的拓樸影響系統可以支援的最大並發事務和連線數。
* 透過頻寬有限的網路與StorageGRID系統互動的客戶端應用程式可能必須降低並發度，以確保各個事務在合理的時間內完成。
* 當許多客戶端應用程式共用StorageGRID系統時，您可能必須降低並發度以避免超出系統的限制。




== 分離用於讀取和寫入操作的 HTTP 連線池

您可以使用單獨的 HTTP 連線池進行讀取和寫入操作，並控制每個操作使用的池量。單獨的 HTTP 連線池可讓您更好地控制事務和平衡負載。

客戶端應用程式可以建立以檢索為主（讀取）或以儲存為主（寫入）的負載。透過為讀取和寫入事務提供單獨的 HTTP 連線池，您可以調整每個池中用於讀取或寫入交易的連線數量。
