---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: 變更管理節點的 SSH 存取密碼也會更新網格中每個節點的唯一內部 SSH 金鑰集。主管理節點使用這些 SSH 金鑰透過安全、無密碼的身份驗證存取節點。 
---
= 更改管理節點的 SSH 存取密碼
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
變更管理節點的 SSH 存取密碼也會更新網格中每個節點的唯一內部 SSH 金鑰集。主管理節點使用這些 SSH 金鑰透過安全、無密碼的身份驗證存取節點。

使用 SSH 金鑰以以下身分登入節點 `admin`或虛擬機器或實體控制台連接上的 root 使用者。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 你有link:admin-group-permissions.html["維護或 Root 存取權限"]。
* 您擁有目前的設定密碼。


.關於此任務
管理節點的新存取密碼和每個節點的新內部金鑰儲存在 `Passwords.txt`恢復包中的檔案。密鑰列在該文件中的密碼列中。

節點間通訊使用的 SSH 金鑰有單獨的 SSH 存取密碼。這些不會因該過程而改變。



== 訪問嚮導

.步驟
. 選擇*設定* > *存取控制* > *電網密碼*。
. 在*更改 SSH 金鑰*下，選擇*進行更改*。




== [[download-current]]下載當前復原包

在變更 SSH 存取金鑰之前，請下載目前的復原包。如果任何節點的金鑰變更過程失敗，您可以使用此文件中的金鑰。

.步驟
. 輸入您的網格的配置密碼。
. 選擇*下載恢復包*。
. 複製復原包文件(`.zip`）到兩個安全、可靠且獨立的地點。
+

CAUTION: 復原包檔案必須是安全的，因為它包含可用於從StorageGRID系統取得資料的加密金鑰和密碼。

. 選擇*繼續*。
. 當確認對話方塊出現時，如果您準備好開始變更 SSH 存取金鑰，請選擇「是」。
+

CAUTION: 一旦該過程開始，您就無法取消。





== 變更 SSH 存取金鑰

當變更 SSH 存取金鑰程序開始時，將產生一個包含新金鑰的新復原包。然後，在每個節點上更新金鑰。

.步驟
. 等待新的恢復包生成，這可能需要幾分鐘。
. 當「下載新的復原包」按鈕啟用時，選擇「*下載新的復原包*」並儲存新的復原包文件(`.zip`）到兩個安全、可靠且獨立的位置。
. 下載完成後：
+
.. 打開 `.zip`文件。
.. 確認您可以存取內容，包括 `Passwords.txt`文件，其中包含新的 SSH 存取金鑰。
.. 複製新的復原包文件(`.zip`）到兩個安全、可靠且獨立的地點。
+

CAUTION: 不要覆蓋舊的恢復包。

+
復原包檔案必須是安全的，因為它包含可用於從StorageGRID系統取得資料的加密金鑰和密碼。



. 等待金鑰在每個節點上更新，這可能需要幾分鐘。
+
如果所有節點的金鑰都發生了更改，則會出現綠色的成功橫幅。

+
如果更新過程中出現錯誤，橫幅訊息會列出未能更改金鑰的節點數。系統將自動在密鑰更改失敗的任何節點上重試該過程。如果該過程結束時某些節點仍未更改金鑰，則會出現「重試」按鈕。

+
如果一個或多個節點的金鑰更新失敗：

+
.. 查看表中列出的錯誤訊息。
.. 解決問題。
.. 選擇*重試*。
+
重試只會變更先前金鑰變更嘗試期間失敗的節點上的 SSH 存取金鑰。



. 在所有節點的 SSH 存取金鑰變更後，刪除<<download-current,您下載的第一個復原包>>。
. 或者，選擇 *維護* > *系統* > *恢復包* 來下載新恢復包的額外副本。

