---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: 網格中的每個節點都有一個唯一的節點控制台密碼，您需要該密碼才能登入該節點。請依照下列步驟變更網格中每個節點的節點控制台密碼。密碼儲存在恢復包中。 
---
= 更改節點控制台密碼
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
網格中的每個節點都有一個唯一的節點控制台密碼，您需要該密碼才能登入該節點。使用這些步驟來變更網格中每個節點的每個唯一節點控制台密碼。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 你有link:admin-group-permissions.html["維護或 Root 存取權限"]。
* 您擁有目前的設定密碼。


.關於此任務
使用節點控制台密碼透過 SSH 以「管理員」身分登入節點，或透過 VM/實體控制台連線以 root 使用者身分登入。更改節點控制台密碼程序會為網格中的每個節點建立新密碼，並將密碼儲存在更新的 `Passwords.txt`恢復包中的檔案。密碼列在 Passwords.txt 檔案的密碼欄位中。


NOTE: 節點間通訊使用的 SSH 金鑰有單獨的 SSH 存取密碼。此程序不會變更 SSH 存取密碼。



== 訪問嚮導

.步驟
. 選擇*設定* > *存取控制* > *電網密碼*。
. 在*更改節點控制台密碼*下，選擇*進行更改*。




== 輸入設定密碼

.步驟
. 輸入您的網格的配置密碼。
. 選擇*繼續*。




== [[download-current]]下載當前復原包

在變更節點控制台密碼之前，請下載目前的復原包。如果任何節點的密碼變更過程失敗，您可以使用此檔案中的密碼。

.步驟
. 選擇*下載恢復包*。
. 複製復原包文件(`.zip`）到兩個安全、可靠且獨立的地點。
+

CAUTION: 復原包檔案必須是安全的，因為它包含可用於從StorageGRID系統取得資料的加密金鑰和密碼。

. 選擇*繼續*。
. 當確認對話方塊出現時，如果您準備好開始更改節點控制台密碼，請選擇*是*。
+
一旦該過程開始，您就無法取消。





== 更改節點控制台密碼

當節點控制台密碼程序啟動時，將產生一個包含新密碼的新復原包。然後，在每個節點上更新密碼。

.步驟
. 等待新的恢復包生成，這可能需要幾分鐘。
. 選擇*下載新的恢復包*。
. 下載完成後：
+
.. 打開 `.zip`文件。
.. 確認您可以存取內容，包括 `Passwords.txt`文件，其中包含新的節點控制台密碼。
.. 複製新的復原包文件(`.zip`）到兩個安全、可靠且獨立的地點。
+

CAUTION: 不要覆蓋舊的恢復包。

+
復原包檔案必須是安全的，因為它包含可用於從StorageGRID系統取得資料的加密金鑰和密碼。



. 選取核取方塊表示您已下載新的復原套件並驗證了內容。
. 選擇*更改節點控制台密碼*並等待所有節點更新新密碼。這可能需要幾分鐘。
+
如果所有節點的密碼都已更改，則會出現綠色的成功橫幅。轉至下一步。

+
如果更新過程中出現錯誤，橫幅訊息會列出密碼變更失敗的節點數。系統將自動在密碼變更失敗的任何節點上重試該過程。如果該過程結束時某些節點仍未更改密碼，則會出現「重試」按鈕。

+
如果一個或多個節點的密碼更新失敗：

+
.. 查看表中列出的錯誤訊息。
.. 解決問題。
.. 選擇*重試*。
+

NOTE: 重試僅更改在前一次密碼變更嘗試中失敗的節點上的節點控制台密碼。



. 更改所有節點的節點控制台密碼後，刪除<<download-current,您下載的第一個復原包>>。
. 或者，使用*恢復包*鏈接下載新恢復包的附加副本。

