---
permalink: admin/changing-browser-session-timeout-interface.html 
sidebar: sidebar 
keywords: security, browser inactivity timeout, management API stack track 
summary: 透過介面安全性設置，您可以控制當使用者處於非活動狀態的時間超過指定時間時是否將其註銷，以及是否在 API 錯誤回應中包含堆疊追蹤。 
---
= 更改介面安全設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
透過介面安全性設置，您可以控制當使用者處於非活動狀態的時間超過指定時間時是否將其註銷，以及是否在 API 錯誤回應中包含堆疊追蹤。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 你有link:admin-group-permissions.html["Root存取權限"]。


.關於此任務
*安全設定*頁麵包括*瀏覽器不活動逾時*和*管理 API 堆疊追蹤*設定。

瀏覽器不活動逾時:: 指示使用者登出之前瀏覽器可以處於非活動狀態的時間。預設值為 15 分鐘。
+
--
瀏覽器不活動逾時也受以下因素控制：

* 一個單獨的、不可設定的StorageGRID計時器，用於系統安全。每個使用者的身份驗證令牌在使用者登入 16 小時後過期。當使用者的身份驗證過期時，該使用者將自動登出，即使瀏覽器不活動逾時已停用或尚未達到瀏覽器逾時值。若要更新令牌，使用者必須重新登入。
* 身分提供者的逾時設置，假設為StorageGRID啟用了單一登入 (SSO)。
+
如果啟用了 SSO 並且使用者的瀏覽器逾時，則使用者必須重新輸入其 SSO 憑證才能再次存取StorageGRID 。看link:configuring-sso.html["配置單一登入"] 。



--
管理 API 堆疊追蹤:: 控制是否在網格管理器和租用戶管理器 API 錯誤回應中傳回堆疊追蹤。
+
--
預設此選項是停用的，但您可能希望為測試環境啟用此功能。一般來說，您應該在生產環境中停用堆疊追蹤，以避免在發生 API 錯誤時洩露內部軟體詳細資訊。

--


.步驟
. 選擇*配置* > *安全* > *安全設定*。
. 選擇“*介面*”選項卡。
. 若要更改瀏覽器不活動逾時設定：
+
.. 展開手風琴。
.. 若要變更逾時期限，請指定 60 秒到 7 天之間的值。預設超時時間為 15 分鐘。
.. 若要停用此功能，請取消選取該複選框。
.. 選擇*儲存*。
+
新設定不會影響目前已登入的使用者。使用者必須重新登入或刷新瀏覽器才能使新的逾時設定生效。



. 若要變更管理 API 堆疊追蹤的設定：
+
.. 展開手風琴。
.. 選取該複選框以在網格管理器和租用戶管理器 API 錯誤回應中傳回堆疊追蹤。
+

CAUTION: 在生產環境中停用堆疊追蹤，以避免在發生 API 錯誤時洩露內部軟體詳細資訊。

.. 選擇*儲存*。



