---
permalink: admin/creating-tenant-account.html 
sidebar: sidebar 
keywords: create tenant, tenant account 
summary: 您必須建立至少一個租用戶帳戶來控制對StorageGRID系統中儲存的存取。 
---
= 建立租用戶帳戶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須建立至少一個租用戶帳戶來控制對StorageGRID系統中儲存的存取。

建立租用戶帳戶的步驟取決於link:using-identity-federation.html["身分聯合"]和link:configuring-sso.html["單一登入"]是否配置，以及用於建立租用戶帳戶的網格管理器帳戶是否屬於具有 Root 存取權限的管理員群組。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 你有link:admin-group-permissions.html["根存取權限或租用戶帳戶權限"]。
* 如果租用戶帳戶將使用為網格管理員配置的身分來源，並且您想要將租用戶帳戶的 Root 存取權限授予聯合群組，則您已將該組合群組匯入網格管理器。您不需要為該管理群組指派任何網格管理器權限。看link:managing-admin-groups.html["管理管理員群組"] 。
* 如果您希望允許 S3 租用戶複製帳戶資料並使用網格聯合連線將儲存桶物件複製到另一個網格：
+
** 你有link:grid-federation-create-connection.html["配置電網聯合連接"]。
** 連線狀態為*已連線*。
** 您擁有 Root 存取權限。
** 您已查看了以下注意事項link:grid-federation-manage-tenants.html["管理電網聯合的允許租戶"]。
** 如果租用戶帳戶將使用為網格管理器配置的身分來源，則您已將相同的聯合群組匯入兩個網格上的網格管理器。
+
當您建立租用戶時，您將選擇此群組以擁有來源和目標租用戶帳戶的初始 Root 存取權。

+

TIP: 如果在建立租用戶之前兩個網格上都不存在此管理群組，則該租用戶不會被複製到目標。







== 訪問嚮導

.步驟
. 選擇*租戶*。
. 選擇“*創建*”。




== 輸入詳細信息

.步驟
. 輸入租戶的詳細資料。
+
[cols="1a,3a"]
|===
| 場地 | 描述 


 a| 
Name
 a| 
租戶帳戶的名稱。租戶名稱不需要是唯一的。建立租用戶帳戶時，它會收到一個唯一的 20 位元帳戶 ID。



 a| 
描述（可選）
 a| 
幫助識別租戶的描述。

如果您正在建立將使用網格聯合連線的租用戶，則可以選擇使用此欄位來協助識別哪個是來源租用戶，哪一個是目標租用戶。例如，在網格 1 上建立的租戶的描述也會出現在複製到網格 2 的租戶中：“此租戶是在網格 1 上建立的。”



 a| 
客戶端類型
 a| 
此租戶將使用的用戶端協定類型，*S3* 或 *Swift*。

*注意*：對 Swift 用戶端應用程式的支援已被棄用，並將在未來的版本中刪除。



 a| 
儲存配額（可選）
 a| 
如果您希望該租用戶擁有儲存配額，請為配額和單位指定一個數值。

|===
. 選擇*繼續*。




== [[admin-tenant-select-permissions]]選擇權限

.步驟
. 或者，選擇您希望此租用戶擁有的基本權限。
+

NOTE: 其中一些權限有額外的要求。有關詳細信息，請選擇每個權限的幫助圖示。

+
[cols="1a,3a"]
|===
| 允許 | 如果選擇... 


 a| 
允許平台服務
 a| 
租戶可以使用CloudMirror等S3平台服務。看link:../admin/manage-platform-services-for-tenants.html["管理 S3 租戶帳戶的平台服務"] 。



 a| 
使用自己的身分來源
 a| 
租用戶可以為聯合群組和使用者配置和管理自己的身分來源。如果您有以下情況，則此選項被停用link:../admin/configuring-sso.html["設定 SSO"]適用於您的StorageGRID系統。



 a| 
允許 S3 選擇
 a| 
租用戶可以發出 S3 SelectObjectContent API 請求來過濾和擷取物件資料。看link:../admin/manage-s3-select-for-tenant-accounts.html["管理租用戶帳戶的 S3 Select"] 。

*重要*：SelectObjectContent 請求可能會降低所有 S3 用戶端和所有租用戶的負載平衡器效能。僅在需要時且僅對受信任的租戶啟用此功能。

|===
. 或者，選擇您希望此租用戶擁有的高級權限。
+
[cols="1a,3a"]
|===
| 允許 | 如果選擇... 


 a| 
電網聯合連接
 a| 
租戶可以使用電網聯合連接，它可以：

** 導致此租戶以及新增至帳戶的所有租用戶群組和使用者從此網格（_來源網格_）複製到所選連接中的另一個網格（_目標網格_）。
** 允許此租戶在每個網格上的相應儲存桶之間配置跨網格複製。


看link:../admin/grid-federation-manage-tenants.html["管理電網聯合的允許租戶"] 。



 a| 
S3 對象鎖
 a| 
允許租用戶使用 S3 Object Lock 的特定功能：

** *設定最長保留期* 定義從提取新物件開始，新增至此儲存桶的新物件應保留多長時間。
** *允許合規模式*可防止使用者在保留期間內覆寫或刪除受保護的物件版本。


|===
. 選擇*繼續*。




== 定義根存取權限並建立租用戶

.步驟
. 根據您的StorageGRID系統是否使用身分聯合、單一登入 (SSO) 或兩者，定義租用​​戶帳戶的根存取權限。
+
[cols="1a,2a"]
|===
| 選項 | 執行此操作 


 a| 
如果未啟用身份聯合
 a| 
指定以本機 root 使用者身分登入租用戶時所使用的密碼。



 a| 
如果啟用了身份聯合
 a| 
.. 選擇一個現有的聯合群組，為租用戶提供 Root 存取權限。
.. 或者，指定以本機 root 使用者身分登入租用戶時所使用的密碼。




 a| 
如果同時啟用身份聯合和單一登入 (SSO)
 a| 
選擇一個現有的聯合群組，為租用戶提供 Root 存取權限。沒有本地用戶可以登入。

|===
. 選擇*建立租戶*。
+
出現成功訊息，並且新租戶會列在「租戶」頁面上。若要了解如何查看租戶詳細資訊和監控租戶活動，請參閱link:../monitor/monitoring-tenant-activity.html["監控租戶活動"]。

+

NOTE: 根據網路連線、節點狀態和 Cassandra 操作，在整個網格中套用租用戶設定可能需要 15 分鐘或更長時間。

. 如果您為租用戶選擇了「使用網格聯合連線」權限：
+
.. 確認相同的租戶已複製到連接中的另一個網格。兩個網格上的租戶將具有相同的 20 位元帳戶 ID、名稱、描述、配額和權限。
+

NOTE: 如果您看到錯誤訊息“建立租用戶時沒有複製”，請參閱link:grid-federation-troubleshoot.html["解決網格聯合錯誤"]。

.. 如果您在定義 root 存取權時提供了本機 root 使用者密碼，link:changing-password-for-tenant-local-root-user.html["更改本機 root 使用者的密碼"]對於複製的租戶。
+

TIP: 本機 root 使用者在密碼變更之前無法登入目標網格上的租用戶管理員。







== Sign in租戶（可選）

根據需要，您可以立即登入新租戶以完成配置，也可以稍後登入租戶。登入步驟取決於您是否使用預設連接埠（443）或受限連接埠登入網格管理器。看link:controlling-access-through-firewalls.html["控制外部防火牆的訪問"] 。



=== 立即Sign in

[cols="1a,3a"]
|===
| 如果您正在使用... | 這樣做... 


 a| 
連接埠 443 並為本機 root 使用者設定密碼
 a| 
. 選擇*以 rootSign in*。
+
當您登入時，會出現用於設定儲存桶、身分聯合、群組和使用者的連結。

. 選擇連結來配置租用戶帳戶。
+
每個連結都會開啟租戶管理器中的對應頁面。若要完成該頁面，請參閱link:../tenant/index.html["租戶帳戶使用說明"]。





 a| 
連接埠 443 且您沒有為本機 root 使用者設定密碼
 a| 
選擇*Sign in*，然後輸入根存取聯合群組中使用者的憑證。



 a| 
受限連接埠
 a| 
. 選擇“完成”
. 在租用戶表中選擇「*受限*」以了解有關存取此租用戶帳戶的詳細資訊。
+
租用戶管理員的 URL 格式如下：

+
`https://_FQDN_or_Admin_Node_IP:port_/?accountId=_20-digit-account-id_/`

+
** `_FQDN_or_Admin_Node_IP_`是管理節點的完全限定網域名稱或 IP 位址
** `_port_`是僅限租用戶的連接埠
** `_20-digit-account-id_`是租戶的唯一帳戶ID




|===


=== 稍後Sign in

[cols="1a,3a"]
|===
| 如果您正在使用... | 做其中之一... 


 a| 
埠 443
 a| 
* 從網格管理員中，選擇 *TENANTS*，然後選擇租用戶名稱右側的 *Sign in*。
* 在 Web 瀏覽器中輸入租用戶的 URL：
+
`https://_FQDN_or_Admin_Node_IP_/?accountId=_20-digit-account-id_/`

+
** `_FQDN_or_Admin_Node_IP_`是管理節點的完全限定網域名稱或 IP 位址
** `_20-digit-account-id_`是租戶的唯一帳戶ID






 a| 
受限連接埠
 a| 
* 從網格管理員中，選擇*TENANTS*，然後選擇*Restricted*。
* 在 Web 瀏覽器中輸入租用戶的 URL：
+
`https://_FQDN_or_Admin_Node_IP:port_/?accountId=_20-digit-account-id_`

+
** `_FQDN_or_Admin_Node_IP_`是管理節點的完全限定網域名稱或 IP 位址
** `_port_`是僅限租用戶的限制端口
** `_20-digit-account-id_`是租戶的唯一帳戶ID




|===


== 配置租戶

按照link:../tenant/index.html["使用租用戶帳戶"]管理租戶群組和使用者、S3 存取密鑰、儲存桶、平台服務以及帳戶克隆和跨網格複製。
