---
permalink: admin/creating-traffic-classification-policies.html 
sidebar: sidebar 
keywords: traffic classification, network traffic, traffic limits, policy 
summary: 如果您想要透過儲存桶、租用戶、IP 子網路或負載平衡器端點監控並選擇性地限制網路流量，則可以建立流量分類策略。或者，您可以根據頻寬、並發請求數或請求率設定策略限制。 
---
= 建立流量分類策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想要監控，則可以建立流量分類策略，並選擇性地透過儲存桶、儲存桶正規表示式、CIDR、負載平衡器端點或租用戶限製網路流量。或者，您可以根據頻寬、並發請求數或請求率設定策略限制。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 你有link:admin-group-permissions.html["Root存取權限"]。
* 您已建立想要匹配的任何負載平衡器端點。
* 您已建立任何想要匹配的租戶。


.步驟
. 選擇*配置* > *網路* > *流量分類*。
. 選擇“*創建*”。
. 輸入策略的名稱和描述（可選），然後選擇*繼續*。
+
例如，描述此流量分類策略適用於什麼以及它將限制什麼。

. 選擇*新增規則*並指定以下詳細資訊以為策略建立一個或多個符合規則。您建立的任何策略都應至少有一條符合規則。選擇*繼續*。
+
[cols="1a,3a"]
|===
| 場地 | 描述 


 a| 
類型
 a| 
選擇符合規則適用的流量類型。流量類型包括儲存桶、儲存桶正規表示式、CIDR、負載平衡器端點和租用戶。



 a| 
匹配值
 a| 
輸入與所選類型相符的值。

** 儲存桶：輸入一個或多個儲存桶名稱。
** Bucket regex：輸入一個或多個用來符合一組 bucket 名稱的正規表示式。
+
正規表示式未錨定。使用 ^ 錨點在 bucket 名稱的開頭進行匹配，並使用 $ 錨點在名稱的結尾進行匹配。正規表示式匹配支援 PCRE（Perl 相容正規表示式）語法的子集。

** CIDR：以 CIDR 表示法輸入與所需子網路相符的一個或多個 IPv4 子網路。
** 負載平衡器端點：選擇端點名稱。這些是您在link:../admin/configuring-load-balancer-endpoints.html["配置負載平衡器端點"]。
** 租戶：租戶匹配使用存取密鑰ID。如果請求中不包含存取金鑰ID（例如匿名存取），則使用所存取的儲存桶的所有權來確定租用戶。




 a| 
反向匹配
 a| 
如果您想要符合剛剛定義的類型和符合值一致的流量之外的所有網路流量，請勾選「*反向符合*」複選框。否則，請清除該複選框。

例如，如果您希望此策略套用於除一個負載平衡器端點之外的所有端點，請指定要排除的負載平衡器端點，然後選擇*反向符合*。

對於包含多個匹配器（其中至少有一個是逆匹配器）的策略，請注意不要建立匹配所有請求的策略。

|===
. 或者，選擇*新增限制*並選擇以下詳細資訊以新增一個或多個限制來控制規則匹配的網路流量。
+

NOTE: 即使您不新增任何限制， StorageGRID也會收集指標，因此您可以了解流量趨勢。

+
[cols="1a,3a"]
|===
| 場地 | 描述 


 a| 
類型
 a| 
您想要對規則相符的網路流量套用的限制類型。例如，您可以限制頻寬或請求速率。

*注意*：您可以建立策略來限制總頻寬或限制每個要求的頻寬。但是， StorageGRID不能同時限制兩種類型的頻寬。當聚合頻寬正在使用時，每個請求的頻寬不可用。相反，當每個請求的頻寬都在使用中時，聚合頻寬不可用。總頻寬限制可能會對不受限制的流量造成額外的輕微效能影響。

對於頻寬限制， StorageGRID會套用與限制集類型最相符的策略。例如，如果您有一個僅限制一個方向流量的策略，那麼相反方向的流量將不受限制，即使存在符合具有頻寬限制的其他策略的流量。  StorageGRID會依照下列順序實現頻寬限制的「最佳」配對：

** 精確的 IP 位址（/32 遮罩）
** 確切的儲存桶名稱
** 桶正規表示式
** 租戶
** 端點
** 非精確 CIDR 匹配（非 /32）
** 反向匹配




 a| 
適用於
 a| 
此限制是否適用於客戶端讀取請求（GET 或 HEAD）或寫入請求（PUT、POST 或 DELETE）。



 a| 
價值
 a| 
根據您選擇的單位，網路流量將被限制的值。例如輸入10並選擇MiB/s，則該規則所符合的網路流量不能超過10MiB/s。

*注意*：根據單位設置，可用的單位將是二進制（例如，GiB）或十進制（例如，GB）。若要變更單位設置，請選擇網格管理員右上角的使用者下拉式選單，然後選擇*使用者首選項*。



 a| 
單元
 a| 
描述您輸入的值的單位。

|===
+
例如，如果您想要為 SLA 層建立 40 GB/s 的頻寬限制，請建立兩個聚合頻寬限制：GET/HEAD 為 40 GB/s，PUT/POST/DELETE 為 40 GB/s。

. 選擇*繼續*。
. 閱讀並檢討流量分類政策。使用“*上一步*”按鈕返回並根據需要進行更改。當您對政策滿意時，選擇*保存並繼續*。
+
S3 用戶端流量現在會根據流量分類策略進行處理。



.完成後
link:viewing-network-traffic-metrics.html["查看網路流量指標"]驗證政策是否正在執行您期望的流量限制。
