---
permalink: admin/deactivate-features-from-api.html 
sidebar: sidebar 
keywords: deactivate features from api 
summary: 您可以使用網格管理 API 完全停用StorageGRID系統中的某些功能。當某項功能停用時，任何人都無法被指派執行與該功能相關的任務的權限。 
---
= 使用 API 停用功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用網格管理 API 完全停用StorageGRID系統中的某些功能。當某項功能停用時，任何人都無法被指派執行與該功能相關的任務的權限。

.關於此任務
停用功能係統可讓您阻止存取StorageGRID系統中的某些功能。停用某項功能是阻止根使用者或具有 *Root 存取* 權限的管理群組使用者使用此功能的唯一方法。

要了解此功能如何有用，請考慮以下場景：

_公司 A 是一家服務供應商，透過建立租用戶帳戶來租賃其StorageGRID系統的儲存容量。為了保護其租賃對象的安全，A 公司希望確保其員工在部署帳戶後永遠無法存取任何租戶帳戶。

_公司 A 可以透過使用網格管理 API 中的停用功能係統來實現這一目標。透過在網格管理員（UI 和 API）中完全停用「變更租用戶根密碼」功能，公司 A 確保管理員使用者（包括根使用者和屬於具有「根存取」權限的群組的使用者）無法變更任何租用戶帳戶的根用戶的密碼。

.步驟
. 存取網格管理 API 的 Swagger 文件。看link:using-grid-management-api.html["使用網格管理 API"] 。
. 找到停用功能端點。
. 若要停用某項功能（例如變更租用戶根密碼），請向 API 傳送如下正文：
+
`{ "grid": {"changeTenantRootPassword": true} }`

+
請求完成後，更改租用戶 root 密碼功能將被停用。  *更改租用戶根密碼*管理權限不再出現在使用者介面中，並且任何嘗試更改租用戶根密碼的 API 請求都將失敗並顯示「403 禁止」。





== 重新啟用已停用的功能

預設情況下，您可以使用網格管理 API 重新啟用已停用的功能。但是，如果您想要防止已停用的功能被重新激活，您可以停用 *activateFeatures* 功能本身。


CAUTION: *activateFeatures* 功能無法重新啟動。如果您決定停用此功能，請注意，您將永久失去重新啟用任何其他已停用功能的能力。您必須聯絡技術支援以恢復任何遺失的功能。

.步驟
. 存取網格管理 API 的 Swagger 文件。
. 找到停用功能端點。
. 若要重新啟動所有功能，請向 API 發送如下正文：
+
`{ "grid": null }`

+
當此請求完成後，所有功能（包括變更租用戶根密碼功能）都會重新啟用。  *更改租用戶根密碼*管理權限現在出現在使用者介面中，並且任何嘗試更改租用戶根密碼的 API 請求都將成功，假設使用者俱有*根存取權*或*更改租用戶根密碼*管理權限。




TIP: 前面的範例導致所有已停用的功能被重新啟用。如果其他功能已停用且應保持停用狀態，則必須在 PUT 請求中明確指定它們。例如，若要重新啟用變更租用戶 root 密碼功能並繼續停用 storageAdmin 管理權限，請傳送此 PUT 要求：+
`{ "grid": {"storageAdmin": true} }`
