---
permalink: admin/grid-federation-retry-failed-replication.html 
sidebar: sidebar 
keywords: grid federation, troubleshoot 
summary: 解決跨網格複製永久失敗警報後，您應該確定是否有任何物件或刪除標記無法複製到另一個網格。然後，您可以重新擷取這些物件或使用網格管理 API 重試複製。 
---
= 識別並重試失敗的複製操作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
解決*跨網格複製永久失敗*警報後，您應該確定是否有任何物件或刪除標記無法複製到另一個網格。然後，您可以重新擷取這些物件或使用網格管理 API 重試複製。

*跨網格複製永久失敗*警報表示由於需要使用者乾預才能解決的原因，租戶物件無法在兩個網格上的儲存桶之間複製。此警報通常是由來源儲存桶或目標儲存桶的變更引起的。有關詳細信息，請參閱link:grid-federation-troubleshoot.html["解決網格聯合錯誤"] 。



== 確定是否有任何物件複製失敗

若要確定是否有任何物件或刪除標記尚未複製到另一個網格，您可以搜尋稽核日誌link:../audit/cgrr-cross-grid-replication-request.html["CGRR（跨網格複製請求）"]消息。當StorageGRID無法將物件、多部分物件或刪除標記複製到目標儲存桶時，此訊息將會新增至日誌中。

您可以使用link:../audit/using-audit-explain-tool.html["審計解釋工具"]將結果轉換成更易於閱讀的格式。

.開始之前
* 您擁有 Root 存取權限。
* 你有 `Passwords.txt`文件。
* 您知道主管理節點的 IP 位址。


.步驟
. 登入主管理節點：
+
.. 輸入以下命令： `ssh admin@_primary_Admin_Node_IP_`
.. 輸入 `Passwords.txt`文件。
.. 輸入以下命令切換到root： `su -`
.. 輸入 `Passwords.txt`文件。
+
當您以 root 身分登入時，提示字元將從 `$`到 `#`。



. 在 audit.log 中搜尋 CGRR 訊息，並使用 audit-explain 工具格式化結果。
+
例如，此命令會尋找過去 30 分鐘內的所有 CGRR 訊息並使用 audit-explain 工具。

+
`# awk -vdate=$(date -d "30 minutes ago" '+%Y-%m-%dT%H:%M:%S') '$1$2 >= date { print }' audit.log | grep CGRR | audit-explain`

+
該命令的結果將類似於此範例，其中包含六個 CGRR 訊息的條目。在範例中，所有跨網格複製請求都傳回了一般錯誤，因為無法複製物件。前三個錯誤是針對「複製物件」操作的，後三個錯誤是針對「複製刪除標記」操作的。

+
[listing]
----
CGRR Cross-Grid Replication Request tenant:50736445269627437748 connection:447896B6-6F9C-4FB2-95EA-AEBF93A774E9 operation:"replicate object" bucket:bucket123 object:"audit-0" version:QjRBNDIzODAtNjQ3My0xMUVELTg2QjEtODJBMjAwQkI3NEM4 error:general error
CGRR Cross-Grid Replication Request tenant:50736445269627437748 connection:447896B6-6F9C-4FB2-95EA-AEBF93A774E9 operation:"replicate object" bucket:bucket123 object:"audit-3" version:QjRDOTRCOUMtNjQ3My0xMUVELTkzM0YtOTg1MTAwQkI3NEM4 error:general error
CGRR Cross-Grid Replication Request tenant:50736445269627437748 connection:447896B6-6F9C-4FB2-95EA-AEBF93A774E9 operation:"replicate delete marker" bucket:bucket123 object:"audit-1" version:NUQ0OEYxMDAtNjQ3NC0xMUVELTg2NjMtOTY5NzAwQkI3NEM4 error:general error
CGRR Cross-Grid Replication Request tenant:50736445269627437748 connection:447896B6-6F9C-4FB2-95EA-AEBF93A774E9 operation:"replicate delete marker" bucket:bucket123 object:"audit-5" version:NUQ1ODUwQkUtNjQ3NC0xMUVELTg1NTItRDkwNzAwQkI3NEM4 error:general error
----
+
每個條目包含以下資訊：

+
[cols="1a,2a"]
|===
| 場地 | 描述 


| CGRR 跨網格複製請求  a| 
請求的名稱



| 租戶  a| 
租戶的帳戶ID



| 聯繫  a| 
電網聯合連接的ID



| 手術  a| 
正在嘗試的複製操作類型：

** 複製對象
** 複製刪除標記
** 複製多部分對象




| 桶  a| 
儲存桶名稱



| 目的  a| 
物件名稱



| 版本  a| 
物件的版本 ID



| 錯誤  a| 
錯誤類型。如果跨網格複製失敗，則錯誤為「常規錯誤」。

|===




== 重試失敗的複製

產生未複製到目標儲存桶的物件和刪除標記清單並解決底層問題後，您可以透過以下兩種方式之一重試複製：

* 將每個物件重新放入來源儲存桶。
* 按照說明使用網格管理私有 API。


.步驟
. 從網格管理器的頂部，選擇幫助圖示並選擇*API 文件*。
. 選擇*轉到私有 API 文件*。
+

NOTE: 標記為「私有」的StorageGRID API 端點如有更改，恕不另行通知。  StorageGRID私有端點也會忽略請求的 API 版本。

. 在 *cross-grid-replication-advanced* 部分中，選擇以下端點：
+
`POST /private/cross-grid-replication-retry-failed`

. 選擇*試用*。
. 在 *body* 文字方塊中，將 *versionID* 的範例條目替換為 audit.log 中與失敗的跨網格複製請求相對應的版本 ID。
+
確保保留字串周圍的雙引號。

. 選擇*執行*。
. 確認伺服器回應代碼為*204*，表示物件或刪除標記已被標記為待跨網格複製到另一個網格。
+

NOTE: 待處理意味著跨網格複製請求已新增至內部佇列等待處理。





== 監視複製重試

您應該監視複製重試操作以確保它們完成。


TIP: 將物件或刪除標記複製到另一個網格可能需要幾個小時或更長時間。

您可以透過以下兩種方式之一監視重試操作：

* 使用 S3link:../s3/head-object.html["頭部對象"]或者link:../s3/get-object.html["取得對象"]要求。響應包括StorageGRID特定的 `x-ntap-sg-cgr-replication-status`響應標頭，它將具有以下值之一：
+
[cols="1a,2a"]
|===
| 網格 | 複製狀態 


 a| 
來源
 a| 
** *已完成*：複製成功。
** *待定*：物件尚未被複製。
** *失敗*：複製失敗，並發生永久性故障。使用者必須解決該錯誤。




 a| 
目的地
 a| 
*REPLICA*：物件已從來源網格複製。

|===
* 按照說明使用網格管理私有 API。


.步驟
. 在私有 API 文件的 *cross-grid-replication-advanced* 部分中，選擇以下端點：
+
`GET /private/cross-grid-replication-object-status/{id}`

. 選擇*試用*。
. 在參數部分中，輸入您在 `cross-grid-replication-retry-failed`要求。
. 選擇*執行*。
. 確認伺服器回應代碼為*200*。
. 查看複製狀態，其狀態將是以下之一：
+
** *待定*：物件尚未被複製。
** *已完成*：複製成功。
** *失敗*：複製失敗，並發生永久性故障。使用者必須解決該錯誤。



