---
permalink: admin/grid-federation-compare-cgr-to-cloudmirror.html 
sidebar: sidebar 
keywords: cross-grid replication, cloudmirror replication 
summary: 當您開始使用網格聯合時，請查看跨網格複製和StorageGRID CloudMirror 複製服務之間的異同。 
---
= 比較跨網格複製和 CloudMirror 複製
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當你開始使用網格聯合時，回顧一下link:grid-federation-what-is-cross-grid-replication.html["跨網格複製"]以及link:../tenant/understanding-cloudmirror-replication-service.html["StorageGRID CloudMirror 複製服務"]。

[cols="1a,3a,3a"]
|===
|  | 跨網格複製 | CloudMirror複製服務 


 a| 
主要目的是什麼？
 a| 
一個StorageGRID系統充當災難復原系統。儲存桶中的物件可以在網格之間單向或雙向複製。
 a| 
使租用戶能夠自動將物件從StorageGRID （來源）中的儲存桶複製到外部 S3 儲存桶（目標）。

CloudMirror 複製在獨立的 S3 基礎架構中建立物件的獨立副本。此獨立副本不用作備份，但通常在雲端中進一步處理。



 a| 
如何設置？
 a| 
. 配置兩個網格之間的網格聯合連接。
. 新增的租用戶帳戶，這些帳戶會自動複製到另一個網格。
. 新增新的租戶群組和用戶，也進行克隆。
. 在每個網格上建立相應的儲存桶，並啟用跨網格複製以在一個方向或兩個方向上進行。

 a| 
. 租用戶用戶透過使用租用戶管理器或 S3 API 定義 CloudMirror 端點（IP 位址、憑證等）來設定 CloudMirror 複製。
. 此租用戶帳戶擁有的任何儲存桶都可以設定為指向 CloudMirror 端點。




 a| 
誰負責設置它？
 a| 
* 網格管理員配置連線和租用戶。
* 租戶用戶配置群組、用戶、密鑰和儲存桶。

 a| 
通常是租戶用戶。



 a| 
目的地是哪裡？
 a| 
網格聯合連接中另一個StorageGRID系統上對應且相同的 S3 儲存桶。
 a| 
* 任何相容的 S3 基礎設施（包括 Amazon S3）。
* 谷歌雲端平台（GCP）




 a| 
是否需要物件版本控制？
 a| 
是的，來源儲存桶和目標儲存桶都必須啟用物件版本控制。
 a| 
不，CloudMirror 複製支援來源和目標上任意組合的非版本化和版本化儲存桶。



 a| 
什麼原因導致物體移動到目的地？
 a| 
當物件被加入到啟用了跨網格複製的儲存桶時，它們會自動複製。
 a| 
當物件被加入到已配置 CloudMirror 端點的儲存桶時，物件會自動複製。在使用 CloudMirror 端點配置儲存桶之前，來源儲存桶中存在的物件不會被複製，除非它們被修改。



 a| 
物件是如何複製的？
 a| 
跨網格複製建立版本化對象，並將版本 ID 從來源儲存桶複製到目標儲存桶。這允許在兩個網格中維護版本順序。
 a| 
CloudMirror 複製不需要啟用版本控制的儲存桶，因此 CloudMirror 只能維護網站內金鑰的排序。無法保證對不同站點的物件請求的順序能夠保持不變。



 a| 
如果一個物件無法被複製怎麼辦？
 a| 
該物件正在排隊等待複製，但受到元資料儲存限制。
 a| 
該物件正在排隊等待複製，但受平台服務限制（請參閱link:manage-platform-services-for-tenants.html["使用平台服務的建議"]）。



 a| 
物件的系統元資料是否被複製？
 a| 
是的，當一個物件被複製到另一個網格時，它的系統元資料也會被複製。兩個網格上的元資料將是相同的。
 a| 
不會，當物件被複製到外部儲存桶時，其係統元資料會被更新。元資料在不同位置會有所不同，取決於攝取時間和獨立 S3 基礎設施的行為。



 a| 
如何檢索物件？
 a| 
應用程式可以透過向任一網格上的儲存桶發出請求來檢索或讀取物件。
 a| 
應用程式可以透過向StorageGRID或 S3 目標發出請求來檢索或讀取物件。例如，假設您使用 CloudMirror 複製將物件映像到合作夥伴組織。合作夥伴可以使用自己的應用程式直接從 S3 目標讀取或更新物件。不需要使用StorageGRID 。



 a| 
如果刪除物件會發生什麼？
 a| 
* 包含版本 ID 的刪除請求永遠不會複製到目標網格。
* 不包含版本 ID 的刪除請求會向來源儲存桶新增刪除標記，可以選擇將其複製到目標網格。
* 如果跨網格複製僅配置為一個方向，則可以刪除目標儲存體桶中的物件而不會影響來源。

 a| 
結果將根據來源儲存桶和目標儲存桶的版本狀態而有所不同（它們不需要相同）：

* 如果兩個儲存桶都已版本化，則刪除請求將在兩個位置新增刪除標記。
* 如果僅對來源儲存桶進行版本控制，則刪除請求將向來源新增刪除標記，但不會向目標新增刪除標記。
* 如果兩個儲存桶都沒有版本控制，則刪除請求將從來源中刪除對象，但不會從目標中刪除。


同樣，可以刪除目標儲存桶中的對象，而不會影響來源。

|===