---
permalink: admin/how-ha-groups-are-used.html 
sidebar: sidebar 
keywords: ha groups, high availability group 
summary: '您可以使用高可用性 (HA) 群組為物件資料和管理用途提供與StorageGRID的高可用性連線。' 
---
= HA 組如何使用？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用高可用性 (HA) 群組為物件資料和管理用途提供與StorageGRID的高可用性連線。

* HA 群組可以為網格管理器或租用戶管理器提供高可用性管理連線。
* HA 組可以為 S3 用戶端提供高可用性資料連線。
* 僅包含一個介面的 HA 群組可讓您提供多個 VIP 位址並明確設定 IPv6 位址。


只有當群組中包含的所有節點都提供相同的服務時，HA 組才能提供高可用性。建立 HA 群組時，從提供所需服務的節點類型中新增介面。

* *管理節點*：包含負載平衡器服務並啟用對網格管理器或租戶管理器的存取。
* *網關節點*：包含負載平衡器服務。


[cols="1a,2a"]
|===
| HA 組的目的 | 將此類型的節點新增至 HA 群組 


 a| 
存取網格管理器
 a| 
* 主管理節點（*主*）
* 非主管理節點


*注意：*主管理節點必須是主介面。某些維護程序只能從主管理節點執行。



 a| 
僅限租戶經理訪問
 a| 
* 主要或非主要管理節點




 a| 
S3 用戶端存取權－負載平衡器服務
 a| 
* 管理節點
* 閘道




 a| 
S3 用戶端訪問link:../admin/manage-s3-select-for-tenant-accounts.html["S3 選擇"]
 a| 
* 服務設備
* 基於 VMware 的軟體節點


*注意*：使用 S3 Select 時建議使用 HA 組，但這不是必需的。

|===


== 使用 HA 群組與 Grid Manager 或 Tenant Manager 的限制

如果網格管理器或租用戶管理器服務發生故障，則不會觸發 HA 群組故障轉移。

如果在發生故障轉移時您已登入網格管理器或租用戶管理器，則您將被登出，並且必須再次登入才能恢復您的任務。

當主管理節點不可用時，某些維護程序無法執行。在故障轉移期間，您可以使用網格管理器來監控您的StorageGRID系統。
