---
permalink: admin/managing-traffic-classification-policies.html 
sidebar: sidebar 
keywords: QoS, quality of service, traffic classification, best practices, limit traffic, monitor traffic 
summary: '流量分類策略可讓您識別和監控不同類型的網路流量。這些策略可以幫助限制和監控流量，以增強您的服務品質 (QoS)。' 
---
= 什麼是流量分類策略？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
流量分類策略可讓您識別和監控不同類型的網路流量。這些策略可以幫助限制和監控流量，以增強您的服務品質 (QoS)。

流量分類策略應用於網關節點和管理節點的StorageGRID負載平衡器服務上的端點。若要建立流量分類策略，您必須已經建立負載平衡器端點。



== 匹配規則

每個流量分類策略包含一個或多個符合規則，用於識別與以下一個或多個實體相關的網路流量：

* 鏟鬥
* 子網
* 租戶
* 負載平衡器端點


StorageGRID根據規則的目標監控與策略內任何規則相符的流量。任何與策略規則相符的流量都由該策略處理。相反，您可以設定規則來符合除指定實體之外的所有流量。



== 限流

您可以選擇將以下限制類型新增至策略：

* 總頻寬
* 每個請求的頻寬
* 並發請求
* 請求率


限制值是根據每個負載平衡器強制執行的。如果流量同時分佈在多個負載平衡器之間，則總最大速率是您指定的速率限制的倍數。


NOTE: 您可以建立策略來限制總頻寬或限制每個要求的頻寬。但是， StorageGRID不能同時限制兩種類型的頻寬。總頻寬限制可能會對不受限制的流量造成額外的輕微效能影響。

對於聚合或每個請求的頻寬限制，請求以您設定的速率流入或流出。 StorageGRID只能強制執行一種速度，因此根據匹配器類型，最具體的政策匹配就是強制執行的策略。此請求消耗的頻寬不會計入包含聚合頻寬限制策略的其他不太具體的配對策略。對於所有其他限制類型，用戶端請求將延遲 250 毫秒，並且對於超出任何匹配策略限制的請求，將收到 503 Slow Down 回應。

在網格管理器中，您可以查看流量​​圖表並驗證策略是否正在執行您期望的流量限制。



== 將流量分類策略與 SLA 結合使用

您可以將流量分類策略與容量限制和資料保護結合使用，以強制執行提供容量、資料保護和效能細節的服務等級協定 (SLA)。

以下範例顯示了 SLA 的三個層級。您可以建立流量分類策略來實現每個 SLA 層的效能目標。

[cols="1a,1a,1a,1a,1a"]
|===
| 服務等級層 | 容量 | 資料保護 | 允許的最大性能 | 成本 


 a| 
金子
 a| 
允許 1 PB 儲存空間
 a| 
3 份 ILM 規則
 a| 
25K 個請求/秒

5 GB/秒（40 Gbps）頻寬
 a| 
$$$ 每月



 a| 
銀
 a| 
允許 250 TB 儲存空間
 a| 
2 份 ILM 規則
 a| 
每秒 10 K 個請求

1.25 GB/秒（10 Gbps）頻寬
 a| 
每月$$



 a| 
青銅
 a| 
允許 100 TB 儲存空間
 a| 
2 份 ILM 規則
 a| 
5K 個請求/秒

1 GB/秒（8 Gbps）頻寬
 a| 
$ 每月

|===