---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: '租用戶帳戶可讓您使用簡單儲存服務 \(S3\) REST API 在StorageGRID系統中儲存和擷取物件。' 
---
= 什麼是租戶帳戶？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
租用戶帳戶可讓您使用簡單儲存服務 (S3) REST API 在StorageGRID系統中儲存和擷取物件。


TIP: 此版本的文件網站已刪除 Swift 詳細資訊。看 https://docs.netapp.com/us-en/storagegrid-118/admin/managing-tenants.html["StorageGRID 11.8：管理租戶"^]。

身為網格管理員，您可以建立和管理 S3 用戶端用於儲存和擷取物件的租用戶帳戶。

每個租用戶帳戶都有聯合或本機群組、使用者、S3 儲存桶和物件。

租用戶帳戶可用於依不同實體隔離儲存的物件。例如，多個租用戶帳戶可用於下列任一用例：

* *企業用例：*如果您在企業應用程式中管理StorageGRID系統，您可能想要按組織中的不同部門隔離網格的物件儲存。在這種情況下，您可以為行銷部門、客戶支援部門、人力資源部門等建立租戶帳戶。
+

NOTE: 如果您使用 S3 用戶端協議，則可以使用 S3 儲存桶和儲存桶策略在企業各部門之間隔離物件。您不需要使用租用戶帳戶。請參閱實施說明link:../s3/bucket-and-group-access-policies.html["S3 儲存桶和儲存桶策略"]了解更多。

* *服務提供者使用案例：*如果您作為服務提供者管理StorageGRID系統，則可以透過租用網格儲存的不同實體來隔離網格的物件儲存。在這種情況下，您將為公司 A、公司 B、公司 C 等建立租戶帳戶。


有關更多信息，請參閱link:../tenant/index.html["使用租用戶帳戶"] 。



== 如何建立租用戶帳戶？

使用網格管理器建立租戶帳戶。建立租用戶帳戶時，請指定以下資訊：

* 基本資訊包括租用戶名稱、用戶端類型（S3）和可選儲存配額。
* 租用戶帳戶的權限，例如租用戶帳戶是否可以使用 S3 平台服務、設定自己的身分來源、使用 S3 Select 或使用網格聯合連線。
* 租用戶的初始根存取權限，取決於StorageGRID系統是否使用本機群組和使用者、身分聯合或單一登入 (SSO)。


此外，如果 S3 租用戶帳戶需要遵守監管要求，您可以為StorageGRID系統啟用 S3 物件鎖定設定。啟用 S3 物件鎖定後，所有 S3 租用戶帳戶都可以建立和管理相容的儲存桶。



== 租戶管理器有什麼用途？

建立租用戶帳戶後，租用戶用戶可以登入租用戶管理員執行下列任務：

* 設定身份聯合（除非身份來源與網格共享）
* 管理群組和用戶
* 使用網格聯合進行帳戶克隆和跨網格複製
* 管理 S3 存取密鑰
* 建立和管理 S3 儲存桶
* 使用 S3 平台服務
* 使用 S3 Select
* 監控儲存使用情況



TIP: 雖然 S3 租用戶用戶可以使用租用戶管理器建立和管理 S3 存取金鑰和儲存桶，但他們必須使用 S3 用戶端應用程式來提取和管理物件。看link:../s3/index.html["使用 S3 REST API"]了解詳情。
