---
permalink: admin/networking-and-ports-for-platform-services.html 
sidebar: sidebar 
keywords: platform services, ports for platform services, 443, 80 
summary: 如果您允許 S3 租用戶使用平台服務，則必須為網格配置網路以確保平台服務訊息能夠傳遞到其目的地。 
---
= 平台服務的網路和端口
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您允許 S3 租用戶使用平台服務，則必須為網格配置網路以確保平台服務訊息能夠傳遞到其目的地。

您可以在建立或更新租用戶帳戶時為 S3 租用戶帳戶啟用平台服務。如果啟用了平台服務，租用戶可以建立端點作為 CloudMirror 複製、事件通知或從其 S3 儲存桶搜尋整合訊息的目標。這些平台服務訊息從執行 ADC 服務的儲存節點傳送到目標端點。

例如，租用戶可能會配置以下類型的目標端點：

* 本地託管的 Elasticsearch 集群
* 支援接收 Amazon Simple Notification Service 訊息的本機應用程式
* 本機託管的 Kafka 集群
* 位於同一或另一個StorageGRID實例上的本機託管的 S3 儲存桶
* 外部端點，例如 Amazon Web Services 上的端點。


為了確保平台服務訊息能夠傳遞，您必須配置包含 ADC 儲存節點的網路。您必須確保以下連接埠可用於將平台服務訊息傳送至目標端點。

預設情況下，平台服務訊息在以下連接埠發送：

* *80*：適用於以 http 開頭的端點 URI（大多數端點）
* *443*：適用於以 https 開頭的端點 URI（大多數端點）
* *9092*：對於以 http 或 https 開頭的端點 URI（僅限 Kafka 端點）


租戶在建立或編輯端點時可以指定不同的連接埠。


NOTE: 如果使用StorageGRID部署作為 CloudMirror 複製的目標，則可能會在 80 或 443 以外的連接埠上收到複製訊息。確保在端點中指定目標StorageGRID部署用於 S3 的連接埠。

如果您使用非透明代理伺服器，您還必須link:configuring-storage-proxy-settings.html["配置儲存代理設定"]允許將訊息傳送到外部端點，例如網路上的端點。

.相關資訊
link:../tenant/index.html["使用租用戶帳戶"]
