---
permalink: admin/summary-ip-addresses-and-ports-for-client-connections.html 
sidebar: sidebar 
keywords: ip addresses for client, how to connect to storagegrid, ports, vip 
summary: '為了儲存或檢索對象，S3 用戶端應用程式連接到所有管理節點和網關節點上包含的負載平衡器服務，或連接到所有儲存節點上包含的本機分發路由器 (LDR) 服務。' 
---
= 摘要：客戶端連接的 IP 位址和連接埠
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
為了儲存或檢索對象，S3 用戶端應用程式連接到所有管理節點和網關節點上包含的負載平衡器服務，或連接到所有儲存節點上包含的本機分發路由器 (LDR) 服務。

用戶端應用程式可以使用網格節點的 IP 位址和該節點上的服務的連接埠號碼連接到StorageGRID 。或者，您可以建立負載平衡節點的高可用性 (HA) 群組，以提供使用虛擬 IP (VIP) 位址的高可用性連線。如果您想要使用完全限定網域名稱 (FQDN) 而不是 IP 或 VIP 位址連線到StorageGRID ，您可以設定 DNS 項目。

此表總結了用戶端連接到StorageGRID 的不同方式以及用於每種連接類型的 IP 位址和連接埠。如果您已建立負載平衡器端點和高可用性 (HA) 群組，請參閱<<在哪裡查找 IP 位址>>在網格管理器中定位這些值。

[cols="1a,1a,1a,1a"]
|===
| 連接地點 | 用戶端連線的服務 | IP 位址 | 港口 


 a| 
HA組
 a| 
負載平衡器
 a| 
HA組的虛擬IP位址
 a| 
分配給負載平衡器端點的端口



 a| 
管理節點
 a| 
負載平衡器
 a| 
管理節點的 IP 位址
 a| 
分配給負載平衡器端點的端口



 a| 
閘道
 a| 
負載平衡器
 a| 
網關節點的IP位址
 a| 
分配給負載平衡器端點的端口



 a| 
儲存節點
 a| 
遠距離駕駛
 a| 
儲存節點IP位址
 a| 
預設 S3 連接埠：

* HTTPS：18082
* HTTP：18084


|===


== 範例 URL

若要將用戶端應用程式連接到網關節點 HA 群組的負載平衡器端點，請使用如下所示結構的 URL：

`https://_VIP-of-HA-group:LB-endpoint-port_`

例如，如果 HA 群組的虛擬 IP 位址為 192.0.2.5，負載平衡器端點的連接埠號碼為 10443，則應用程式可以使用下列 URL 連接至StorageGRID：

`\https://192.0.2.5:10443`



== 在哪裡查找 IP 位址

. Sign inlink:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
. 若要尋找網格節點的 IP 位址：
+
.. 選擇*NODES*。
.. 選擇要連接的管理節點、網關節點或儲存節點。
.. 選擇“*概覽*”標籤。
.. 在節點資訊部分中，記下節點的 IP 位址。
.. 選擇*顯示更多*以查看 IPv6 位址和介面映射。
+
您可以從客戶端應用程式與清單中的任何 IP 位址建立連線：

+
*** *eth0:* 網格網絡
*** *eth1：*管理網路（可選）
*** *eth2：*客戶端網路（選購）
+

NOTE: 如果您正在查看管理節點或網關節點，並且它是高可用性群組中的活動節點，則 HA 群組的虛擬 IP 位址將顯示在 eth2 上。





. 若要尋找高可用性群組的虛擬 IP 位址：
+
.. 選擇 *配置* > *網路* > *高可用性群組*。
.. 在表中，記下 HA 群組的虛擬 IP 位址。


. 若要尋找負載平衡器端點的連接埠號碼：
+
.. 選擇 *配置* > *網路* > *負載平衡器端點*。
.. 記下您要使用的端點的連接埠號碼。
+

NOTE: 如果連接埠號碼是 80 或 443，則端點僅在網關節點上配置，因為這些連接埠在管理節點上保留。所有其他連接埠均在網關節點和管理節點上配置。

.. 從表格中選擇端點的名稱。
.. 確認*客戶端類型*（S3）與將使用端點的客戶端應用程式相符。



