---
permalink: admin/use-s3-setup-wizard.html 
sidebar: sidebar 
keywords: S3, S3 setup wizard 
summary: 您可以使用 S3 設定精靈將StorageGRID配置為 S3 應用程式的物件儲存系統。 
---
= 使用 S3 設定精靈：注意事項與要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 S3 設定精靈將StorageGRID配置為 S3 應用程式的物件儲存系統。



== 何時使用 S3 設定嚮導

S3 設定精靈將引導您完成設定StorageGRID以與 S3 應用程式一起使用的每個步驟。作為完成精靈的一部分，您可以下載可用於將值輸入到 S3 應用程式中的檔案。使用精靈可以更快地配置您的系統並確保您的設定符合StorageGRID最佳實務。

如果你有link:admin-group-permissions.html["Root存取權限"]，您可以在開始使用StorageGRID Grid Manager 時完成 S3 設定精靈，也可以在以後的任何時間存取並完成該精靈。根據您的要求，您也可以手動配置部分或全部所需項目，然後使用精靈來組裝 S3 應用程式所需的值。



== 使用精靈之前

在使用該精靈之前，請確認您已完成這些先決條件。

取得 IP 位址並設定 VLAN 介面:: 如果您要設定高可用性 (HA) 群組，您就會知道 S3 應用程式將連接到哪些節點以及將使用哪個StorageGRID網路。您也知道要為子網路 CIDR、閘道 IP 位址和虛擬 IP (VIP) 位址輸入哪些值。
+
--
如果您打算使用虛擬 LAN 來隔離來自 S3 應用程式的流量，則您已經設定了 VLAN 介面。看link:../admin/configure-vlan-interfaces.html["配置VLAN介面"] 。

--
設定身份聯合和 SSO:: 如果您打算對StorageGRID系統使用身分聯合或單一登入 (SSO)，則您已啟用這些功能。您也知道哪個聯合群組應該對 S3 應用程式將使用的租用戶帳戶具有根存取權限。看link:../admin/using-identity-federation.html["使用身分聯合"]和link:../admin/configuring-sso.html["配置單一登入"]。
取得並配置域名:: 您知道要為StorageGRID使用哪一個完全限定網域名稱 (FQDN)。網域名稱伺服器 (DNS) 項目會將此 FQDN 對應到您使用精靈建立的 HA 群組的虛擬 IP (VIP) 位址。
+
--
如果您打算使用 S3 虛擬託管式請求，您應該link:../admin/configuring-s3-api-endpoint-domain-names.html["配置的 S3 端點域名"]。建議使用虛擬託管式請求。

--
審查負載平衡器和安全性證書要求:: 如果您打算使用StorageGRID負載平衡器，則您已經查看了負載平衡的一般注意事項。您擁有要上傳的憑證或產生憑證所需的值。
+
--
如果您打算使用外部（第三方）負載平衡器端點，則您擁有該負載平衡器的完全限定網域名稱（FQDN）、連接埠和憑證。

--
配置任何電網聯合連接:: 如果您希望允許 S3 租用戶複製帳戶資料並使用網格聯合連線將儲存桶物件複製到另一個網格，請在啟動精靈之前確認以下內容：
+
--
* 你有link:grid-federation-manage-connection.html["配置電網聯合連接"]。
* 連線狀態為*已連線*。
* 您擁有 Root 存取權限。


--

