---
permalink: admin/viewing-network-traffic-metrics.html 
sidebar: sidebar 
keywords: network traffic, traffic classification policy, monitor traffic 
summary: 您可以透過查看「流量分類策略」頁面提供的圖表來監控網路流量。 
---
= 查看網路流量指標
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以透過查看「流量分類策略」頁面提供的圖表來監控網路流量。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 你有link:admin-group-permissions.html["根存取權限或租用戶帳戶權限"]。


.關於此任務
對於任何現有的流量分類策略，您可以查看負載平衡器服務的指標，以確定該策略是否成功限制了整個網路的流量。圖表中的數據可以幫助您確定是否需要調整策略。

即使沒有為流量分類策略設定限制，也會收集指標，圖表可以提供有用的資訊來了解流量趨勢。

.步驟
. 選擇*配置* > *網路* > *流量分類*。
+
出現「流量分類策略」頁面，並在表格中列出現有策略。

. 選擇要查看其指標的流量分類策略名稱。
. 選擇“*Metrics*”選項卡。
+
出現流量分類策略圖表。圖表僅顯示與所選策略相符的流量的指標。

+
此頁麵包含以下圖表。

+
** 請求率：此圖表提供所有負載平衡器處理的符合此策略的頻寬量。接收到的資料包括所有請求的請求標頭以及包含正文資料的回應的正文資料大小。已發送包括所有請求的回應標頭以及回應中包含正文資料的請求的回應正文資料大小。
+

NOTE: 當請求完成時，此圖表僅顯示頻寬使用量。對於緩慢或較大的物件請求，實際瞬時頻寬可能與此圖中報告的值不同。

** 錯誤回應率：此圖表提供與此策略相符的請求向客戶端傳回錯誤（HTTP 狀態碼 >= 400）的大致速率。
** 平均請求持續時間（非錯誤）：此圖表提供符合此策略的成功請求的平均持續時間。
** 策略頻寬使用量：此圖表提供所有負載平衡器處理的與此策略相符的頻寬量。接收到的資料包括所有請求的請求標頭以及包含正文資料的回應的正文資料大小。已發送包括所有請求的回應標頭以及回應中包含正文資料的請求的回應正文資料大小。


. 將遊標放在折線圖上即可查看圖表特定部分的彈出值。
. 選擇「Metrics」標題正下方的「Grafana dashboard」來查看策略的所有圖表。除了「*Metrics*」標籤中的四個圖表之外，您還可以查看另外兩個圖表：
+
** 依物件大小的寫入請求率：符合此策略的 PUT/POST/DELETE 請求的速率。單一單元格上的定位顯示每秒的速率。懸停視圖中顯示的速率將被截斷為整數計數，並且當儲存桶中有非零請求時可能會報告 0。
** 依物件大小讀取請求率：符合此策略的 GET/HEAD 請求的速率。單一單元格上的定位顯示每秒的速率。懸停視圖中顯示的速率將被截斷為整數計數，並且當儲存桶中有非零請求時可能會報告 0。


. 或者，從*SUPPORT*選單存取圖表。
+
.. 選擇*支援* > *工具* > *指標*。
.. 從 *Grafana* 部分選擇 *流量分類策略*。
.. 從頁面左上角的選單中選擇策略。
.. 將遊標放在圖表上即可看到彈出窗口，其中顯示樣本的日期和時間、聚合到計數中的物件大小以及該時間段內每秒的請求數。
+
流量分類策略透過其 ID 來識別。策略 ID 列在流量分類策略頁面上。



. 分析圖表以確定策略限制流量的頻率以及是否需要調整策略。

