---
permalink: s3/object-versioning.html 
sidebar: sidebar 
keywords: object version, object versioning 
summary: 如果您想要保留物件的多個版本，可以設定儲存桶的版本控制狀態。啟用儲存桶的版本控制有助於防止意外刪除對象，並使您能夠檢索和還原對象的早期版本。 
---
= 物件版本控制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想要保留每個物件的多個版本，您可以設定儲存桶的版本控制狀態。啟用儲存桶的版本控制有助於防止意外刪除對象，並使您能夠檢索和還原對象的早期版本。

StorageGRID系統實現了版本控制，支援大多數功能，但也有一些限制。  StorageGRID支援每個物件最多 10,000 個版本。

物件版本控制可以與StorageGRID資訊生命週期管理 (ILM) 或 S3 儲存桶生命週期配置結合。您必須明確啟用每個儲存桶的版本控制。當為儲存桶啟用版本控制時，新增至儲存桶的每個物件都會被指派一個版本 ID，該 ID 由StorageGRID系統產生。

不支援使用 MFA（多因素身份驗證）刪除。


NOTE: 僅可在使用StorageGRID版本 10.3 或更高版本建立的儲存桶上啟用版本控制。



== ILM 和版本控制

ILM 策略適用於物件的每個版本。 ILM 掃描過程會持續掃描所有物件並根據目前 ILM 策略重新評估它們。您對 ILM 策略所做的任何變更都將套用於所有先前攝取的物件。如果啟用了版本控制，這包括先前攝取的版本。  ILM 掃描將新的 ILM 變更套用至先前擷取的物件。

對於啟用版本控制的儲存桶中的 S3 對象，版本控制支援可讓您建立使用“非目前時間”作為參考時間的 ILM 規則（對於“僅將此規則應用於較舊的對象版本？”問題，選擇“是”link:../ilm/create-ilm-rule-enter-details.html["建立 ILM 規則精靈的第 1 步"] ）。當物件更新時，其先前版本將變為非目前版本。使用「非當前時間」篩選器可讓您建立減少物件先前版本儲存影響的策略。


NOTE: 當您使用分段上傳作業上傳物件的新版本時，物件原始版本的非當前時間反映的是新版本的分段上傳的建立時間，而不是分段上傳的完成時間。在有限的情況下，原始版本的非當前時間可能比目前版本的時間早幾小時或幾天。

.相關資訊
* link:../ilm/how-objects-are-deleted.html#delete-s3-versioned-objects["如何刪除 S3 版本控制對象"]
* link:../ilm/example-4-ilm-rules-and-policy-for-s3-versioned-objects.html["S3 版本化物件的 ILM 規則和策略（範例 4）"] 。

