---
permalink: s3/post-object-restore.html 
sidebar: sidebar 
keywords: post, RestoreObject, object 
summary: 您可以使用 S3 RestoreObject 請求來還原儲存在雲端儲存池中的物件。 
---
= 復原對象
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 S3 RestoreObject 請求來還原儲存在雲端儲存池中的物件。



== 支援的請求類型

StorageGRID僅支援 RestoreObject 請求來還原物件。它不支援 `SELECT`修復類型。選擇請求返回 `XNotImplemented`。



== 版本控制

（可選）指定 `versionId`還原受版本控制的儲存桶中物件的特定版本。如果你沒有指定 `versionId`，該物件的最新版本已恢復



== RestoreObject 在雲端儲存池物件上的行為

如果一個物件被儲存在link:../ilm/what-cloud-storage-pool-is.html["雲端儲存池"]，根據物件的狀態，RestoreObject 請求具有以下行為。看link:head-object.html["頭部對象"]了解更多詳情。


NOTE: 如果物件儲存在雲端儲存池中，且該物件的一個或多個副本也存在於網格上，則無需透過發出 RestoreObject 請求來還原該物件。相反，可以使用 GetObject 請求直接檢索本機副本。

[cols="1a,2a"]
|===
| 物體狀態 | RestoreObject 的行為 


 a| 
物件已匯入StorageGRID但尚未由 ILM 評估，或物件不在雲端儲存池中
 a| 
`403 Forbidden` ，  `InvalidObjectState`



 a| 
物件位於雲端儲存池中，但尚未轉換為不可檢索狀態
 a| 
`200 OK`沒有做出任何改變。

*注意*：在物件轉換為不可檢索狀態之前，您無法變更其 `expiry-date`。



 a| 
物件已轉換為不可檢索狀態
 a| 
`202 Accepted`將物件的可檢索副本還原到雲端儲存池，保留天數為請求正文中指定的天數。在此期限結束時，物件將返回到不可檢索的狀態。

或者，使用 `Tier`請求元素來決定還原作業需要多長時間才能完成(`Expedited`， `Standard` ， 或者 `Bulk`）。如果你沒有指定 `Tier`， 這 `Standard`層被使用。

*重要*：如果物件已轉換到 S3 Glacier Deep Archive 或雲端儲存池使用 Azure Blob 存儲，則無法使用 `Expedited`層。傳回以下錯誤 `403 Forbidden`， `InvalidTier` ： `Retrieval option is not supported by this storage class` 。



 a| 
物件正在從不可恢復狀態恢復
 a| 
`409 Conflict` ，  `RestoreAlreadyInProgress`



 a| 
物件已完全恢復到雲端儲存池
 a| 
`200 OK`

*注意：*如果物件已恢復到可檢索狀態，您可以變更其 `expiry-date`透過重新發出 RestoreObject 請求並使用新值 `Days`。恢復日期根據請求的時間進行更新。

|===