---
permalink: s3/upload-part-copy.html 
sidebar: sidebar 
keywords: UploadPart, UploadPartCopy, multipart uploads, uploads, 
summary: UploadPartCopy 操作透過從現有物件作為資料來源複製資料來上傳物件的一部分。 
---
= 上傳部分複製
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
UploadPartCopy 操作透過從現有物件作為資料來源複製資料來上傳物件的一部分。

UploadPartCopy 操作是透過所有 Amazon S3 REST API 行為實現的。如有變更，恕不另行通知。

此請求讀取並寫入指定的物件數據 `x-amz-copy-source-range`在StorageGRID系統內。

支援以下請求標頭：

* `x-amz-copy-source-if-match`
* `x-amz-copy-source-if-none-match`
* `x-amz-copy-source-if-unmodified-since`
* `x-amz-copy-source-if-modified-since`




== 伺服器端加密的請求標頭

如果您為 CreateMultipartUpload 要求指定了 SSE-C 加密，則也必須在每個 UploadPartCopy 請求中包含以下請求標頭：

* `x-amz-server-side-encryption-customer-algorithm`： 指定 `AES256`。
* `x-amz-server-side-encryption-customer-key`：指定您在 CreateMultipartUpload 請求中提供的相同加密金鑰。
* `x-amz-server-side-encryption-customer-key-MD5`：指定您在 CreateMultipartUpload 請求中提供的相同 MD5 摘要。


如果來源物件使用客戶提供的金鑰（SSE-C）加密，則必須在 UploadPartCopy 請求中包含以下三個標頭，以便可以解密然後複製物件：

* `x-amz-copy-source​-server-side​-encryption​-customer-algorithm`： 指定 `AES256`。
* `x-amz-copy-source​-server-side-encryption-customer-key`：指定您在建立來源物件時提供的加密金鑰。
* `x-amz-copy-source​-server-side-encryption-customer-key-MD5`：指定您在建立來源物件時提供的 MD5 摘要。



CAUTION: 您提供的加密金鑰永遠不會被儲存。如果遺失了加密金鑰，您就會遺失對應的物件。在使用客戶提供的金鑰保護物件資料之前，請先查看link:using-server-side-encryption.html["使用伺服器端加密"]。



== 版本控制

分段上傳包括啟動上傳、列出上傳、上傳部分、組裝上傳部分和完成上傳的單獨操作。執行 CompleteMultipartUpload 作業時會建立物件（如果適用，也會進行版本控制）。
