---
permalink: monitor/configuring-snmp-agent.html 
sidebar: sidebar 
keywords: snmp agent, mib, trap, inform 
summary: 您可以設定StorageGRID SNMP 代理程式以使用第三方 SNMP 管理系統進行唯讀 MIB 存取和通知。 
---
= 設定 SNMP 代理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定StorageGRID SNMP 代理程式以使用第三方 SNMP 管理系統進行唯讀 MIB 存取和通知。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 你有link:../admin/admin-group-permissions.html["Root存取權限"]。


.關於此任務
StorageGRID SNMP 代理程式支援 SNMPv1、SNMPv2c 和 SNMPv3。您可以為一個或多個版本配置代理程式。對於 SNMPv3，僅支援使用者安全模型 (USM) 驗證。

網格中的所有節點都使用相同的 SNMP 配置。



== 指定基本配置

第一步，啟用StorageGRID SMNP 代理並提供基本資訊。

.步驟
. 選擇 *設定* > *監控* > *SNMP 代理程式*。
+
出現 SNMP 代理頁面。

. 若要在所有網格節點上啟用 SNMP 代理，請勾選「啟用 SNMP」複選框。
. 在基本配置部分輸入以下資訊。
+
[cols="1a,2a"]
|===
| 場地 | 描述 


 a| 
系統聯絡人
 a| 
選修的。  StorageGRID系統的主要聯絡人，在 SNMP 訊息中以 sysContact 的形式傳回。

系統聯絡人通常是一個電子郵件地址。此值適用於StorageGRID系統中的所有節點。  *系統聯絡人*最多可包含 255 個字元。



 a| 
系統位置
 a| 
選修的。  StorageGRID系統的位置，在 SNMP 訊息中以 sysLocation 的形式傳回。

系統位置可以是任何有助於識別StorageGRID系統所在位置的資訊。例如，您可以使用設施的街道地址。此值適用於StorageGRID系統中的所有節點。  *系統位置*最多可包含 255 個字元。



 a| 
啟用 SNMP 代理程式通知
 a| 
** 如果選擇此選項， StorageGRID SNMP 代理程式將發送陷阱和通知。
** 如果未選擇，SNMP 代理程式支援唯讀 MIB 訪問，但不會發送任何 SNMP 通知。




 a| 
啟用身份驗證陷阱
 a| 
如果選擇此選項， StorageGRID SNMP 代理程式將在收到未正確驗證的協定訊息時傳送身份驗證陷阱。

|===




== 輸入社區字串

如果您使用 SNMPv1 或 SNMPv2c，請完成社群字串部分。

當管理系統查詢StorageGRID MIB 時，它會傳送一個社群字串。如果社群字串與此處指定的某個值匹配，則 SNMP 代理程式會向管理系統發送回應。

.步驟
. 對於*唯讀社群*，可選擇輸入社群字串以允許在 IPv4 和 IPv6 代理位址上進行唯讀 MIB 存取。
+

TIP: 為了確保StorageGRID系統的安全，請不要使用「public」作為社群字串。如果將此欄位留空，SNMP 代理程式將使用StorageGRID系統的網格 ID 作為社群字串。

+
每個社區字串最多可以有 32 個字符，且不能包含空格字符。

. 選擇*新增另一個社區字串*來新增其他字串。
+
最多允許五個字串。





== [[select_trap_destination]]建立陷阱目的地

使用「其他配置」部分中的「陷阱目標」標籤來定義StorageGRID陷阱或通知通知的一個或多個目標。當您啟用 SNMP 代理程式並選擇 *儲存* 時， StorageGRID會在觸發警報時向每個定義的目的地發送通知。也會為支援的 MIB-II 實體（例如，ifDown 和 coldStart）發送標準通知。

.步驟
. 對於 *預設陷阱社群* 字段，可選擇輸入要用於 SNMPv1 或 SNMPv2 陷阱目標的預設社群字串。
+
根據需要，您可以在定義特定的陷阱目標時提供不同的（「自訂」）社群字串。

+
*預設陷阱社群*最多可以包含 32 個字符，且不能包含空格字符。

. 若要新增陷阱目標，請選擇*創建*。
. 選擇將用於此陷阱目標的 SNMP 版本。
. 完成您所選版本的「建立陷阱目標」表單。
+
[role="tabbed-block"]
====
.SNMPv1
--
如果您選擇 SNMPv1 作為版本，請填寫這些欄位。

[cols="1a,2a"]
|===
| 場地 | 描述 


 a| 
類型
 a| 
對 SNMPv1 來說必須是 Trap。



 a| 
主持人
 a| 
用於接收陷阱的 IPv4 或 IPv6 位址或完全限定網域名稱 (FQDN)。



 a| 
港口
 a| 
使用 162，這是 SNMP 陷阱的標準端口，除非您必須使用其他值。



 a| 
協定
 a| 
使用 UDP，它是標準 SNMP 陷阱協議，除非您需要使用 TCP。



 a| 
社區字串
 a| 
如果指定了，則使用預設陷阱社區，或為此陷阱目標輸入自訂社區字串。

自訂社區字串最多可以有 32 個字符，且不能包含空格。

|===
--
.SNMPv2c
--
如果您選擇 SNMPv2c 作為版本，請填寫這些欄位。

[cols="1a,2a"]
|===
| 場地 | 描述 


 a| 
類型
 a| 
目的地是否用於陷阱或通知。



 a| 
主持人
 a| 
用於接收陷阱的 IPv4 或 IPv6 位址或 FQDN。



 a| 
港口
 a| 
使用 162，這是 SNMP 陷阱的標準端口，除非您必須使用其他值。



 a| 
協定
 a| 
使用 UDP，它是標準 SNMP 陷阱協議，除非您需要使用 TCP。



 a| 
社區字串
 a| 
如果指定了，則使用預設陷阱社區，或為此陷阱目標輸入自訂社區字串。

自訂社區字串最多可以有 32 個字符，且不能包含空格。

|===
--
.SNMPv3
--
如果您選擇 SNMPv3 作為版本，請填寫這些欄位。

[cols="1a,2a"]
|===
| 場地 | 描述 


 a| 
類型
 a| 
目的地是否用於陷阱或通知。



 a| 
主持人
 a| 
用於接收陷阱的 IPv4 或 IPv6 位址或 FQDN。



 a| 
港口
 a| 
使用 162，這是 SNMP 陷阱的標準端口，除非您必須使用其他值。



 a| 
協定
 a| 
使用 UDP，它是標準 SNMP 陷阱協議，除非您需要使用 TCP。



 a| 
USM 用戶
 a| 
將用於身份驗證的 USM 使用者。

** 如果您選擇了 *Trap*，則僅顯示沒有權威引擎 ID 的 USM 使用者。
** 如果您選擇了*通知*，則僅顯示具有權威引擎 ID 的 USM 使用者。
** 如果沒有顯示使用者：
+
... 創建並保存陷阱目的地。
... 前往<<create-usm-users,建立 USM 用戶>>並創建用戶。
... 返回「陷阱目標」標籤，從表格中選擇已儲存的目標，然後選擇「*編輯*」。
... 選擇用戶。




|===
--
====
. 選擇“*創建*”。
+
陷阱目標已建立並新增至表中。





== 建立代理地址

或者，使用其他配置部分中的代理程式位址標籤指定一個或多個「監聽位址」。這些是 SNMP 代理程式可以接收查詢的StorageGRID位址。

如果您未設定代理位址，則所有StorageGRID網路上的預設監聽位址為 UDP 連接埠 161。

.步驟
. 選擇“*創建*”。
. 輸入以下資訊。
+
[cols="1a,2a"]
|===
| 場地 | 描述 


 a| 
網際網路協定
 a| 
此位址是否使用 IPv4 或 IPv6。

預設情況下，SNMP 使用 IPv4。



 a| 
傳輸協定
 a| 
此位址是否使用 UDP 或 TCP。

預設情況下，SNMP 使用 UDP。



 a| 
StorageGRID網路
 a| 
代理將監聽哪個StorageGRID網路。

** 網格、管理和客戶端網路：SNMP 代理程式將監聽所有三個網路上的查詢。
** 網格網絡
** 管理網路
** 客戶網路
+
*注意*：如果您使用客戶端網路傳輸不安全的數據，並為客戶端網路建立代理位址，請注意 SNMP 流量也將不安全。





 a| 
港口
 a| 
可選，SNMP 代理應監聽的連接埠號碼。

SNMP 代理程式的預設 UDP 連接埠是 161，但您可以輸入任何未使用的連接埠號碼。

*注意*：當您儲存 SNMP 代理程式時， StorageGRID會自動在內部防火牆上開啟代理位址連接埠。您必須確保任何外部防火牆都允許存取這些連接埠。

|===
. 選擇“*創建*”。
+
代理地址已建立並新增至表中。





== [[create-usm-users]]建立 USM 用戶

如果您使用的是 SNMPv3，請使用其他設定部分中的 USM 使用者標籤來定義有權查詢 MIB 或接收陷阱和通知的 USM 使用者。


NOTE: SNMPv3 _inform_ 目的地必須具有具有引擎 ID 的使用者。  SNMPv3 _trap_ 目標不能擁有具有引擎 ID 的使用者。

如果您僅使用 SNMPv1 或 SNMPv2c，則這些步驟不適用。

.步驟
. 選擇“*創建*”。
. 輸入以下資訊。
+
[cols="1a,2a"]
|===
| 場地 | 描述 


 a| 
使用者名稱
 a| 
此 USM 使用者的唯一名稱。

使用者名稱最多可以有 32 個字符，且不能包含空格字符。用戶建立後，用戶名不能更改。



 a| 
只讀 MIB 訪問
 a| 
如果選擇，該使用者應該具有 MIB 的唯讀存取權限。



 a| 
權威引擎ID
 a| 
如果此使用者將在通知目的地中使用，則為該使用者的權威引擎 ID。

輸入 10 到 64 個十六進位字元（5 到 32 個位元組），中間不帶空格。對於將在陷阱目的地中選擇以進行通知的 USM 用戶，此值是必需的。對於將在陷阱目標中選擇的 USM 用戶，不允許使用此值。

*注意*：如果您選擇了*只讀 MIB 存取*，則不會顯示此字段，因為具有唯讀 MIB 存取權限的 USM 使用者不能擁有引擎 ID。



 a| 
安全等級
 a| 
USM 用戶的安全等級：

** *authPriv*：此使用者透過身分驗證和隱私（加密）進行通訊。您必須指定身份驗證協定和密碼以及隱私權協議和密碼。
** *authNoPriv*：此使用者透過身分驗證進行通信，但不進行隱私（無加密）。您必須指定身份驗證協定和密碼。




 a| 
身份驗證協議
 a| 
始終設定為 SHA，這是唯一支援的協定（HMAC-SHA-96）。



 a| 
密碼
 a| 
該用戶將用於身份驗證的密碼。



 a| 
隱私協議
 a| 
僅當您選擇 *authPriv* 並始終設定為 AES（這是唯一支援的隱私協定）時才顯示。



 a| 
密碼
 a| 
僅當您選擇 *authPriv* 時才顯示。該用戶將使用的密碼以保護隱私。

|===
. 選擇“*創建*”。
+
USM 使用者已建立並新增至表中。

. 完成 SNMP 代理程式配置後，選擇*儲存*。
+
新的 SNMP 代理程式配置將生效。


