---
permalink: monitor/monitoring-load-balancing-operations.html 
sidebar: sidebar 
keywords: load balancing, monitoring 
summary: 如果您使用負載平衡器來管理與StorageGRID 的用戶端連接，則應在初始設定係統後以及進行任何設定變更或執行擴充後監控負載平衡操作。 
---
= 監控負載平衡操作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用負載平衡器來管理與StorageGRID 的用戶端連接，則應在初始設定係統後以及進行任何設定變更或執行擴充後監控負載平衡操作。

.關於此任務
您可以使用管理節點或網關節點上的負載平衡器服務或外部第三方負載平衡器在多個儲存節點之間指派用戶端請求。

配置負載平衡後，您應該確認物件擷取和檢索操作在儲存節點之間均勻分佈。均勻分佈的請求可確保StorageGRID在負載下仍能回應用戶端請求，並有助於維持用戶端效能。

如果您以主動-備援模式設定了網關節點或管理節點的高可用性 (HA) 群組，則群組中只有一個節點主動分發用戶端要求。

有關更多信息，請參閱link:../admin/configuring-client-connections.html["配置 S3 用戶端連接"] 。

.步驟
. 如果 S3 用戶端使用負載平衡器服務進行連接，請檢查管理節點或網關節點是否按預期主動分配流量：
+
.. 選擇*NODES*。
.. 選擇網關節點或管理節點。
.. 在「*概述*」標籤上，檢查節點介面是否位於 HA 群組中，以及節點介面是否具有主介面角色。
+
具有主角色的節點和不屬於 HA 群組的節點應該主動向客戶端分發請求。

.. 對於應該主動分發客戶端請求的每個節點，選擇link:viewing-load-balancer-tab.html["負載平衡器選項卡"]。
.. 查看過去一週的負載平衡器請求流量圖表，以確保節點一直在主動分發請求。
+
主動-備份 HA 群組中的節點可能不時承擔備份角色。在此期間，節點不會分發客戶端請求。

.. 查看上週負載平衡器傳入請求率圖表，以查看節點的物件吞吐量。
.. 對StorageGRID系統中的每個管理節點或網關節點重複這些步驟。
.. 或者，使用流量分類策略來查看負載平衡器服務所服務的流量的更詳細分析。


. 驗證這些請求是否均勻分佈到儲存節點。
+
.. 選擇 *_Storage Node_* > *LDR* > *HTTP*。
.. 查看*目前已建立的傳入會話*的數量。
.. 對網格中的每個儲存節點重複此操作。
+
所有儲存節點的會話數量應大致相等。




