---
permalink: monitor/monitoring-information-lifecycle-management.html 
sidebar: sidebar 
keywords: lifecycle management, lifecycle, monitoring, ILM, information lifecycle management 
summary: 資訊生命週期管理（ILM）系統為網格上儲存的所有物件提供資料管理。您必須監控 ILM 操作以了解網格是否可以處理目前負載，或者是否需要更多資源。 
---
= 監控資訊生命週期管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
資訊生命週期管理（ILM）系統為電網上儲存的所有物件提供資料管理。您必須監控 ILM 操作以了解網格是否可以處理目前負載，或者是否需要更多資源。

.關於此任務
StorageGRID系統透過應用活動的 ILM 策略來管理物件。  ILM 策略和相關的 ILM 規則決定了要製作多少份副本、建立的副本類型、副本的放置位置以及每個副本的保留時間長度。

物件攝取和其他物件相關活動可能超過StorageGRID評估 ILM 的速度，導致系統將無法近乎即時地完成 ILM 放置指令的物件排隊。您應該監控StorageGRID是否跟上客戶端的操作。



== 使用網格管理器儀表板選項卡

.步驟
使用網格管理器儀表板上的 ILM 標籤來監視 ILM 操作：

. Sign in入網格管理器。
. 從儀表板中，選擇 ILM 標籤並記下 ILM 佇列（物件）卡和 ILM 評估率卡上的值。
+
預計儀表板上的 ILM 佇列（物件）卡會出現暫時的峰值。但是，如果佇列持續增加且不減少，則網格需要更多資源才能有效運作：要么是更多儲存節點，要么是更多網路頻寬（如果 ILM 策略將物件放置在遠端位置）。





== 使用 NODES 頁面

.步驟
此外，使用 *NODES* 頁面調查 ILM 佇列：


NOTE: 在未來的StorageGRID版本中，*NODES* 頁面上的圖表將被對應的儀表闆卡取代。

. 選擇*NODES*。
. 選擇*_grid name_* > *ILM*。
. 將遊標放在 ILM 佇列圖上，查看給定時間點的以下屬性的值：
+
** *排隊的物件（來自客戶端操作）*：由於客戶端操作（例如，攝取）而等待 ILM 評估的物件總數。
** *排隊的物件（來自所有操作）*：等待 ILM 評估的物件總數。
** *掃描速率（物件/秒）*：掃描網格中的物件並將其排隊等待 ILM 的速率。
** *評估率（物件/秒）*：目前根據網格中的 ILM 策略評估物件的速率。


. 在 ILM 佇列部分，查看以下屬性。
+

NOTE: ILM 佇列部分僅包含在網格中。此資訊不會顯示在網站或儲存節點的 ILM 標籤上。

+
** *掃描週期 - 估計值*：完成所有物件的完整 ILM 掃描的估計時間。
+

NOTE: 全面掃描並不能保證 ILM 已套用於所有物件。

** *嘗試修正*：已嘗試的複製資料的物件修復操作總數。每次儲存節點嘗試修復高風險物件時，此計數都會增加。如果電網變得繁忙，則優先進行高風險的 ILM 修復。
+

NOTE: 如果修復後複製失敗，則相同物件修復可能會再次增加。



+
當您監控儲存節點磁碟區復原的進度時，這些屬性非常有用。如果嘗試修復的次數停止增加並且完整掃描已完成，則修復可能已完成。


