---
permalink: monitor/updating-snmp-agent.html 
sidebar: sidebar 
keywords: how to update the SNMP agent 
summary: 您可以停用 SNMP 通知、更新社群字串，或新增或刪除代理程式地址、USM 使用者和陷阱目的地。 
---
= 更新 SNMP 代理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以停用 SNMP 通知、更新社群字串，或新增或刪除代理程式地址、USM 使用者和陷阱目的地。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 你有link:../admin/admin-group-permissions.html["Root存取權限"]。


.關於此任務
看link:configuring-snmp-agent.html["設定 SNMP 代理"]有關 SNMP 代理頁面上每個欄位的詳細資訊。您必須選擇頁面底部的“*儲存*”才能提交在每個標籤上所做的任何變更。

.步驟
. 選擇 *設定* > *監控* > *SNMP 代理程式*。
+
出現 SNMP 代理頁面。

. 若要停用所有網格節點上的 SNMP 代理，請清除 *啟用 SNMP* 複選框，然後選擇 *儲存*。
+
如果重新啟用 SNMP 代理，則任何先前的 SNMP 設定設定都會保留。

. 或者，更新基本配置部分中的資訊：
+
.. 根據需要，更新*系統聯絡人*和*系統位置*。
.. 或者，勾選或清除「啟用 SNMP 代理通知」複選框來控制StorageGRID SNMP 代理程式是否發送陷阱和通知通知。
+
清除此複選框後，SNMP 代理程式支援唯讀 MIB 訪問，但不發送 SNMP 通知。

.. 或者，勾選或清除「啟用身份驗證陷阱」複選框，以控制StorageGRID SNMP 代理程式在收到未正確驗證的協定訊息時是否發送身份驗證陷阱。


. 如果您使用 SNMPv1 或 SNMPv2c，則可以選擇在社群字串部分更新或新增 *只讀社群*。
. 若要更新陷阱目標，請選擇「其他配置」部分中的「陷阱目標」標籤。
+
使用此選項卡可以定義StorageGRID陷阱或通知通知的一個或多個目標。當您啟用 SNMP 代理程式並選擇 *儲存* 時， StorageGRID會在觸發警報時向每個定義的目的地發送通知。也會為支援的 MIB-II 實體（例如，ifDown 和 coldStart）發送標準通知。

+
有關輸入內容的詳細信息，請參閱link:../monitor/configuring-snmp-agent.html#create-trap-destinations["創建陷阱目的地"]。

+
** 或者，更新或刪除預設陷阱社群。
+
如果刪除預設陷阱社區，則必須先確保任何現有的陷阱目標都使用自訂社區字串。

** 若要新增陷阱目標，請選擇*創建*。
** 若要編輯陷阱目標，請選擇單選按鈕，然後選擇*編輯*。
** 若要刪除陷阱目標，請選擇單選按鈕，然後選擇*刪除*。
** 若要提交您的更改，請選擇頁面底部的“*儲存*”。


. 若要更新代理地址，請選擇其他配置部分中的代理地址標籤。
+
使用此選項卡可以指定一個或多個「監聽位址」。這些是 SNMP 代理程式可以接收查詢的StorageGRID位址。

+
有關輸入內容的詳細信息，請參閱link:../monitor/configuring-snmp-agent.html#create-agent-addresses["建立代理地址"]。

+
** 若要新增代理地址，請選擇*建立*。
** 若要編輯代理位址，請選擇單選按鈕，然後選擇*編輯*。
** 若要刪除代理地址，請選擇單選按鈕，然後選擇*刪除*。
** 若要提交您的更改，請選擇頁面底部的“*儲存*”。


. 若要更新 USM 用戶，請選擇「其他配置」部分中的「USM 用戶」標籤。
+
使用此標籤定義有權查詢 MIB 或接收陷阱和通知的 USM 使用者。

+
有關輸入內容的詳細信息，請參閱link:../monitor/configuring-snmp-agent.html#create-usm-users["建立 USM 用戶"]。

+
** 若要新增 USM 用戶，請選擇 *建立*。
** 若要編輯 USM 用戶，請選擇單選按鈕，然後選擇 *編輯*。
+
現有 USM 用戶的用戶名無法更改。如果您需要更改用戶名，則必須刪除該用戶並建立新用戶。

+

NOTE: 如果您新增或刪除使用者的權威引擎 ID，且該使用者目前被選為目標，則必須編輯或刪除該目標。否則，儲存 SNMP 代理程式設定時會出現驗證錯誤。

** 若要刪除 USM 用戶，請選擇單選按鈕，然後選擇 *刪除*。
+

NOTE: 如果您刪除的使用者目前被選為陷阱目標，則必須編輯或刪除該目標。否則，儲存 SNMP 代理程式設定時會出現驗證錯誤。

** 若要提交您的更改，請選擇頁面底部的“*儲存*”。


. 更新 SNMP 代理程式配置後，選擇*儲存*。

