---
permalink: maintain/configuring-ip-addresses.html 
sidebar: sidebar 
keywords: configure ip address, change IP tool, ethernet, dhcp, ha group 
summary: 您可以使用變更 IP 工具為網格節點配置 IP 位址來執行網路配置。 
---
= IP 位址指南
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用變更 IP 工具為網格節點配置 IP 位址來執行網路配置。

您必須使用變更 IP 工具對網格部署期間最初設定的網路配置進行大部分變更。使用標準 Linux 網路命令和檔案進行的手動變更可能不會傳播到所有StorageGRID服務，並且可能不會在升級、重新啟動或節點復原過程中持續存在。


NOTE: IP 變更過程可能是一個破壞性的過程。在套用新配置之前，部分網格可能無法使用。


NOTE: 如果您僅對網格網路子網路清單進行更改，請使用網格管理器新增或變更網路配置。否則，如果由於網路配置問題而無法存取網格管理器，或者您同時執行網格網路路由變更和其他網路更改，請使用變更 IP 工具。


TIP: 如果要變更網格中所有節點的網格網路 IP 位址，請使用link:changing-ip-addresses-and-mtu-values-for-all-nodes-in-grid.html["電網範圍變更的特殊程序"]。



== 乙太網路介面

指派給 eth0 的 IP 位址始終是網格節點的網格網路 IP 位址。指派給 eth1 的 IP 位址始終是網格節點的管理網路 IP 位址。指派給 eth2 的 IP 位址始終是網格節點的客戶端網路 IP 位址。

請注意，在某些平台（例如StorageGRID設備）上，eth0、eth1 和 eth2 可能是由從屬網橋或實體或 VLAN 介面的綁定組成的聚合介面。在這些平台上，*SSM* > *資源* 標籤可能顯示除 eth0、eth1 或 eth2 之外分配給其他介面的網格、管理和用戶端網路 IP 位址。



== DHCP

您只能在部署階段設定 DHCP。您無法在設定期間設定 DHCP。如果要變更網格節點的 IP 位址、子網路遮罩和預設網關，則必須使用 IP 位址變更程式。使用變更 IP 工具將導致 DHCP 位址變為靜態。



== 高可用性 (HA) 組

* 如果用戶端網路介麵包含在 HA 群組中，則無法將該介面的用戶端網路 IP 位址變更為該 HA 群組配置的子網路之外的位址。
* 您無法將用戶端網路 IP 位址變更為指派給用戶端網路介面上設定的 HA 群組的現有虛擬 IP 位址的值。
* 如果 Grid 網路介麵包含在 HA 群組中，則無法將該介面的 Grid 網路 IP 位址變更為 HA 群組配置的子網路之外的位址。
* 您無法將網格網路 IP 位址變更為指派給網格網路介面上配置的 HA 群組的現有虛擬 IP 位址的值。

