---
permalink: maintain/configuring-ntp-servers.html 
sidebar: sidebar 
keywords: storagegrid, ntp, ntp server, configure ntp, configuring ntp 
summary: '您可以新增、更新或刪除網路時間協定 (NTP) 伺服器，以確保StorageGRID系統中的網格節點之間資料準確同步。' 
---
= 管理 NTP 伺服器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以新增、更新或刪除網路時間協定 (NTP) 伺服器，以確保StorageGRID系統中的網格節點之間資料準確同步。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 你有link:../admin/admin-group-permissions.html["維護或 Root 存取權限"]。
* 您有配置密碼。
* 您需要設定 NTP 伺服器的 IPv4 位址。




== StorageGRID如何使用 NTP

StorageGRID系統使用網路時間協定 (NTP) 來同步網格中所有網格節點之間的時間。

在每個站點， StorageGRID系統中至少有兩個節點被指派主要 NTP 角色。它們與建議的最少四個、最多六個外部時間源同步，並且彼此之間也同步。  StorageGRID系統中每個非主 NTP 節點都充當 NTP 用戶端並與這些主 NTP 節點同步。

外部 NTP 伺服器連線到您先前指派了主要 NTP 角色的節點。因此，建議指定至少兩個具有主要 NTP 角色的節點。



== NTP 伺服器指南

請遵循以下準則來防止時序問題：

* 外部 NTP 伺服器連線到您先前指派了主要 NTP 角色的節點。因此，建議指定至少兩個具有主要 NTP 角色的節點。
* 確保每個站點至少有兩個節點可以存取至少四個外部 NTP 來源。如果網站中只有一個節點可以存取 NTP 來源，則當節點發生故障時就會出現計時問題。此外，如果站點與電網的其餘部分隔離，則為每個站點指定兩個節點為主要 NTP 來源可確保準確的計時。
* 指定的外部 NTP 伺服器必須使用 NTP 協定。您必須指定 Stratum 3 或更高層級的 NTP 伺服器參考，以防止時間漂移問題。



NOTE: 為生產級StorageGRID安裝指定外部 NTP 來源時，請勿在早於 Windows Server 2016 的 Windows 版本上使用 Windows 時間 (W32Time) 服務。早期版本的 Windows 上的時間服務不夠準確，且 Microsoft 不支援在高精確度環境（包括StorageGRID）中使用。有關詳細信息，請參閱 https://support.microsoft.com/en-us/help/939322/support-boundary-to-configure-the-windows-time-service-for-high-accura["支援邊界以配置 Windows 時間服務以實現高精度環境"^]。



== 配置 NTP 伺服器

請依照下列步驟新增、更新或刪除 NTP 伺服器。

.步驟
. 選擇 *維護* > *網路* > *NTP 伺服器*。
. 在伺服器部分，根據需要新增、更新或刪除 NTP 伺服器條目。
+
您應該至少包含四個 NTP 伺服器，並且最多可以指定六個伺服器。

. 輸入您的StorageGRID系統的設定密碼，然後選擇*儲存*。
+
該頁面將被停用，直到配置更新完成。

+

NOTE: 如果在儲存新的 NTP 伺服器後所有 NTP 伺服器均未通過連線測試，請不要繼續。聯繫技術支援。





== 解決 NTP 伺服器問題

如果您在安裝期間最初指定的 NTP 伺服器的穩定性或可用性方面遇到問題，則可以透過新增其他伺服器或更新或刪除現有伺服器來更新StorageGRID系統使用的外部 NTP 來源清單。
