---
permalink: maintain/considerations-for-decommissioning-storage-nodes.html 
sidebar: sidebar 
keywords: storage node decommission, considerations, appliance node clone 
summary: 在退役儲存節點之前，請考慮是否可以克隆該節點。然後，如果您決定退役該節點，請查看StorageGRID在退役過程中如何管理物件和元資料。 
---
= 退役儲存節點的注意事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在退役儲存節點之前，請考慮是否可以克隆該節點。然後，如果您決定退役該節點，請查看StorageGRID在退役過程中如何管理物件和元資料。



== 何時克隆節點而不是停用它

如果您想用更新或更大的設備取代舊設備儲存節點，請考慮複製設備節點，而不是在擴充功能中新增設備，然後停用舊設備。

透過設備節點克隆，您可以輕鬆地在同一StorageGRID站點用相容設備取代現有設備節點。克隆過程將所有資料傳輸到新設備，使新設備投入使用，並使舊設備處於預先安裝狀態。

如果需要，您可以克隆設備節點：

* 更換已達到使用壽命的設備。
* 升級現有節點以利用改良的設備技術。
* 無需改變StorageGRID系統中的儲存節點數量即可增加網格儲存容量。
* 提高儲存效率，例如透過變更 RAID 模式。


看 https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/how-appliance-node-cloning-works.html["設備節點克隆"^]了解詳情。



== 連接儲存節點的注意事項

查看停用已連接儲存節點的注意事項。

* 在單一退役節點流程中，您不應退役超過 10 個儲存節點。
* 系統必須始終包含足夠的儲存節點以滿足操作要求，包括link:understanding-adc-service-quorum.html["ADC 仲裁"]和活躍link:reviewing-ilm-policy-and-storage-configuration.html["ILM 策略"]。為了滿足此限制，您可能需要在擴充功能中新增新的儲存節點，然後才能停用現有的儲存節點。
+
在包含基於軟體的純元資料節點的網格中停用儲存節點時請務必小心。如果您停用所有配置為儲存物件和元資料的節點，則儲存物件的能力將從網格中刪除。看link:../primer/what-storage-node-is.html#types-of-storage-nodes["儲存節點的類型"]有關僅元資料儲存節點的詳細資訊。

* 當您刪除儲存節點時，大量物件資料將透過網路傳輸。雖然這些傳輸不會影響正常的系統操作，但它們會影響StorageGRID系統消耗的網路頻寬總量。
* 與儲存節點退役相關的任務的優先順序低於與正常系統操作相關的任務。這意味著退役不會幹擾正常的StorageGRID系統操作，並且不需要安排在系統不活動期間。由於退役是在後台進行的，因此很難估計該過程需要多長時間才能完成。一般來說，當系統安靜時，或一次只刪除一個儲存節點時，退役會更快完成。
* 停用儲存節點可能需要幾天或幾週的時間。相應地規劃此過程。雖然退役過程旨在不影響系統運行，但它可能會限制其他程式。一般來說，您應該在刪除網格節點之前執行任何計劃的系統升級或擴充。
* 如果在移除儲存節點時需要執行其他維護程序，您可以link:pausing-and-resuming-decommission-process-for-storage-nodes.html["暫停退役程序"]並在其他過程完成後恢復它。
+

NOTE: 只有在達到 ILM 評估或擦除編碼資料退役階段時才會啟用 *暫停* 按鈕；但是，ILM 評估（資料遷移）將繼續在背景執行。

* 當退役任務正在運行時，您無法在任何網格節點上執行資料修復作業。
* 在儲存節點退役期間，您不應對 ILM 策略進行任何變更。
* 若要永久安全地刪除數據，您必須在退役過程完成後擦除儲存節點的磁碟機。




== 斷開連接的儲存節點的注意事項

查看停用已斷開連線的儲存節點的注意事項。

* 切勿停用斷開連接的節點，除非您確定它無法上線或恢復。
+

CAUTION: 如果您認為有可能從節點恢復物件數據，請不要執行此程序。相反，請聯絡技術支援以確定是否可以恢復節點。

* 當您退役斷開連接的儲存節點時， StorageGRID會使用來自其他儲存節點的資料來重建斷開連接的節點上的物件資料和元資料。
* 如果您停用多個斷開連線的儲存節點，則可能會發生資料遺失。如果沒有足夠的物件副本、擦除編碼片段或物件元資料可用，系統可能無法重建資料。當在具有基於軟體的純元資料節點的網格中退役儲存節點時，退役所有配置為儲存物件和元資料的節點將從網格中刪除所有物件儲存。看link:../primer/what-storage-node-is.html#types-of-storage-nodes["儲存節點的類型"]有關僅元資料儲存節點的詳細資訊。
+

CAUTION: 如果您有多個無法恢復的斷開連接的儲存節點，請聯絡技術支援以確定最佳的措施。

* 當您退役已中斷連線的儲存節點時， StorageGRID會在退役程序結束時啟動資料修復作業。這些作業嘗試重建儲存在斷開連接的節點上的物件資料和元資料。
* 當您退役已斷開連線的儲存節點時，退役程序會相對較快完成。然而，資料修復工作可能需要幾天或幾週的時間才能完成，並且不受退役程序的監控。您必須手動監控這些作業並根據需要重新啟動它們。看link:checking-data-repair-jobs.html["檢查資料修復作業"] 。
* 如果您停用包含物件唯一副本的已中斷連線的儲存節點，則該物件將會遺失。只有噹噹前連接的儲存節點上存在至少一個複製副本或足夠的擦除編碼片段時，資料修復作業才能重建和恢復物件。

