---
permalink: maintain/how-site-recovery-is-performed-by-technical-support.html 
sidebar: sidebar 
keywords: storagegrid, site recovery, technical support, tech support 
summary: 如果整個StorageGRID站點發生故障或多個儲存節點發生故障，則必須聯絡技術支援。技術支援將評估您的狀況，制定恢復計劃，然後以滿足您的業務目標、優化恢復時間並防止不必要的資料遺失的方式恢復故障節點或網站。 
---
= 技術支援如何恢復站點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果整個StorageGRID站點發生故障或多個儲存節點發生故障，則必須聯絡技術支援。技術支援將評估您的狀況，制定恢復計劃，然後以滿足您的業務目標、優化恢復時間並防止不必要的資料遺失的方式恢復故障節點或網站。


CAUTION: 站點恢復只能由技術支援執行。

StorageGRID系統能夠抵禦各種故障，您可以自行成功執行許​​多復原和維護程序。然而，建立一個簡單、通用的網站復原程序很困難，因為詳細步驟取決於特定於您情況的因素。例如：

* *您的業務目標*：在StorageGRID網站完全遺失後，您應該評估如何最好地實現您的業務目標。例如，您是否想就地重建遺失的網站？您是否想在新位置替換遺失的StorageGRID網站？每個客戶的情況都不同，您的恢復計劃必須根據您的優先事項進行設計。
* *故障的確切性質*：在開始站點復原之前，確定故障站點上的任何節點是否完好無損，或任何儲存節點是否包含可復原的物件。如果重建包含有效資料的節點或儲存卷，可能會發生不必要的資料遺失。
* *活動的 ILM 策略*：網格中物件副本的數量、類型和位置由活動的 ILM 策略控制。  ILM 策略的具體內容可能會影響可恢復資料的數量以及恢復所需的具體技術。
+

CAUTION: 如果某個網站包含某個物件的唯一副本，而該網站遺失，則該物件也會遺失。

* *儲存桶（或容器）一致性*：應用於儲存桶（或容器）的一致性會影響StorageGRID在告知客戶端物件攝取成功之前是否將物件元資料完全複製到所有節點和網站。如果一致性值允許最終一致性，則某些物件元資料可能會在網站故障中遺失。這可能會影響可恢復資料的數量，甚至可能影響恢復過程的細節。
* *最近更改的歷史記錄*：故障發生時是否有任何維護程序正在進行，或者您的 ILM 策略是否最近進行了任何更改，都會影響您的恢復過程的詳細資訊。在開始站點恢復之前，技術支援必須評估您的電網的近期歷史及其當前狀況。



CAUTION: 站點恢復只能由技術支援執行。

這是技術支援用於恢復故障站點的過程的概述：

. 技術支援：
+
.. 對失敗進行詳細評估。
.. 與您一起檢視您的業務目標。
.. 制定適合您情況的恢復計畫。


. 如果主管理節點發生故障，技術支援將對其進行復原。
. 技術支援將按照以下概要恢復所有儲存節點：
+
.. 根據需要更換儲存節點硬體或虛擬機器。
.. 將物件元資料還原到故障站點。
.. 將物件資料還原到已復原的儲存節點。
+

CAUTION: 如果使用單一故障儲存節點的復原程序，則會發生資料遺失。

+

NOTE: 當整個站點發生故障時，技術支援使用專門的命令來成功恢復物件和物件元資料。



. 技術支援恢復其他故障節點。
+
恢復物件元資料和資料後，技術支援使用標準程序來恢復故障的網關節點或非主管理節點。



.相關資訊
link:site-decommissioning.html["場地退役"]
