---
permalink: maintain/how-your-system-is-affected-when-you-apply-hotfix.html 
sidebar: sidebar 
keywords: storagegrid, hotfix 
summary: 您必須了解應用修補程式時StorageGRID系統將受到怎樣的影響。 
---
= 應用修補程式後您的系統會受到怎樣的影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須了解應用修補程式時StorageGRID系統將受到怎樣的影響。



== StorageGRID修補程式不會造成中斷

StorageGRID系統可以在整個修補程式過程中從用戶端應用程式提取和檢索資料。如果您批准對相同類型的所有節點（例如，儲存節點）進行熱修復，則會一次關閉一個節點，因此不會出現所有網格節點或某種類型的所有網格節點都不可用的情況。

為了實現持續可用性，請確保您的 ILM 策略包含指定儲存每個物件的多個副本的規則。您還必須確保所有外部 S3 用戶端都配置為將請求傳送到以下之一：

* 高可用性 (HA) 群組虛擬 IP 位址
* 高可用性第三方負載平衡器
* 每個客戶端有多個網關節點
* 每個客戶端有多個儲存節點




== 客戶端應用程式可能會遭遇短期中斷

StorageGRID系統可以在整個修補程式過程中從用戶端應用程式擷取和擷取資料；但是，如果修補程式需要重新啟動這些節點上的服務，則用戶端與各個網關節點或儲存節點的連線可能會暫時中斷。修復過程完成後，連線將恢復，並且各個節點上的服務將恢復。

如果在短時間內失去連線是不可接受的，您可能需要安排停機時間來套用修補程式。您可以使用選擇性批准來安排某些節點的更新時間。


NOTE: 您可以使用多個網關和高可用性 (HA) 群組在修補程式過程中提供自動故障轉移。請參閱說明link:../admin/configure-high-availability-group.html["配置高可用性組"]。



== 可能會觸發警報和 SNMP 通知

當服務重新啟動時以及當StorageGRID系統作為混合版本環境運行時（一些網格節點運行早期版本，而其他網格節點已升級到更高版本），可能會觸發警報和 SNMP 通知。一般來說，這些警報和通知將在修補程序完成時清除。



== 配置變更受到限制

將修補程式套用至StorageGRID時：

* 在修補程式套用到所有節點之前，請勿進行任何網格配置變更（例如，指定網格網路子網路或核准待處理的網格節點）。
* 在將修補程式套用到所有節點之前，請勿更新 ILM 配置。

