---
permalink: maintain/rebooting-grid-node-from-grid-manager.html 
sidebar: sidebar 
keywords: reboot grid node, tasks tab 
summary: 您可以從「節點」頁面上的「任務」標籤重新啟動單一網格節點。 
---
= 從「任務」標籤重新啟動網格節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從「節點」頁面上的「任務」標籤重新啟動單一網格節點。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 你有link:../admin/admin-group-permissions.html["維護或 Root 存取權限"]。
* 您有配置密碼。
* 如果您要重新啟動主管理節點或任何儲存節點，請先查看以下注意事項：
+
** 當您重新啟動主管理節點時，您的瀏覽器將暫時失去對網格管理器的存取權。
** 如果您在給定網站重新啟動兩個或更多儲存節點，則您可能無法在重新啟動期間存取某些物件。如果任何 ILM 規則使用 *Dual commit* 攝取選項（或規則指定 *Balanced* 且無法立即建立所有必要的副本），則可能會出現此問題。在這種情況下， StorageGRID會將新攝取的物件提交到同一站點上的兩個儲存節點，然後再評估 ILM。
** 為確保在儲存節點重新啟動時可以存取所有對象，請在重新啟動節點之前停止在站點提取對象約一小時。




.關於此任務
當StorageGRID重新啟動網格節點時，它會發出 `reboot`命令，這會導致節點關閉並重新啟動。所有服務都會自動重新啟動。

* 重新啟動 VMware 節點將重新啟動虛擬機器。
* 重新啟動 Linux 節點會重新啟動容器。
* 重新啟動StorageGRID Appliance 節點會重新啟動運算控制器。



TIP: 如果需要重新啟動多個節點，可以使用link:../maintain/rolling-reboot-procedure.html["滾動重啟程序"]。

.步驟
. 選擇*NODES*。
. 選擇要重新啟動的網格節點。
. 選擇“*任務*”標籤。
. 選擇*重新啟動*。
+
出現確認對話框。如果您正在重新啟動主管理節點，確認對話方塊會提醒您，當服務停止時，您的瀏覽器與網格管理器的連線將暫時遺失。

. 輸入設定密碼，然後選擇「*確定*」。
. 等待節點重新啟動。
+
服務關閉可能需要一些時間。

+
當節點重新啟動時，節點頁面上會出現該節點的灰色（管理關閉）圖示。當所有服務重新啟動且節點成功連接到電網時，「節點」頁面應顯示正常狀態（節點名稱左側沒有圖示），表示沒有活動警報且節點已連接到電網。


