---
permalink: maintain/recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html 
sidebar: sidebar 
keywords: storagegrid, recover, maintenance, maintain, failed storage volumes, failed volumes, cassandra, cassandra rebuild, rebuild cassandra, cassandra database 
summary: 您必須執行一個腳本，重新格式化並重新安裝故障儲存磁碟區上的存儲，並在系統確定必要時重建儲存節點上的 Cassandra 資料庫。 
---
= 恢復故障的儲存磁碟區並重建 Cassandra 資料庫
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須執行一個腳本，重新格式化並重新安裝故障儲存磁碟區上的存儲，並在系統確定必要時重建儲存節點上的 Cassandra 資料庫。

.開始之前
* 你有 `Passwords.txt`文件。
* 伺服器上的系統磁碟機完好無損。
* 故障原因已確定，如有必要，已購買了替換儲存硬體。
* 替換存儲的總大小與原始存儲相同。
* 您已檢查儲存節點退役未正在進行，或您已暫停節點退役程序。（在網格管理員中，選擇 *維護* > *任務* > *退役*。）
* 您已檢查擴充功能是否尚未進行。（在網格管理員中，選擇 *維護* > *任務* > *擴充*。）
* 你有link:reviewing-warnings-about-storage-volume-recovery.html["查看了有關儲存卷復原的警告"]。


.步驟
. 根據需要，更換與您先前識別和卸載的故障儲存卷相關的故障實體或虛擬儲存。
+
請勿在此步驟中重新安裝磁碟區。存儲已重新安裝並添加到 `/etc/fstab`在後續步驟中。

. 在網格管理器中，前往 *NODES* > `*appliance Storage Node*` > *硬體*。在頁面的StorageGRID Appliance 部分中，驗證儲存 RAID 模式是否正常。
. 登入發生故障的儲存節點：
+
.. 輸入以下命令： `ssh admin@_grid_node_IP_`
.. 輸入 `Passwords.txt`文件。
.. 輸入以下命令切換到root： `su -`
.. 輸入 `Passwords.txt`文件。
+
當您以 root 身分登入時，提示字元將從 `$`到 `#`。



. 使用文字編輯器（vi 或 vim）從 `/etc/fstab`文件，然後儲存該文件。
+

NOTE: 註解掉失敗的捲 `/etc/fstab`文件不足。必須從 `fstab`恢復過程會驗證 `fstab`文件與已安裝的檔案系統相符。

. 重新格式化任何失敗的儲存卷，並在必要時重建 Cassandra 資料庫。進入： `reformat_storage_block_devices.rb`
+
** 當儲存磁碟區 0 被卸載時，提示和訊息將表示 Cassandra 服務正在停止。
** 如果有必要，系統會提示您重建 Cassandra 資料庫。
+
*** 查看警告。如果都不適用，則重建 Cassandra 資料庫。輸入：*y*
*** 如果多個儲存節點處於離線狀態，或在過去 15 天內重建了另一個儲存節點。輸入：*n*
+
腳本將退出而不重建 Cassandra。聯繫技術支援。



** 對於儲存節點上的每個 rangedb 驅動器，當您被詢問時： `Reformat the rangedb drive _<name>_ (device _<major number>:<minor number>_)? [y/n]?` ，請輸入以下回應之一：
+
*** *y* 重新格式化有錯誤的磁碟機。這將重新格式化儲存卷，並將重新格式化的儲存卷新增至 `/etc/fstab`文件。
*** *n* 如果磁碟機沒有錯誤，且您不想重新格式化它。
+

NOTE: 選擇 *n* 退出腳本。安裝磁碟機（如果您認為應該保留磁碟機上的資料並且錯誤地卸載了磁碟機）或移除磁碟機。然後，運行 `reformat_storage_block_devices.rb`再次命令。

+

NOTE: 一些StorageGRID恢復程序使用 Reaper 來處理 Cassandra 修復。一旦相關或所需的服務開始，修復就會自動進行。您可能會注意到腳本輸出中提到了“reaper”或“Cassandra repair”。如果您看到指示修復失敗的錯誤訊息，請執行錯誤訊息中指示的命令。

+
在以下範例輸出中，驅動器 `/dev/sdf`必須重新格式化，而 Cassandra 不需要重建：

+
[listing]
----
root@DC1-S1:~ # reformat_storage_block_devices.rb
Formatting devices that are not in use...
Skipping in use device /dev/sdc
Skipping in use device /dev/sdd
Skipping in use device /dev/sde
Reformat the rangedb drive /dev/sdf (device 8:64)? [Y/n]? y
Successfully formatted /dev/sdf with UUID b951bfcb-4804-41ad-b490-805dfd8df16c
All devices processed
Running: /usr/local/ldr/setup_rangedb.sh 12368435
Cassandra does not need rebuilding.
Starting services.
Informing storage services of new volume

Reformatting done.  Now do manual steps to
restore copies of data.
----






重新格式化並重新安裝儲存磁碟區並完成必要的 Cassandra 操作後，您可以link:../maintain/restoring-volume.html["使用網格管理器恢復物件數據"]。
