---
permalink: maintain/removing-port-remaps.html 
sidebar: sidebar 
keywords: storagegrid, recover, remove port remap, removing port remap, port remap 
summary: 如果要為負載平衡器服務配置端點，並且要使用已配置為連接埠重新映射的映射到連接埠的端口，則必須先刪除現有的連接埠重映射，否則端點將無效。您必須在每個具有衝突的重新映射連接埠的管理節點和網關節點上執行腳本，以刪除該節點的所有連接埠重新映射。 
---
= 刪除連接埠重新映射
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要為負載平衡器服務配置端點，並且要使用已配置為連接埠重新映射的映射到連接埠的端口，則必須先刪除現有的連接埠重映射，否則端點將無效。您必須在每個具有衝突的重新映射連接埠的管理節點和網關節點上執行腳本，以刪除該節點的所有連接埠重新映射。

.關於此任務
此過程將刪除所有連接埠重新映射。如果您需要保留一些重新映射，請聯絡技術支援。

有關配置負載平衡器端點的信息，請參閱link:../admin/configuring-load-balancer-endpoints.html["配置負載平衡器端點"]。


NOTE: 如果連接埠重新映射提供用戶端訪問，請重新配置用戶端以使用不同的連接埠作為負載平衡器端點，以避免服務遺失。否則，刪除連接埠對映將導致客戶端存取遺失，應進行適當的安排。


NOTE: 此程序不適用於在裸機主機上作為容器部署的StorageGRID系統。請參閱說明link:removing-port-remaps-on-bare-metal-hosts.html["刪除裸機主機上的連接埠重新映射"]。

.步驟
. 登入節點。
+
.. 輸入以下命令： `ssh -p 8022 admin@node_IP`
+
端口 8022 是基礎作業系統的 SSH 端口，而端口 22 是運行StorageGRID的容器引擎的 SSH 端口。

.. 輸入 `Passwords.txt`文件。
.. 輸入以下命令切換到root： `su -`
.. 輸入 `Passwords.txt`文件。
+
當您以 root 身分登入時，提示字元將從 `$`到 `#`。



. 運行以下腳本： `remove-port-remap.sh`
. 重啟節點： `reboot`
. 退出命令外殼： `exit`
. 在每個具有衝突的重新映射連接埠的管理節點和網關節點上重複這些步驟。

