---
permalink: maintain/removing-port-remaps-on-bare-metal-hosts.html 
sidebar: sidebar 
keywords: storagegrid, recover, linux, linux host, bare metal host, baremetal host, remove port remap, removing port remap, port remap 
summary: 如果要為負載平衡器服務配置端點，並且要使用已配置為連接埠重新映射的映射到連接埠的端口，則必須先刪除現有的連接埠重映射，否則端點將無效。 
---
= 刪除裸機主機上的連接埠重新映射
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要為負載平衡器服務配置端點，並且要使用已配置為連接埠重新映射的映射到連接埠的端口，則必須先刪除現有的連接埠重映射，否則端點將無效。

.關於此任務
如果您在裸機主機上執行StorageGRID ，請依照此程序操作，而不是依照刪除連接埠重新對應的常規程序操作。您必須編輯具有衝突的重新映射連接埠的每個管理節點和網關節點的節點配置文件，以刪除所有節點的連接埠重新映射並重新啟動該節點。


CAUTION: 此過程將刪除所有連接埠重新映射。如果您需要保留一些重新映射，請聯絡技術支援。

有關配置負載平衡器端點的信息，請參閱管理StorageGRID的說明。


NOTE: 由於節點重新啟動，此程序可能會導致服務暫時遺失。

.步驟
. 登入支援該節點的主機。以 root 身分或具有 sudo 權限的帳號登入。
. 執行以下命令暫時禁用該節點： `sudo storagegrid node stop _node-name_`
. 使用文字編輯器（例如 vim 或 pico）編輯節點的節點設定檔。
+
節點設定檔可以在以下位置找到 `/etc/storagegrid/nodes/_node-name_.conf`。

. 找到包含連接埠重新映射的節點設定檔部分。
+
請參閱以下範例中的最後兩行。

+
[listing, subs="specialcharacters,quotes"]
----
ADMIN_NETWORK_CONFIG = STATIC
ADMIN_NETWORK_ESL = 10.0.0.0/8, 172.19.0.0/16, 172.21.0.0/16
ADMIN_NETWORK_GATEWAY = 10.224.0.1
ADMIN_NETWORK_IP = 10.224.5.140
ADMIN_NETWORK_MASK = 255.255.248.0
ADMIN_NETWORK_MTU = 1400
ADMIN_NETWORK_TARGET = eth1
ADMIN_NETWORK_TARGET_TYPE = Interface
BLOCK_DEVICE_VAR_LOCAL = /dev/sda2
CLIENT_NETWORK_CONFIG = STATIC
CLIENT_NETWORK_GATEWAY = 47.47.0.1
CLIENT_NETWORK_IP = 47.47.5.140
CLIENT_NETWORK_MASK = 255.255.248.0
CLIENT_NETWORK_MTU = 1400
CLIENT_NETWORK_TARGET = eth2
CLIENT_NETWORK_TARGET_TYPE = Interface
GRID_NETWORK_CONFIG = STATIC
GRID_NETWORK_GATEWAY = 192.168.0.1
GRID_NETWORK_IP = 192.168.5.140
GRID_NETWORK_MASK = 255.255.248.0
GRID_NETWORK_MTU = 1400
GRID_NETWORK_TARGET = eth0
GRID_NETWORK_TARGET_TYPE = Interface
NODE_TYPE = VM_API_Gateway
*PORT_REMAP = client/tcp/8082/443*
*PORT_REMAP_INBOUND = client/tcp/8082/443*
----
. 編輯 PORT_REMAP 和 PORT_REMAP_INBOUND 條目以刪除連接埠重新對應。
+
[listing]
----
PORT_REMAP =
PORT_REMAP_INBOUND =
----
. 執行以下命令來驗證對節點的節點設定檔的變更：``sudo storagegrid node validate _node-name_``
+
在繼續下一步之前，請解決所有錯誤或警告。

. 執行以下命令重新啟動節點而不進行連接埠重新映射： `sudo storagegrid node start _node-name_`
. 使用列出的密碼以管理員身分登入節點 `Passwords.txt`文件。
. 驗證服務是否正確啟動。
+
.. 查看伺服器上所有服務的狀態清單：``sudo storagegrid-status``
+
狀態會自動更新。

.. 等到所有服務的狀態都變成「正在運作」或「已驗證」。
.. 退出狀態畫面：``Ctrl+C``


. 在每個具有衝突的重新映射連接埠的管理節點和網關節點上重複這些步驟。

