---
permalink: maintain/rename-grid-site-node-overview.html 
sidebar: sidebar 
keywords: rename grid, rename site, rename node, display name, system name 
summary: 根據需要，您可以變更整個網格、每個網站和每個節點在網格管理器中顯示的顯示名稱。您可以隨時安全地更新顯示名稱。 
---
= 使用重新命名過程
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根據需要，您可以變更整個網格、每個網站和每個節點在網格管理器中顯示的顯示名稱。您可以隨時安全地更新顯示名稱。



== 重命名的程式是怎樣的？

最初安裝StorageGRID時，您需要為網格、每個網站和每個節點指定一個名稱。這些初始名稱稱為_系統名稱_，它們是整個StorageGRID中最初顯示的名稱。

系統名稱是內部StorageGRID操作所必需的，並且不能更改。但是，您可以使用重新命名程序為網格、每個網站和每個節點定義新的_顯示名稱_。這些顯示名稱出現在各種StorageGRID位置，而不是（或在某些情況下，除了）底層系統名稱。

使用重新命名程序來修正拼字錯誤、實施不同的命名約定或指示網站及其所有節點已重新定位。與系統名稱不同，顯示名稱可以在需要時更新，並且不會影響StorageGRID操作。



== 系統名稱和顯示名稱出現在哪裡？

下表總結了系統名稱和顯示名稱在StorageGRID使用者介面和StorageGRID檔案中的顯示位置。

[cols="2a,2a,3a"]
|===
| 地點 | 系統名稱 | 顯示名稱 


 a| 
網格管理器頁面
 a| 
除非項目被重新命名，否則顯示
 a| 
如果某個項目被重新命名，則會在下列位置顯示系統名稱：

* 儀表板
* 節點頁面
* 高可用性群組、負載平衡器端點、VLAN 介面、金鑰管理伺服器、網格密碼和防火牆控制的設定頁面
* 警報
* 儲存池定義
* 對像元資料查找頁面
* 與維護程序相關的頁面，包括升級、修補程式、 SANtricity OS 升級、停用、擴充、復原和物件存在性檢查
* 支援頁面（日誌和診斷）
* 單一登入頁面，位於管理節點詳細資料表中管理節點主機名稱旁邊




 a| 
*NODES* > 節點的 *Overview* 選項卡
 a| 
始終顯示
 a| 
僅當項目重新命名時顯示



 a| 
網格管理器中的舊頁面（例如，*支援* > *網格拓撲*）
 a| 
顯示
 a| 
未顯示



 a| 
*節點健康* API
 a| 
總是返回
 a| 
僅當項目重命名時才返回



 a| 
使用 SSH 存取節點時提示
 a| 
顯示為主要名稱，除非該項目已重新命名：

`admin@SYSTEM-NAME: ~ $`

當項目重新命名時包含在括號中：

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`
 a| 
當項目重新命名時顯示為主名稱：

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`



 a| 
`Passwords.txt`復原包中的文件
 a| 
顯示為 `Server Name`
 a| 
顯示為 `Display Name`



 a| 
`/etc/hosts`所有節點上的文件

例如：

`10.96.99.128 SYSTEM-NAME 28989c59-a2c3-4d30-bb09-6879adf2437f DISPLAY-NAME localhost-grid # storagegrid-gen-host`
 a| 
始終顯示在第二列
 a| 
當項目重新命名時，顯示在第四列



 a| 
`topology-display-names.json`，包含在AutoSupport資料中
 a| 
不包括
 a| 
除非項目已重新命名，否則為空；否則，將網格、站點和節點 ID 對應到其顯示名稱。

|===


== 顯示名稱要求

在使用此程序之前，請查看顯示名稱的要求。



=== 顯示節點的名稱

節點的顯示名稱必須遵循以下規則：

* 在您的StorageGRID系統中必須是唯一的。
* 不能與StorageGRID系統中任何其他項目的系統名稱相同。
* 必須至少包含 1 個字符，且不超過 32 個字符。
* 可以包含數字、連字號 (-) 以及大寫和小寫字母。
* 可以以字母或數字開頭或結尾，但不能以連字符開頭或結尾。
* 不能全是數字。
* 不區分大小寫。例如， `DC1-ADM`和 `dc1-adm`均視為重複。


您可以使用其他節點先前使用的顯示名稱重新命名節點​​，只要重新命名不會導致重複的顯示名稱或系統名稱。



=== 網格和站點的顯示名稱

網格和網站的顯示名稱遵循相同的規則，但有以下例外：

* 可以包含空格。
* 可包含以下特殊字元： `= - _ : , . @ !`
* 可以以特殊字元（包括連字符）開頭和結尾。
* 可以是全部數字或特殊字元。




== 顯示名稱最佳實踐

如果您打算重新命名多個項目，請在使用此程序之前記錄您的一般命名方案。提出一個系統，確保名稱唯一、一致且一目了然。

您可以使用任何適合您的組織要求的命名約定。請考慮以下關於應包含哪些內容的基本建議：

* *站點指示器*：如果您有多個站點，請為每個節點名稱新增一個站點代碼。
* *節點類型*：節點名稱通常指示節點的類型。您可以使用以下縮寫 `s`， `adm` ， 和 `gw`（儲存節點、管理節點和網關節點）。
* *節點編號*：如果網站包含多個特定類型的節點，則在每個節點的名稱後面加上一個唯一的編號。


在為可能隨時間而改變的名稱添加具體細節之前，請三思。例如，不要在節點名稱中包含 IP 位址，因為這些位址可能會變更。同樣，如果您移動設備或升級硬件，機架位置或設備型號可能會發生變化。



=== 顯示名稱範例

假設您的StorageGRID系統有三個資料中心，並且每個資料中心都有不同類型的節點。您的顯示名稱可能像這樣簡單：

* *網格*： `StorageGRID Deployment`
* *第一個站點*： `Data Center 1`
+
** `dc1-adm1`
** `dc1-s1`
** `dc1-s2`
** `dc1-s3`
** `dc1-gw1`


* *第二個站點*： `Data Center 2`
+
** `dc2-adm2`
** `dc2-s1`
** `dc2-s2`
** `dc2-s3`


* *第三個站點*： `Data Center 3`
+
** `dc3-s1`
** `dc3-s2`
** `dc3-s3`



