---
permalink: maintain/reviewing-warnings-about-storage-volume-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, volume warning 
summary: 在恢復儲存節點的故障儲存磁碟區之前，您必須查看以下警告。 
---
= 儲存卷恢復警告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在恢復儲存節點的故障儲存磁碟區之前，請查看以下警告。

儲存節點中的儲存磁碟區（或 rangedb）由十六進位數標識，稱為磁碟區 ID。例如，0000 是第一卷，000F 是第十六卷。每個儲存節點上的第一個物件儲存（磁碟區 0）使用最多 4 TB 的空間用於物件元資料和 Cassandra 資料庫操作；該磁碟區上的任何剩餘空間都用於物件資料。所有其他儲存卷專門用於物件資料。

如果磁碟區 0 發生故障並需要恢復，則 Cassandra 資料庫可能會作為磁碟區復原過程的一部分進行重建。在以下情況下，Cassandra 也可能需要重建：

* 儲存節點離線超過 15 天後將重新上線。
* 系統磁碟機和一個或多個儲存磁碟區發生故障並已復原。


當 Cassandra 重建時，系統使用來自其他儲存節點的資訊。如果太多儲存節點處於離線狀態，某些 Cassandra 資料可能無法使用。如果 Cassandra 最近重建，Cassandra 資料可能在整個網格中尚不一致。如果在太多儲存節點離線時重建 Cassandra，或在 15 天內重建兩個或多個儲存節點，則可能會發生資料遺失。


CAUTION: 如果多個儲存節點發生故障（或離線），請聯絡技術支援。不要執行以下恢復程序。可能會發生資料遺失。


CAUTION: 如果這是儲存節點故障或恢復後 15 天內第二次發生儲存節點故障，請聯絡技術支援。在 15 天內在兩個或更多儲存節點上重建 Cassandra 可能會導致資料遺失。


NOTE: 如果站點上的多個儲存節點發生故障，則可能需要站點復原程序。看link:how-site-recovery-is-performed-by-technical-support.html["技術支援如何恢復站點"] 。


CAUTION: 如果 ILM 規則配置為僅儲存複製副本，且該副本存在於發生故障的儲存磁碟區上，則您將無法復原該物件。

.相關資訊
link:warnings-and-considerations-for-grid-node-recovery.html["網格節點復原的警告和注意事項"]
