---
permalink: maintain/shutting-down-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, node shutdown, shut down node, node shut down 
summary: 您可以從節點的命令 shell 關閉網格節點。 
---
= 關閉網格節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從節點的命令 shell 關閉網格節點。

.開始之前
* 你有 `Passwords.txt`文件。


.關於此任務
在執行此程序之前，請先查看以下注意事項：

* 一般來說，您不應該一次關閉多個節點，以避免中斷。
* 除非文件或技術支援明確指示，否則請勿在維護過程中關閉節點。
* 關機過程取決於節點的安裝位置，如下所示：
+
** 關閉 VMware 節點會關閉虛擬機器。
** 關閉 Linux 節點會關閉容器。
** 關閉StorageGRID設備節點會關閉計算控制器。


* 如果您打算關閉某個站點的多個儲存節點，請在關閉節點之前停止在該站點提取物件約一小時。
+
如果任何 ILM 規則使用 *Dual commit* 攝取選項（或如果規則使用 *Balanced* 選項並且無法立即建立所有必要的副本）， StorageGRID會立即將任何新攝取的物件提交到同一網站上的兩個儲存節點，然後評估 ILM。如果網站上的多個儲存節點關閉，您可能無法在關閉期間存取新攝取的物件。如果網站上可用的儲存節點太少，寫入操作也可能會失敗。看link:../ilm/index.html["使用 ILM 管理對象"] 。



.步驟
. 登入網格節點：
+
.. 輸入以下命令： `ssh admin@_grid_node_IP_`
.. 輸入 `Passwords.txt`文件。
.. 輸入以下命令切換到root： `su -`
.. 輸入 `Passwords.txt`文件。


+
當您以 root 身分登入時，提示字元將從 `$`到 `#`。

. 停止所有服務： `service servermanager stop`
+
服務可能需要長達 15 分鐘才能關閉，您可能需要遠端登入系統來監控關閉過程。

. 如果節點正在 VMware 虛擬機器上運行或它是設備節點，請發出關機命令： `shutdown -h now`
+
無論結果如何，都執行此步驟 `service servermanager stop`命令。

+

NOTE: 發出 `shutdown -h now`命令，則必須關閉設備電源並重新啟動節點。

+
對於設備，此命令關閉控制器，但設備仍處於通電狀態。您必須完成下一步。

. 如果您要關閉設備節點，請按照適用於您的設備的步驟進行操作。
+
[role="tabbed-block"]
====
.SG6160
--
.. 關閉 SG6100-CN 儲存控制器的電源。
.. 等待 SG6100-CN 儲存控制器上的藍色電源 LED 熄滅。


--
.SGF6112
--
.. 關閉設備電源。
.. 等待藍色電源 LED 熄滅。


--
.SG6000
--
.. 等待儲存控制器背面的綠色快取活動 LED 熄滅。
+
當需要將快取資料寫入磁碟機時，此 LED 亮起。您必須等待此 LED 熄滅後才能關閉電源。

.. 關閉設備電源，等待藍色電源 LED 熄滅。


--
.SG5800
--
.. 等待儲存控制器背面的綠色快取活動 LED 熄滅。
+
當需要將快取資料寫入磁碟機時，此 LED 亮起。您必須等待此 LED 熄滅後才能關閉電源。

.. 從SANtricity System Manager 主頁中，選擇 *查看正在進行的操作*。
.. 確認所有操作均已完成，然後再繼續下一步。
.. 關閉控制器架上的兩個電源開關，並等待控制器架上的所有 LED 熄滅。


--
.SG5700
--
.. 等待儲存控制器背面的綠色快取活動 LED 熄滅。
+
當需要將快取資料寫入磁碟機時，此 LED 亮起。您必須等待此 LED 熄滅後才能關閉電源。

.. 關閉設備電源，等待所有 LED 和七段顯示活動停止。


--
.SG100 或 SG1000
--
.. 關閉設備電源。
.. 等待藍色電源 LED 熄滅。


--
====

