---
permalink: maintain/storagegrid-hotfix-procedure.html 
sidebar: sidebar 
keywords: apply hotfix, install hotfix, replace primary admin node 
summary: 如果在功能發布之間偵測到並解決了軟體問題，則可能需要對StorageGRID系統套用修補程式。 
---
= StorageGRID修補程式程序
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果在功能發布之間偵測到並解決了軟體問題，則可能需要對StorageGRID系統套用修補程式。

StorageGRID修補程式包含在功能或修補程式版本之外提供的軟體變更。未來版本中也會包含相同的變更。此外，每個修補程式版本都包含功能或修補程式版本中所有先前修補程式的總和。



== 應用修補程序的注意事項

當另一個維護程序正在運作時，您無法套用StorageGRID修補程式。例如，在退役、擴充或復原過程正在執行時，您無法套用修補程式。


NOTE: 如果節點或網站退役程式暫停，您可以安全地套用修補程式。此外，您可能能夠在StorageGRID升級過程的最後階段套用修補程式。有關詳細信息，請參閱升級StorageGRID軟體的說明。

在網格管理器中上傳修補程式後，修補程式將自動套用到主管理節點。然後，您可以批准將修補程式套用到StorageGRID系統中的其餘節點。

如果修補程式無法套用到一個或多個節點，則失敗的原因將顯示在修補程式進度表的詳細資料列中。您必須解決導致失敗的任何問題，然後重試整個過程。先前成功應用修補程式的節點將在後續應用中被跳過。您可以根據需要安全地重試修補程式程序多次，直到所有節點都已更新。必須在所有網格節點上成功安裝修補程式才能使應用程式完整。

雖然網格節點會使用新的修補程式版本進行更新，但修補程式中的實際變更可能只會影響特定類型節點上的特定服務。例如，修補程式可能僅影響儲存節點上的 LDR 服務。



== 如何應用修補程式進行恢復和擴展

將修補程式套用到您的網格後，主管理節點會自動將相同的修補程式版本安裝到透過復原作業還原或在擴充功能中新增的任何節點。

但是，如果您需要還原主管理節點，則必須手動安裝正確的StorageGRID版本，然後套用修補程式。主管理節點的最終StorageGRID版本必須與網格中其他節點的版本相符。

以下範例說明如何在復原主管理節點時套用修補程式：

. 假設網格正在執行具有最新修補程式的StorageGRID 11._A.B_ 版本。  「網格版本」是 11._A.B.y_。
. 主管理節點發生故障。
. 您使用StorageGRID 11._A.B_ 重新部署主管理節點，並執行復原程序。
+

NOTE: 根據需要匹配網格版本，您可以在部署節點時使用次要版本；您不需要先部署主要版本。

. 然後將修補程式 11._A.B.y_ 應用到主管理節點。


有關更多信息，請參閱link:configuring-replacement-primary-admin-node.html["配置替換主管理節點"] 。
