---
permalink: maintain/warnings-and-considerations-for-grid-node-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, warning 
summary: 如果網格節點發生故障，您必須盡快恢復它。在開始之前，您必須查看節點復原的所有警告和注意事項。 
---
= 網格節點復原的警告和注意事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果網格節點發生故障，您必須盡快恢復它。在開始之前，您必須查看節點復原的所有警告和注意事項。


CAUTION: StorageGRID是一個由多個相互協作的節點所組成的分散式系統。不要使用磁碟快照來還原網格節點。相反，請參考每種節點類型的復原和維護程序。


NOTE: 如果整個StorageGRID站點發生故障，請聯絡技術支援。技術支援將與您合作制定並執行網站復原計劃，以最大限度地恢復資料量並滿足您的業務目標。看link:how-site-recovery-is-performed-by-technical-support.html["技術支援如何恢復站點"] 。

盡快恢復故障網格節點的一些原因包括：

* 發生故障的網格節點會降低系統和物件資料的冗餘度，如果另一個節點發生故障，您將面臨永久性資料遺失的風險。
* 電網節點故障會影響日常營運的效率。
* 網格節點故障會降低您監控系統操作的能力。
* 如果實施嚴格的 ILM 規則，則發生故障的網格節點可能會導致 500 內部伺服器錯誤。
* 如果網格節點沒有及時恢復，恢復時間可能會增加。例如，在恢復完成之前可能會出現需要清除的佇列。


始終遵循您正在復原的特定類型的網格節點的復原程序。主或非主管理節點、網關節點、設備節點和儲存節點的復原過程各不相同。



== 恢復網格節點的先決條件

恢復網格節點時假設以下所有條件：

* 故障的實體或虛擬硬體已被更換和配置。
* 替換裝置上的StorageGRID Appliance Installer 版本與您的StorageGRID系統的軟體版本相匹配，如 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html["驗證並升級StorageGRID Appliance Installer 版本"^]。
* 如果您正在還原主管理節點以外的網格節點，則正在復原的網格節點與主管理節點之間存在連線。
* 如果要恢復設備儲存節點，則必須在設備安裝期間指定與原始設備相同的儲存類型（組合、僅元資料或僅資料）。如果指定不同的儲存類型，復原將失敗，並且需要使用指定的正確儲存類型重新安裝裝置。




== 當託管多個網格節點的伺服器發生故障時，節點復原的順序

如果託管多個網格節點的伺服器發生故障，您可以按任意順序還原節點。但是，如果發生故障的伺服器託管主管理節點，則必須先還原該節點。首先恢復主管理節點可防止其他節點復原因等待聯繫主管理節點而停止。



== 已恢復節點的 IP 位址

不要嘗試使用目前指派給任何其他節點的 IP 位址來還原節點。部署新節點時，請使用故障節點的目前 IP 位址或未使用的 IP 位址。

如果您使用新的 IP 位址部署新節點，然後還原該節點，則復原的節點將繼續使用新的 IP 位址。如果要還原到原始 IP 位址，請在恢復完成後使用變更 IP 工具。
