---
permalink: primer/hybrid-clouds-with-storagegrid.html 
sidebar: sidebar 
keywords: hybrid cloud, cloud storage pool, platform services, fabricpool, ontap 
summary: 透過實施策略驅動的資料管理將物件儲存在雲端儲存池、利用StorageGRID平台服務以及使用NetApp FabricPool將資料從ONTAP到StorageGRID ，在混合雲配置中使用StorageGRID 。 
---
= 使用StorageGRID的混合雲
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
透過實施策略驅動的資料管理將物件儲存在雲端儲存池、利用StorageGRID平台服務以及使用NetApp FabricPool將資料從ONTAP到StorageGRID ，在混合雲配置中使用StorageGRID 。



== 雲端儲存池

雲端儲存池可讓您儲存StorageGRID系統之外的物件。例如，您可能想要將不經常存取的物件移至成本較低的雲端存儲，例如 Amazon S3 Glacier、S3 Glacier Deep Archive、Google Cloud 或 Microsoft Azure Blob 儲存中的存檔存取層。或者，您可能想要維護StorageGRID物件的雲端備份，可用於還原因儲存磁碟區或儲存節點故障而遺失的資料。

還支援第三方合作夥伴存儲，包括磁碟和磁帶存儲。


NOTE: 不支援將雲端儲存池與FabricPool一起使用，因為從雲端儲存池目標檢索物件會增加延遲。



== S3平台服務

S3 平台服務可讓您使用遠端服務作為物件複製、事件通知或搜尋整合的端點。平台服務獨立於網格的 ILM 規則運行，並為單獨的 S3 儲存桶啟用。支援以下服務：

* CloudMirror 複製服務會自動將指定物件映像到目標 S3 儲存桶，可位於 Amazon S3 或第二個StorageGRID系統上。
* 事件通知服務將指定操作的訊息傳送至支援接收簡單通知服務 (Amazon SNS) 事件的外部端點。
* 搜尋整合服務將物件元資料傳送至外部 Elasticsearch 服務，允許使用第三方工具搜尋、視覺化和分析元資料。


例如，您可以使用 CloudMirror 複製將特定客戶記錄鏡像到 Amazon S3，然後利用 AWS 服務對您的資料執行分析。



== 使用FabricPool進行ONTAP資料分層

您可以使用FabricPool將資料分層到StorageGRID ，從而降低ONTAP儲存的成本。  FabricPool支援將資料自動分層到低成本的物件儲存層（無論是在內部還是外部）。

與手動分層解決方案不同， FabricPool透過自動化資料分層來降低儲存成本，從而降低整體擁有成本。它透過分層到公有雲和私有雲（包括StorageGRID）來實現雲端經濟的優勢。

.相關資訊
* link:../ilm/what-cloud-storage-pool-is.html["什麼是雲端儲存池？"]
* link:../tenant/what-platform-services-are.html["管理平台服務"]
* link:../fabricpool/index.html["為FabricPool配置StorageGRID"]

