---
permalink: primer/what-admin-node-is.html 
sidebar: sidebar 
keywords: admin nodes 
summary: 管理節點提供系統設定、監控和日誌記錄等管理服務。管理節點也可用於平衡 S3 用戶端流量的負載。每個網格必須有一個主管理節點，並且可以有任意數量的非主管理節點以實現冗餘。 
---
= 什麼是管理節點？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理節點提供系統設定、監控和日誌記錄等管理服務。管理節點也可用於平衡 S3 用戶端流量的負載。每個網格必須有一個主管理節點，並且可以有任意數量的非主管理節點以實現冗餘。



== 主管理節點和非主管理節點之間的差異

當您登入網格管理器或租戶管理器時，您正在連線到管理節點。您可以連接到任何管理節點，每個管理節點都會顯示StorageGRID系統的類似視圖。但是，主管理節點比非主管理節點提供更多功能。例如，大多數維護程序必須從主管理節點執行。

此表總結了主管理節點和非主管理節點的功能。

[cols="2a,1a,1a"]
|===
| 功能 | 主管理節點 | 非主管理節點 


 a| 
包括<<ams,輔助醫療系統>>服務
 a| 
是的
 a| 
是的



 a| 
包括<<cmn,厘米奈米>>服務
 a| 
是的
 a| 
不



 a| 
包括<<nms,網管系統>>服務
 a| 
是的
 a| 
是的



 a| 
包括<<prometheus,普羅米修斯>>服務
 a| 
是的
 a| 
是的



 a| 
包括<<ssm,薩姆>>服務
 a| 
是的
 a| 
是的



 a| 
包括<<load-balancer,負載平衡器>>和<<high-availability,高可用性>>服務
 a| 
是的
 a| 
是的



 a| 
支援<<mgmt-api,管理應用程式介面>>（管理 API）
 a| 
是的
 a| 
是的



 a| 
可用於所有與網路相關的維護任務，例如 IP 位址變更和更新 NTP 伺服器
 a| 
是的
 a| 
不



 a| 
可以在儲存節點擴充後執行 EC 重新平衡
 a| 
是的
 a| 
不



 a| 
可用於音量恢復程序
 a| 
是的
 a| 
是的



 a| 
可以從一個或多個節點收集日誌檔案和系統數據
 a| 
是的
 a| 
不



 a| 
發送警報通知、 AutoSupport套件和 SNMP 陷阱並通知
 a| 
是的。作為<<preferred-sender,首選寄件人>>。
 a| 
是的。充當備用發送者。

|===


== [[preferred-sender]]首選寄件者管理節點

如果您的StorageGRID部署包含多個管理節點，則主管理節點是警報通知、 AutoSupport套件以及 SNMP 陷阱和通知的首選傳送者。

在正常系統操作下，只有首選發送者發送通知。但是，所有其他管理節點都會監控首選發送者。如果偵測到問題，其他管理節點將充當_備用發送者_。

在以下情況下可能會發送多條通知：

* 如果管理節點彼此“孤立”，則首選發送者和備用發送者都會嘗試發送通知，並且可能會收到多份通知副本。
* 如果備用發送器偵測到首選發送器出現問題並開始發送通知，則首選發送器可能會重新獲得發送通知的能力。如果發生這種情況，可能會發送重複的通知。當備用發送器不再偵測到首選發送器上的錯誤時，它將停止發送通知。
+

NOTE: 當您測試AutoSupport套件時，所有管理節點都會傳送測試。測試警報通知時，您必須登入每個管理節點以驗證連線性。





== 管理節點的主要服務

下表顯示了管理節點的主要服務；但是，此表並未列出所有節點服務。

[cols="1a,2a"]
|===
| 服務 | 按鍵功能 


 a| 
審計管理系統 (AMS)
 a| 
追蹤系統活動和事件。



 a| 
[[cmn]]組態管理節點 (CMN)
 a| 
管理整個系統配置。



 a| 
高可用性
 a| 
管理管理節點和網關節點群組的高可用性虛擬 IP 位址。

*注意：*此服務也可在網關節點上找到。



 a| 
負載平衡器
 a| 
提供從客戶端到儲存節點的 S3 流量負載平衡。

*注意：*此服務也可在網關節點上找到。



 a| 
[[mgmt-api]]管理應用程式介面 (mgmt-api)
 a| 
處理來自網格管理 API 和租用戶管理 API 的請求。



 a| 
網路管理系統 (NMS)
 a| 
為網格管理器提供功能。



 a| 
普羅米修斯
 a| 
收集並儲存來自所有節點上的服務的時間序列指標。



 a| 
[[ssm]]伺服器狀態監視器 (SSM)
 a| 
監控作業系統和底層硬體。

|===