---
permalink: primer/what-storage-node-is.html 
sidebar: sidebar 
keywords: what is a storage node, how many storage nodes 
summary: 儲存節點管理和儲存物件資料和元資料。儲存節點包括在磁碟上儲存、移動、驗證和檢索物件資料和元資料所需的服務和流程。 
---
= 什麼是儲存節點？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存節點管理和儲存物件資料和元資料。儲存節點包括在磁碟上儲存、移動、驗證和檢索物件資料和元資料所需的服務和流程。

StorageGRID系統中的每個站點必須至少有三個儲存節點。



== 儲存節點的類型

在安裝過程中，您可以選擇要安裝的儲存節點類型。這些類型適用於基於軟體的儲存節點和支援該功能的基於設備的儲存節點：

* 組合資料和元資料儲存節點
* 僅元資料儲存節點
* 純資料儲存節點


您可以在以下情況下選擇儲存節點類型：

* 最初安裝儲存節點時
* 在StorageGRID系統擴充期間新增儲存節點時



NOTE: 儲存節點安裝完成後，您無法變更類型。

資料和元資料儲存節點（組合）:: 預設情況下，所有新的儲存節點都將儲存物件資料和元資料。這種類型的儲存節點稱為組合儲存節點。
僅元資料儲存節點:: 如果您的網格儲存了大量的小對象，那麼專門使用儲存節點來儲存元資料是有意義的。安裝專用元資料容量可以在大量小物件所需的空間和這些物件的元資料所需的空間之間實現更好的平衡。此外，在高效能設備上託管的僅元資料儲存節點可以提高效能。


僅元資料儲存節點具有特定的硬體需求：

* 使用StorageGRID設備時，只能在具有 12 個 1.9 TB 或 12 個 3.8 TB 硬碟的 SGF6112 裝置上配置僅元資料節點。
* 使用基於軟體的節點時，僅元資料節點資源必須與現有的儲存節點資源相符。例如：
+
** 如果現有StorageGRID站點使用 SG6000 或 SG6100 設備，則基於軟體的僅元資料節點必須符合以下最低要求：
+
*** 128 GB 內存
*** 8核心CPU
*** 8 TB SSD 或用於 Cassandra 資料庫的等效儲存空間（rangedb/0）


** 如果現有的StorageGRID站點使用具有 24 GB RAM、8 核心 CPU 和 3 TB 或 4TB 元資料儲存的虛擬儲存節點，則基於軟體的僅元資料節點應使用類似的資源（24 GB RAM、8 核心 CPU 和 4TB 元資料儲存（rangedb/0）。


* 新增新的StorageGRID站點時，新站點的總元資料容量應至少與現有StorageGRID站點相匹配，且新站點資源應與現有StorageGRID站點的儲存節點相符。


安裝僅元資料節點時，網格還必須包含用於資料儲存的最小數量的節點：

* 對於單站點網格，配置至少兩個組合或僅資料的儲存節點。
* 對於多站點網格，每個站點至少配置一個組合或僅資料的儲存節點。



NOTE: 儘管僅元資料儲存節點包含<<ldr-service,LDR 服務>>並且可以處理 S3 用戶端請求， StorageGRID效能可能不會提高。

純資料儲存節點:: 如果您的儲存節點具有不同的效能特徵，則專門使用儲存節點來儲存資料是有意義的。例如，為了潛在地提高效能，您可以使用僅資料、高容量旋轉磁碟儲存節點以及僅元資料的高效能儲存節點。


安裝僅資料節點時，網格必須包含以下內容：

* 每個網格至少有兩個組合或僅資料儲存節點
* 每個站點至少一個組合或僅資料儲存節點
* 每個站點至少有三個組合或僅元資料儲存節點




== 儲存節點的主要服務

下表顯示了儲存節點的主要服務；但是，此表並未列出所有節點服務。


NOTE: 某些服務（例如 ADC 服務和 RSM 服務）通常僅存在於每個站點的三個儲存節點上。

[cols="1a,3a"]
|===
| 服務 | 按鍵功能 


 a| 
帳戶（acct）
 a| 
管理租戶帳戶。



 a| 
管理網域控制器 (ADC)
 a| 
維護拓樸和電網範圍的配置。

*注意*：僅資料儲存節點不託管 ADC 服務。

.細節
[%collapsible]
====
管理網域控制器 (ADC) 服務會對網格節點及其相互之間的連接進行驗證。  ADC 服務託管在一個站點的至少三個儲存節點上。

ADC 服務維護拓撲訊息，包括服務的位置和可用性。當一個網格節點需要來自另一個網格節點的資訊或需要另一個網格節點執行的操作時，它會聯絡 ADC 服務來找到最佳的網格節點來處理其請求。此外，ADC 服務保留了StorageGRID部署的設定包的副本，允許任何網格節點檢索目前設定資訊。

為了促進分散式和孤立操作，每個 ADC 服務都會與StorageGRID系統中的其他 ADC 服務同步憑證、設定包以及有關服務和拓撲的資訊。

一般來說，所有網格節點都與至少一個 ADC 服務保持連線。這確保了網格節點始終能夠存取最新資訊。當網格節點連接時，它們會快取其他網格節點的證書，使得系統即使在 ADC 服務不可用時也能繼續與已知的網格節點一起運作。新的網格節點只能使用 ADC 服務建立連線。

每個網格節點的連接使得 ADC 服務能夠收集拓撲資訊。此網格節點資訊包括 CPU 負載、可用磁碟空間（如果有儲存）、支援的服務以及網格節點的站點 ID。其他服務透過拓樸查詢向 ADC 服務詢問拓樸資訊。  ADC 服務使用從StorageGRID系統收到的最新資訊來回應每個查詢。

====


 a| 
卡桑德拉
 a| 
儲存和保護對像元資料。

*注意*：僅資料儲存節點不託管 Cassandra 服務。



 a| 
卡桑德拉·雷珀
 a| 
執行物件元資料的自動修復。

*注意*：僅資料儲存節點不託管 Cassandra Reaper 服務。



 a| 
區塊
 a| 
管理擦除編碼資料和奇偶校驗片段。



 a| 
資料移動器 (dmv)
 a| 
將資料移至雲端儲存池。



 a| 
分散式資料儲存（DDS）
 a| 
監控對像元資料儲存。

.細節
[%collapsible]
====
每個儲存節點都包含分散式資料儲存 (DDS) 服務。該服務與 Cassandra 資料庫交互，對儲存在StorageGRID系統中的物件元資料執行後台任務。

DDS 服務追蹤進入StorageGRID系統的物件總數以及透過系統支援的每個介面 (S3) 提取的物件總數。

====


 a| 
身份（idnt）
 a| 
聯合 LDAP 和 Active Directory 的使用者身分。



 a| 
[[ldr-service]]本機分發路由器 (LDR)
 a| 
處理物件儲存協定請求並管理磁​​碟上的物件資料。

.細節
[%collapsible]
====
每個_組合_、_僅資料_和_僅元資料_儲存節點都包含本機分發路由器 (LDR) 服務。此服務處理內容傳輸功能，包括資料儲存、路由和請求處理。  LDR 服務透過處理資料傳輸負載和資料流量功能完成了StorageGRID系統的大部分艱苦工作。

LDR 服務處理以下任務：

* 查詢
* 資訊生命週期管理 (ILM) 活動
* 物件刪除
* 物件資料存儲
* 從另一個 LDR 服務（儲存節點）傳輸物件數據
* 資料儲存管理
* S3協定介面


LDR 服務也將每個 S3 物件對應到其唯一的 UUID。

物件儲存:: LDR 服務的底層資料儲存被劃分為固定數量的物件儲存（也稱為儲存磁碟區）。每個物件儲存都是一個單獨的掛載點。
+
--
儲存節點中的物件儲存由從 0000 到 002F 的十六進制數標識，該數字稱為磁碟區 ID。第一個物件儲存（磁碟區 0）中保留了空間，用於儲存 Cassandra 資料庫中的物件元資料；該磁碟區上的任何剩餘空間都用於儲存物件資料。所有其他物件儲存專門用於物件數據，其中包括複製的副本和擦除編碼片段。

為了確保複製副本的空間使用均勻，給定物件的物件資料將根據可用儲存空間儲存到一個物件儲存中。當物件儲存填滿容量時，剩餘的物件儲存將繼續儲存對象，直到儲存節點上沒有更多空間。

--
元資料保護:: StorageGRID將物件元資料儲存在 Cassandra 資料庫中，該資料庫與 LDR 服務互動。
+
--
為了確保冗餘並防止遺失，每個站點都保留了三個物件元資料副本。此複製不可配置且自動執行。有關詳細信息，請參閱link:../admin/managing-object-metadata-storage.html["管理對像元資料存儲"] 。

--


====


 a| 
複製狀態機（RSM）
 a| 
確保 S3 平台服務請求傳送到各自的端​​點。



 a| 
伺服器狀態監視器（SSM）
 a| 
監控作業系統和底層硬體。

|===