---
permalink: primer/what-gateway-node-is.html 
sidebar: sidebar 
keywords: gateway nodes, api gateway 
summary: 網關節點提供專用的負載平衡接口，S3 用戶端應用程式可以使用它來連接到StorageGRID。負載平衡透過在多個儲存節點之間分配工作負載來最大限度地提高速度和連接容量。網關節點是可選的。 
---
= 什麼是網關節點？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
網關節點提供專用的負載平衡接口，S3 用戶端應用程式可以使用它來連接到StorageGRID。負載平衡透過在多個儲存節點之間分配工作負載來最大限度地提高速度和連接容量。網關節點是可選的。

所有管理節點及所有網關節點均提供StorageGRID負載平衡器服務。它執行客戶端請求的傳輸層安全性 (TLS) 終止，檢查請求，並與儲存節點建立新的安全連線。負載平衡器服務無縫地將客戶端引導至最佳儲存節點，以便節點甚至整個網站的故障都是透明的。

您可以設定一個或多個負載平衡器端點來定義傳入和傳出用戶端請求將用於存取網關和管理節點上的負載平衡器服務的連接埠和網路協定（HTTPS 或 HTTP）。負載平衡器端點還定義客戶端類型（S3）、綁定模式以及可選的允許或封鎖租用戶清單。看link:../admin/managing-load-balancing.html["負載平衡的注意事項"] 。

根據需要，您可以將多個網關節點和管理節點的網路介面分組為高可用性 (HA) 群組。如果 HA 群組中的活動介面發生故障，則備份介面可以管理用戶端應用程式工作負載。看link:../admin/managing-high-availability-groups.html["管理高可用性 (HA) 組"] 。



== 網關節點的主要服務

下表顯示了網關節點的主要服務；但是，該表並未列出所有節點服務。

[cols="1a,2a"]
|===
| 服務 | 按鍵功能 


 a| 
高可用性
 a| 
管理管理節點和網關節點群組的高可用性虛擬 IP 位址。

*注意：*此服務也可在管理節點上找到。



 a| 
負載平衡器
 a| 
提供從客戶端到儲存節點的 S3 流量的第 7 層負載平衡。這是推薦的負載平衡機制。

*注意：*此服務也可在管理節點上找到。



 a| 
伺服器狀態監視器（SSM）
 a| 
監控作業系統和底層硬體。

|===