---
permalink: expand/copying-prometheus-metrics.html 
sidebar: sidebar 
keywords: prometheus, copy metrics, Admin Node expansion 
summary: 新增新的管理節點後，您可以選擇將 Prometheus 維護的歷史指標從主管理節點複製到新的管理節點。複製指標可確保管理節點之間的歷史指標保持一致。 
---
= 複製 Prometheus 指標
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新增新的管理節點後，您可以選擇將 Prometheus 維護的歷史指標從主管理節點複製到新的管理節點。複製指標可確保管理節點之間的歷史指標保持一致。

.開始之前
* 新的管理節點已安裝並正在運行。
* 你有 `Passwords.txt`文件。
* 您有配置密碼。


.關於此任務
當您新增管理節點時，軟體安裝過程會建立一個新的 Prometheus 資料庫。您可以透過將 Prometheus 資料庫從主管理節點（來源管理節點）複製到新的管理節點來保持節點之間的歷史指標一致。


NOTE: 複製 Prometheus 資料庫可能需要一個小時或更長時間。當來源管理節點上的服務停止時，某些網格管理器功能將無法使用。

.步驟
. 登入來源管理節點：
+
.. 輸入以下命令： `ssh admin@_grid_node_IP_`
.. 輸入 `Passwords.txt`文件。
.. 輸入以下命令切換到root： `su -`
.. 輸入 `Passwords.txt`文件。


. 從來源管理節點停止 Prometheus 服務： `service prometheus stop`
. 在新的管理節點上完成以下步驟：
+
.. 登入新的管理節點：
+
... 輸入以下命令： `ssh admin@_grid_node_IP_`
... 輸入 `Passwords.txt`文件。
... 輸入以下命令切換到root： `su -`
... 輸入 `Passwords.txt`文件。


.. 停止 Prometheus 服務： `service prometheus stop`
.. 將 SSH 私鑰新增至 SSH 代理程式。進入：``ssh-add``
.. 輸入 `Passwords.txt`文件。
.. 將 Prometheus 資料庫從來源管理節點複製到新的管理節點： `/usr/local/prometheus/bin/prometheus-clone-db.sh _Source_Admin_Node_IP_`
.. 出現提示時，按 *Enter* 確認您要銷毀新管理節點上的新 Prometheus 資料庫。
+
原有的Prometheus資料庫及其歷史資料複製到新的Admin Node。複製操作完成後，腳本將啟動新的管理節點。出現如下狀態：

+
`Database cloned, starting services`

.. 當您不再需要無密碼存取其他伺服器時，請從 SSH 代理程式中刪除私鑰。進入：
+
`ssh-add -D`



. 在來源管理節點上重新啟動 Prometheus 服務。
+
`service prometheus start`


