---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure 
summary: 新增儲存節點後，您可以使用擦除編碼重新平衡程序在現有儲存節點和新儲存節點之間重新指派擦除編碼片段。 
---
= 新增儲存節點後重新平衡擦除編碼數據
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新增儲存節點後，您可以使用擦除編碼 (EC) 重新平衡程序在現有儲存節點和新儲存節點之間重新指派擦除編碼片段。

.開始之前
* 您已完成新增儲存節點的擴充步驟。
* 您已審閱link:considerations-for-rebalancing-erasure-coded-data.html["重新平衡擦除編碼資料的注意事項"]。
* 您了解，此過程不會移動複製的物件數據，並且 EC 重新平衡過程在確定將擦除編碼資料移動到何處時不會考慮每個儲存節點上的複製資料使用情況。
* 你有 `Passwords.txt`文件。


.此過程運行時會發生什麼
在開始流程之前，請注意以下事項：

* 如果一個或多個磁碟區處於離線（未安裝）狀態，或處於連線（已安裝）但處於錯誤狀態，則 EC 重新平衡程序將不會啟動。
* EC 重新平衡程式暫時保留了大量儲存空間。儲存警報可能會被觸發，但會在重新平衡完成時解決。如果沒有足夠的儲存空間用於預留，EC 重新平衡程序將會失敗。當 EC 重新平衡流程完成時，無論流程失敗或成功，都會釋放儲存預留。
* 如果在 EC 重新平衡過程進行過程中捲離線，則重新平衡過程將終止。任何已移動的資料片段將保留在新位置，並且不會遺失任何資料。
+
所有捲恢復在線後，您可以重新運行該過程。

* 當 EC 重新平衡流程運作時，ILM 操作和 S3 用戶端操作的效能可能會受到影響。
+

NOTE: 如果上傳物件（或物件部分）的 S3 API 操作需要超過 24 小時才能完成，則在 EC 重新平衡過程中，上傳物件（或物件部分）的操作可能會失敗。如果適用的 ILM 規則在攝取時使用平衡或嚴格放置，則長時間的 PUT 操作將會失敗。會報如下錯誤： `500 Internal Server Error` 。

* 在此過程中，所有節點的儲存容量限制為 80%。超過此限制但仍儲存在目標資料分區以下的節點將被排除在外：
+
** 場地不平衡值
** 任何工作完成條件
+

NOTE: 目標資料分區是透過將站點的總資料除以節點數來計算的。



* *工作完成條件*。當下列任一情況成立時，EC 重新平衡程序即視為完成：
+
** 它無法再移動任何擦除編碼資料。
** 所有節點中的資料與目標資料分區的偏差在5%以內。
** 該程式已運行30天。




.步驟
. [[review_object_storage]]查看您計劃重新平衡的網站的目前物件儲存詳細資訊。
+
.. 選擇*NODES*。
.. 選擇站點中的第一個儲存節點。
.. 選擇“*儲存*”標籤。
.. 將遊標放在「已使用儲存 - 物件資料」圖表上，查看儲存節點上目前複製的資料量和擦除編碼資料量。
.. 重複這些步驟以查看網站上的其他儲存節點。


. 登入主管理節點：
+
.. 輸入以下命令： `ssh admin@_primary_Admin_Node_IP_`
.. 輸入 `Passwords.txt`文件。
.. 輸入以下命令切換到root： `su -`
.. 輸入 `Passwords.txt`文件。
+
當您以 root 身分登入時，提示字元將從 `$`到 `#`。



. 啟動程序：
+
`重新平衡資料啟動 --site "_site-name_"

+
對於“_site-name_”，指定您新增儲存節點或節點的第一個網站。括 `site-name`用引號引起來。

+
EC 重新平衡程式啟動，並傳回作業 ID。

. 複製作業 ID。
. [[view-status]]監控 EC 重新平衡過程的狀態。
+
** 若要查看單一 EC 重新平衡流程的狀態：
+
`rebalance-data status --job-id _job-id_`

+
為了 `_job-id_`，指定啟動該程序時傳回的 ID。

** 若要查看目前 EC 重新平衡程序的狀態以及任何先前完成的程序：
+
`rebalance-data status`

+
[NOTE]
====
如需有關 rebalance-data 指令的協助：

`rebalance-data --help`

====


. 根據傳回的狀態執行其他步驟：
+
** 如果 `State`是 `In progress`，EC 重新平衡操作仍在運作。您應該定期監視該過程直至其完成。
+
使用 `Site Imbalance`值來評估網站儲存節點之間的擦除碼資料使用不平衡程度。該值的範圍是 1.0 到 0，其中 0 表示擦除編碼資料的使用在站點的所有儲存節點之間完全平衡。

+
當所有節點中的資料與目標資料分區的偏差在 5% 以內時，EC 重新平衡作業即被視為完成並將停止。

** 如果 `State`是 `Success`，可選<<review_object_storage,審查對象存儲>>查看網站的更新詳情。
+
現在，網站的儲存節點之間的擦除編碼資料應該會更加平衡。

** 如果 `State`是 `Failure`：
+
... 確認站點上的所有儲存節點都已連接到電網。
... 檢查並解決可能影響這些儲存節點的任何警報。
... 重新啟動 EC 重新平衡程序：
+
`rebalance-data start –-job-id _job-id_`

... <<view-status,查看狀態>>新程序。如果 `State`仍然是 `Failure`，請聯絡技術支援。




. 如果 EC 重新平衡製程產生的負載過大（例如，攝取操作受到影響），請暫停此程序。
+
`rebalance-data pause --job-id _job-id_`

. 如果您需要終止 EC 重新平衡程序（例如，以便您可以執行StorageGRID軟體升級），請輸入以下內容：
+
`rebalance-data terminate --job-id _job-id_`

+

NOTE: 當您終止 EC 重新平衡程序時，任何已移動的資料片段都會保留在其新位置。資料不會移回原始位置。

. 如果您在多個網站使用擦除編碼，請對所有其他受影響的網站執行此程序。

