---
permalink: expand/updating-subnets-for-grid-network.html 
sidebar: sidebar 
keywords: expand, expansion, add subnets, Grid Network 
summary: 當您在擴充功能中新增網格節點或新網站時，可能需要更新或為網格網路新增子網路。 
---
= 更新網格網路的子網
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您在擴充功能中新增網格節點或新網站時，可能需要更新或為網格網路新增子網路。

StorageGRID維護用於在網格網路 (eth0) 上網格節點之間進行通訊的網路子網路清單。這些項目包括StorageGRID系統中每個站點用於網格網路的子網路以及用於 NTP、DNS、LDAP 或透過網格網路閘道存取的其他外部伺服器的任何子網路。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 你有link:../admin/admin-group-permissions.html["維護或 Root 存取權限"]。
* 您有配置密碼。
* 您擁有要設定的子網路的網路位址（以 CIDR 表示法表示）。


.關於此任務
如果任何新節點在先前未使用的子網路上具有網格網路 IP 位址，則必須在開始擴充之前將新子網路新增至網格網路子網路清單。否則，您將必須取消擴展，新增新的子網，然後重新開始該過程。

[NOTE]
====
請勿將包含下列 IPv4 位址的子網路用於任何節點的網格網路、管理網路或用戶端網路：

* 192,168,130,101
* 192,168,131,101
* 192,168,130,102
* 192,168,131,102
* 198.51.100.2
* 198.51.100.4


例如，不要對任何節點的網格網路、管理網路或客戶端網路使用下列子網路範圍：

* 192.168.130.0/24，因為此子網路範圍包含 IP 位址 192.168.130.101 和 192.168.130.102
* 192.168.131.0/24，因為此子網路範圍包含 IP 位址 192.168.131.101 和 192.168.131.102
* 198.51.100.0/24，因為此子網路範圍包含 IP 位址 198.51.100.2 和 198.51.100.4


====
.步驟
. 選擇*維護* > *網路* > *電網網路*。
. 選擇「新增另一個子網路」以 CIDR 表示法新增子網路。
+
例如，輸入 `10.96.104.0/22`。

. 輸入配置密碼，然後選擇*儲存*。
. 等待更改套用完畢，然後下載新的恢復包。
+
.. 選擇*維護* > *系統* > *恢復包*。
.. 輸入*配置密碼*。
+

CAUTION: 復原包檔案必須是安全的，因為它包含可用於從StorageGRID系統取得資料的加密金鑰和密碼。它也用於恢復主管理節點。





您指定的子網路將自動為您的StorageGRID系統設定。
