---
permalink: troubleshoot/troubleshooting-admin-node-and-user-interface-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot admin node issues, how to troubleshoot user interface issues 
summary: 您可以執行多項任務來協助確定與管理節點和StorageGRID使用者介面相關的問題的來源。 
---
= 解決管理節點和使用者介面問題
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以執行多項任務來協助確定與管理節點和StorageGRID使用者介面相關的問題的來源。



== 管理節點登入錯誤

如果您在登入StorageGRID管理節點時遇到錯誤，則您的系統可能有問題link:../troubleshoot/troubleshooting-network-hardware-and-platform-issues.html["聯網"]或者 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/troubleshooting-hardware-installation-sg100-and-sg1000.html["硬體"^]問題，一個問題link:../primer/what-admin-node-is.html["管理節點服務"]或link:../maintain/recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html["Cassandra 資料庫問題"]在連接的儲存節點上。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 你有 `Passwords.txt`文件。
* 你有link:../admin/admin-group-permissions.html["特定存取權限"]。


.關於此任務
如果您在嘗試登入管理節點時看到以下任何錯誤訊息，請使用這些故障排除指南：

* `Your credentials for this account were invalid. Please try again.`
* `Waiting for services to start...`
* `Internal server error. The server encountered an error and could not complete your request. Please try again. If the problem persists, contact Technical Support.`
* `Unable to communicate with server. Reloading page...`


.步驟
. 等待 10 分鐘，然後嘗試再次登入。
+
如果錯誤未自動解決，請前往下一個步驟。

. 如果您的StorageGRID系統有多個管理節點，請嘗試從另一個管理節點登入網格管理員以檢查不可用管理節點的狀態。
+
** 如果您能夠登錄，您可以使用*Dashboard*、*NODES*、*Alerts* 和 *SUPPORT* 選項來協助確定錯誤的原因。
** 如果您只有一個管理節點或仍然無法登錄，請轉到下一步。


. 確定節點的硬體是否處於離線狀態。
. 如果您的StorageGRID系統啟用了單一登入 (SSO)，請參閱link:../admin/configuring-sso.html["配置單一登入"]。
+
您可能需要暫時停用並重新啟用單一管理節點的 SSO 來解決任何問題。

+

NOTE: 如果啟用了 SSO，則您無法使用受限連接埠登入。您必須使用連接埠 443。

. 確定您使用的帳戶是否屬於聯合使用者。
+
如果聯合使用者帳戶不起作用，請嘗試以本機使用者（例如 root）身分登入網格管理員。

+
** 如果本地用戶可以登入：
+
... 查看警報。
... 選擇*配置* > *存取控制* > *身份聯合*。
... 按一下「測試連線」以驗證 LDAP 伺服器的連線設定。
... 如果測試失敗，請解決任何配置錯誤。


** 如果本機使用者無法登錄，且您確信憑證正確，請前往下一步。


. 使用安全外殼（ssh）登入管理節點：
+
.. 輸入以下命令： `ssh admin@Admin_Node_IP`
.. 輸入 `Passwords.txt`文件。
.. 輸入以下命令切換到root： `su -`
.. 輸入 `Passwords.txt`文件。
+
當您以 root 身分登入時，提示字元將從 `$`到 `#`。



. 查看網格節點上所有服務運行狀態： `storagegrid-status`
+
確保 nms、mi、nginx 和 mgmt api 服務都在運作。

+
如果服務狀態發生變化，輸出會立即更新。

+
....
$ storagegrid-status
Host Name                      99-211
IP Address                     10.96.99.211
Operating System Kernel        4.19.0         Verified
Operating System Environment   Debian 10.1    Verified
StorageGRID Webscale Release   11.4.0         Verified
Networking                                    Verified
Storage Subsystem                             Verified
Database Engine                5.5.9999+default Running
Network Monitoring             11.4.0         Running
Time Synchronization           1:4.2.8p10+dfsg Running
ams                            11.4.0         Running
cmn                            11.4.0         Running
nms                            11.4.0         Running
ssm                            11.4.0         Running
mi                             11.4.0         Running
dynip                          11.4.0         Running
nginx                          1.10.3         Running
tomcat                         9.0.27         Running
grafana                        6.4.3          Running
mgmt api                       11.4.0         Running
prometheus                     11.4.0         Running
persistence                    11.4.0         Running
ade exporter                   11.4.0         Running
alertmanager                   11.4.0         Running
attrDownPurge                  11.4.0         Running
attrDownSamp1                  11.4.0         Running
attrDownSamp2                  11.4.0         Running
node exporter                  0.17.0+ds      Running
sg snmp agent                  11.4.0         Running
....
. 確認 nginx-gw 服務正在運行 `# service nginx-gw status`
. [[use_Lumberjack_to_collect_logs]]使用 Lumberjack 收集日誌： `# /usr/local/sbin/lumberjack.rb`
+
如果驗證失敗發生在過去，您可以使用 --start 和 --end Lumberjack 腳本選項來指定適當的時間範圍。使用 lumberjack -h 了解這些選項的詳細資訊。

+
終端的輸出指示日誌存檔已複製到哪裡。

. [[review_logs, start=10]]查看以下日誌：
+
** `/var/local/log/bycast.log`
** `/var/local/log/bycast-err.log`
** `/var/local/log/nms.log`
** `**/*commands.txt`


. 如果您無法識別管理節點的任何問題，請發出以下任一命令來確定在您的網站上執行 ADC 服務的三個儲存節點的 IP 位址。通常，這些是站點上安裝的前三個儲存節點。
+
[listing]
----
# cat /etc/hosts
----
+
[listing]
----
# gpt-list-services adc
----
+
管理節點在驗證過程中使用 ADC 服務。

. 從管理節點，使用 ssh 登入每個 ADC 儲存節點，使用您確定的 IP 位址。
. 查看網格節點上所有服務運行狀態： `storagegrid-status`
+
確保 idnt、acct、nginx 和 cassandra 服務都在運作。

. 重複步驟<<use_Lumberjack_to_collect_logs,使用 Lumberjack 收集日誌>>和<<review_logs,審查日誌>>查看儲存節點上的日誌。
. 如果您無法解決問題，請聯絡技術支援。
+
將您收集的日誌提供給技術支援。另請參閱link:../monitor/logs-files-reference.html["日誌檔參考"] 。





== 使用者介面問題

StorageGRID軟體升級後，網格管理器或租用戶管理器的使用者介面可能無法如預期回應。

.步驟
. 確保你使用的是link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
. 清除您的網頁瀏覽器快取。
+
清除快取會刪除先前版本的StorageGRID軟體所使用的過時資源，並允許使用者介面再次正常運作。有關說明，請參閱 Web 瀏覽器的文件。


