---
permalink: ilm/advantages-disadvantages-of-ingest-options.html 
sidebar: sidebar 
keywords: ingest options, balance ingest, strict ingest, dual commit ingest 
summary: 了解在攝取時保護資料的三個選項（平衡、嚴格或雙重提交）各自的優缺點可以幫助您決定選擇哪一個作為 ILM 規則。 
---
= 攝取選項的優點、缺點和局限性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解在攝取時保護資料的三個選項（平衡、嚴格或雙重提交）各自的優缺點可以幫助您決定選擇哪一個作為 ILM 規則。

有關收錄選項的概述，請參閱link:data-protection-options-for-ingest.html["收錄選項"]。



== 平衡和嚴格選項的優勢

與在攝取期間建立臨時副本的雙重提交相比，兩個同步放置選項可以提供以下優點：

* *更好的資料安全性*：物件資料依照 ILM 規則的放置指令立即受到保護，可以配置為防止各種故障情況，包括多個儲存位置的故障。雙重提交只能防止遺失單一本機副本。
* *更有效率的網格操作*：每個物件在被攝取時只處理一次。由於StorageGRID系統不需要追蹤或刪除臨時副本，因此處理負載更少，消耗的資料庫空間也更少。
* *(平衡)建議*：平衡選項提供最佳的 ILM 效率。建議使用平衡選項，除非需要嚴格的攝取行為或網格滿足使用雙重提交的所有標準。
* *（嚴格）關於物件位置的確定性*：嚴格選項保證物件根據 ILM 規則中的放置說明立即儲存。




== 平衡和嚴格選項的缺點

與雙重提交相比，平衡和嚴格選項有一些缺點：

* *更長的客戶端攝取時間*：客戶端攝取延遲可能會更長。當您使用「平衡」或「嚴格」選項時，直到建立並儲存所有擦除編碼片段或複製副本後，「攝取成功」訊息才會返回給用戶端。然而，物件資料很可能會更快到達其最終位置。
* *（嚴格）更高的攝取失敗率*：使用嚴格選項時，只要StorageGRID無法立即製作 ILM 規則中指定的所有副本，攝取就會失敗。如果所需的儲存位置暫時離線或網路問題導致站點之間複製物件延遲，您可能會看到高攝取失敗率。
* *（嚴格）S3 分段上傳位置在某些情況下可能不符合預期*：使用嚴格設定時，您希望物件按照 ILM 規則的描述進行放置，否則攝取將失敗。但是，對於 S3 分段上傳，在攝取物件時會針對物件的每一部分對 ILM 進行評估，並且在分段上傳完成時對整個物件進行評估。在以下情況下，這可能會導致展示位置與您預期的不同：
+
** *如果在 S3 分段上傳過程中 ILM 發生變化*：由於每個部分都是根據攝取該部分時有效的規則放置的，因此在分段上傳完成時，對象的某些部分可能不符合當前的 ILM 要求。在這些情況下，物件的攝取不會失敗。相反，任何未正確放置的部件都會排隊等待 ILM 重新評估，然後移動到正確的位置。
** *當 ILM 規則按大小過濾時*：當評估某個部分的 ILM 時， StorageGRID會以部分的大小進行過濾，而不是物件的大小。這意味著物件的各個部分可以儲存在不滿足物件整體的 ILM 要求的位置。例如，如果規則指定所有 10 GB 或更大的物件都儲存在 DC1，而所有較小的物件都儲存在 DC2，則在攝取 10 部分分段上傳的每個 1 GB 部分時都儲存在 DC2。當對物件進行 ILM 評估時，物件的所有部分都會移至 DC1。


* *（嚴格）當物件標籤或元資料更新且無法進行新要求的放置時，攝取不會失敗*：使用嚴格，您希望物件按照 ILM 規則的描述放置，否則攝取會失敗。但是，當您更新已儲存在網格中的物件的元資料或標籤時，該物件不會被重新擷取。這表示更新觸發的物件位置的任何變更都不會立即生效。當 ILM 由正常後台 ILM 程序重新評估時，會進行放置變更。如果無法進行所需的位置變更（例如，因為新需要的位置不可用），則更新後的物件將保留其目前位置，直到可以進行位置變更為止。




== 使用“平衡”和“嚴格”選項放置物件的限制

平衡或嚴格選項不能用於具有以下任何放置指令的 ILM 規則：

* 在第 0 天放置在雲端儲存池中。
* 當規則以使用者定義的建立時間作為參考時間時，雲端儲存池中的位置。


存在這些限制是因為StorageGRID無法同步複製至雲端儲存池，且使用者定義的建立時間可以解析為現在。



== ILM 規則和一致性如何相互作用以影響資料保護

您的 ILM 規則和一致性選擇都會影響物件的保護方式。這些設定可以相互作用。

例如，為 ILM 規則選擇的攝取行為會影響物件副本的初始位置，而儲存物件時使用的一致性會影響物件元資料的初始位置。由於StorageGRID需要存取物件的資料和元資料來滿足客戶端請求，因此為一致性和攝取行為選擇相符的保護等級可以提供更好的初始資料保護和更可預測的系統回應。

以下是StorageGRID中可用的一致性值的簡要摘要：

* *全部*：所有節點立即接收物件元數據，否則請求將失敗。
* *Strong-global*：物件元資料立即分發到所有網站。保證所有網站上所有客戶端請求的讀寫一致性。
* *強站點*：物件元資料立即分發到站點的其他節點。保證站點內所有客戶端請求的讀寫一致性。
* *Read-after-new-write*：為新物件提供read-after-write一致性，並為物件更新提供最終一致性。提供高可用性和資料保護保證。在大多數情況下建議使用。
* *可用*：為新物件和物件更新提供最終一致性。對於 S3 儲存桶，僅在需要時使用（例如，對於包含很少讀取的日誌值的儲存桶，或對於不存在的鍵的 HEAD 或 GET 操作）。不支援 S3 FabricPool儲存桶。



NOTE: 在選擇一致性值之前，link:../s3/consistency-controls.html["閱讀一致性的完整描述"] 。在更改預設值之前，您應該了解其優點和限制。



== 一致性和 ILM 規則如何交互的範例

假設您有一個雙站點網格，具有以下 ILM 規則和以下一致性：

* *ILM 規則*：建立兩個物件副本，一個在本機站點，一個在遠端站點。使用嚴格的攝取行為。
* *一致性*：強全域（物件元資料立即分發到所有站點）。


當客戶端將物件儲存到網格時， StorageGRID會複製兩個物件並將元資料分發到兩個站點，然後再將成功返回給客戶端。

在接收成功訊息時，物件將受到完全保護，不會遺失。例如，如果本機站點在攝取後不久遺失，則物件資料和物件元資料的副本仍然存在於遠端站點。該物件完全可檢索。

如果您使用相同的 ILM 規則和強站點一致性，則用戶端可能會在物件資料複製到遠端站點之後但在物件元資料分發到那裡之前收到成功訊息。在這種情況下，物件元資料的保護等級與物件資料的保護等級不符。如果本地站點在攝取後不久遺失，則物件元資料就會遺失。無法檢索該物件。

一致性和 ILM 規則之間的相互關係可能很複雜。如果您需要協助，請聯絡NetApp 。

.相關資訊
link:example-5-ilm-rules-and-policy-for-strict-ingest-behavior.html["範例 5：針對嚴格攝取行為的 ILM 規則和策略"]
