---
permalink: ilm/example-7-compliant-ilm-policy-for-s3-object-lock.html 
sidebar: sidebar 
keywords: ILM policy,S3 Object Lock 
summary: 您可以使用本範例中的 S3 儲存桶、ILM 規則和 ILM 策略作為起點來定義 ILM 策略，以滿足啟用了 S3 物件鎖定的儲存桶中物件的物件保護和保留要求。 
---
= 範例 7：符合 S3 物件鎖定的 ILM 策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用本範例中的 S3 儲存桶、ILM 規則和 ILM 策略作為起點來定義 ILM 策略，以滿足啟用了 S3 物件鎖定的儲存桶中物件的物件保護和保留要求。


NOTE: 如果您在先前的StorageGRID版本中使用了舊版合規功能，則您也可以使用此範例來協助管理啟用了舊版合規功能的任何現有儲存桶。


CAUTION: 以下 ILM 規則和策略僅作為範例。配置 ILM 規則的方法有很多種。在啟動新策略之前，請先進行模擬以確認它能夠如預期運作以保護內容免於遺失。

.相關資訊
* link:managing-objects-with-s3-object-lock.html["使用 S3 對象鎖管理對象"]
* link:creating-ilm-policy.html["建立 ILM 策略"]




== S3 物件鎖定範例的儲存桶和對象

在此範例中，名為 ABC 銀行的 S3 租用戶帳戶使用租用戶管理器建立了一個啟用了 S3 物件鎖的儲存桶，用於儲存重要的銀行記錄。

[cols="2a,2a"]
|===
| 桶定義 | 範例值 


 a| 
租用戶帳戶名稱
 a| 
農業銀行



 a| 
儲存桶名稱
 a| 
銀行記錄



 a| 
桶區域
 a| 
us-east-1（預設）

|===
新增至銀行記錄儲存桶的每個物件和物件版本將使用下列值 `retain-until-date`和 `legal hold`設定.

[cols="1a,2a"]
|===
| 為每個對象設置 | 範例值 


 a| 
`retain-until-date`
 a| 
「2030-12-30T23:59:59Z」（2030 年 12 月 30 日）

每個物件版本都有自己的 `retain-until-date`環境。此設定可以增加，但不能減少。



 a| 
`legal hold`
 a| 
「OFF」（無效）

在保留期內，可以隨時對任何物件版本實施或解除合法保留。如果物件處於合法保留狀態，則即使 `retain-until-date`已達到。

|===


== S3 物件鎖定的 ILM 規則 1 範例：具有儲存桶匹配​​的擦除編碼設定檔

此範例 ILM 規則僅適用於名為 Bank of ABC 的 S3 租用戶帳戶。它匹配 `bank-records`儲存桶，然後使用擦除編碼將物件儲存在三個資料中心站點的儲存節點上，採用 6+3 擦除編碼設定檔。此規則滿足啟用 S3 物件鎖定的儲存桶的要求：從第 0 天到永遠，在儲存節點上保留一份副本，使用攝取時間作為參考時間。

[cols="1a,2a"]
|===
| 規則定義 | 範例值 


 a| 
規則名稱
 a| 
符合規則：銀行記錄儲存桶中的 EC 物件 - ABC 銀行



 a| 
租戶帳戶
 a| 
農業銀行



 a| 
儲存桶名稱
 a| 
`bank-records`



 a| 
進階過濾器
 a| 
物件大小 (MB) 大於 1

*注意：*此過濾器可確保 1 MB 或更小的物件不使用擦除編碼。

|===
[cols="1a,2a"]
|===
| 規則定義 | 範例值 


 a| 
參考時間
 a| 
攝取時間



 a| 
展示位置
 a| 
從第 0 天開始永久存儲



 a| 
擦除編碼配置文件
 a| 
* 在三個資料中心站點的儲存節點上建立擦除編碼副本
* 採用 6+3 擦除編碼方案


|===


== S3 物件鎖定的 ILM 規則 2 範例：不合規規則

此範例 ILM 規則最初在儲存節點上儲存兩個複製的物件副本。一年後，它會將一份副本永久儲存在雲端儲存池中。由於此規則使用雲端儲存池，因此它不合規且不適用於啟用了 S3 物件鎖的儲存桶中的物件。

[cols="1a,2a"]
|===
| 規則定義 | 範例值 


 a| 
規則名稱
 a| 
不合規規則：使用雲端儲存池



 a| 
租戶帳戶
 a| 
未指定



 a| 
儲存桶名稱
 a| 
未指定，但僅適用於未啟用 S3 物件鎖定（或舊版合規功能）的儲存桶。



 a| 
進階過濾器
 a| 
未指定

|===
[cols="1a,2a"]
|===
| 規則定義 | 範例值 


 a| 
參考時間
 a| 
攝取時間



 a| 
展示位置
 a| 
* 在第 0 天，在資料中心 1 和資料中心 2 的儲存節點上保留兩個副本，為期 365 天
* 一年後，永久保留一份副本在雲端儲存池中


|===


== S3 物件鎖定的 ILM 規則 3 範例：預設規則

此範例 ILM 規則將物件資料複製到兩個資料中心的儲存池。此合規規則被設計為 ILM 策略中的預設規則。它不包含任何過濾器，不使用非當前參考時間，並滿足啟用 S3 物件鎖定的儲存桶的要求：從第 0 天到永遠，兩個物件副本都保留在儲存節點上，使用 Ingest 作為參考時間。

[cols="1a,2a"]
|===
| 規則定義 | 範例值 


 a| 
規則名稱
 a| 
預設合規規則：兩個副本兩個資料中心



 a| 
租戶帳戶
 a| 
未指定



 a| 
儲存桶名稱
 a| 
未指定



 a| 
進階過濾器
 a| 
未指定

|===
[cols="1a,2a"]
|===
| 規則定義 | 範例值 


 a| 
參考時間
 a| 
攝取時間



 a| 
展示位置
 a| 
從第 0 天到永遠，保留兩個副本 - 一個在資料中心 1 的儲存節點上，另一個在資料中心 2 的儲存節點上。

|===


== 符合 S3 物件鎖定的 ILM 策略範例

若要建立能夠有效保護系統中的所有物件（包括啟用了 S3 物件鎖的儲存桶中的物件）的 ILM 策略，您必須選擇滿足所有物件的儲存需求的 ILM 規則。然後，您必須模擬並啟動該策略。



=== 在策略中新增規則

在此範例中，ILM 策略包含三個 ILM 規則，順序如下：

. 一項合規規則，使用擦除編碼來保護啟用了 S3 物件鎖定的特定儲存桶中大於 1 MB 的物件。物件從第 0 天起一直儲存在儲存節點上。
. 不合規的規則是在儲存節點上建立兩個複製的物件副本，為期一年，然後將物件副本永久移動到雲端儲存池。此規則不適用於啟用了 S3 物件鎖定的儲存桶，因為它使用雲端儲存池。
. 預設合規規則是從第 0 天到永遠在儲存節點上建立兩個複製物件副本。




=== 模擬策略

在向策略中新增規則、選擇預設相容規則並安排其他規則後，您應該透過測試啟用了 S3 物件鎖定的儲存桶和其他儲存桶中的物件來模擬該策略。例如，當您模擬範例策略時，您會期望測試物件按如下方式進行評估：

* 第一條規則將僅符合 ABC 銀行租戶的儲存桶銀行記錄中大於 1 MB 的測試對象。
* 第二條規則將符合所有其他租用戶帳戶的所有不合規儲存桶中的所有物件。
* 預設規則將匹配這些物件：
+
** ABC 銀行租戶的儲存桶銀行記錄中 1 MB 或更小的物件。
** 為所有其他租用戶帳戶啟用了 S3 物件鎖的任何其他儲存桶中的物件。






=== 啟動策略

當您完全滿意新策略按預期保護物件資料時，您可以啟動它。
