---
permalink: ilm/guidelines-for-creating-storage-pools.html 
sidebar: sidebar 
keywords: storage pool guidelines 
summary: 配置和使用儲存池，透過在多個站點之間分發資料來防止資料遺失。複製副本和擦除編碼副本需要不同的儲存池配置。 
---
= 建立儲存池的指南
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
配置和使用儲存池，透過在多個站點之間分發資料來防止資料遺失。複製副本和擦除編碼副本需要不同的儲存池配置。

看link:using-multiple-storage-pools-for-cross-site-replication.html["使用複製和擦除編碼實現網站遺失保護的範例"] 。



== 所有儲存池的指南

* 使儲存池配置盡可能簡單。不要建立超過需要的儲存池。
* 建立具有盡可能多的節點的儲存池。每個儲存池應包含兩個或更多節點。如果某個節點不可用，則節點不足的儲存池可能會導致 ILM 積壓。
* 避免建立或使用重疊的儲存池（包含一個或多個相同的節點）。如果儲存池重疊，則可能會在同一個節點上儲存多個物件資料的副本。
* 一般來說，請勿使用所有儲存節點StorageGRID池（ StorageGRID 11.6 及更早版本）或所有站點站點。這些項目會自動更新以包含您在擴充功能中新增的任何新站點，這可能不是您想要的行為。




== 用於複製副本的儲存池指南

* 對於網站遺失保護，使用link:what-replication-is.html["複製"]，在link:create-ilm-rule-define-placements.html["每個 ILM 規則的放置說明"]。
+
在StorageGRID安裝期間，會自動為每個網站建立一個儲存池。

+
為每個網站使用儲存池可確保複製的物件副本準確地放置在您期望的位置（例如，每個網站的每個物件都有一個副本，以防止網站遺失）。

* 如果在擴充功能中新增站點，請建立僅包含新站點的新儲存池。然後，link:working-with-ilm-rules-and-ilm-policies.html#edit-an-ilm-rule["更新 ILM 規則"]控制哪些物件儲存在新站點上。
* 如果副本數小於儲存池數，系統將指派副本以平衡池之間的磁碟使用情況。
* 如果儲存池重疊（包含相同的儲存節點），則物件的所有副本可能僅保存在一個網站上。您必須確保所選的儲存池不包含相同的儲存節點。




== 用於擦除編碼副本的儲存池指南

* 對於網站遺失保護，使用link:what-erasure-coding-is.html["擦除編碼"]，建立至少由三個網站組成的儲存池。如果儲存池僅包含兩個站點，則無法使用該儲存池進行擦除編碼。對於具有兩個網站的儲存池，沒有可用的擦除編碼方案。
* 儲存池中包含的儲存節點和站點的數量決定了link:what-erasure-coding-schemes-are.html["擦除編碼方案"]可用。
* 如果可能，儲存池應包含超過您選擇的擦除編碼方案所需的最小儲存節點數量。例如，如果您使用 6+3 擦除編碼方案，則必須至少有九個儲存節點。但是，建議每個站點至少有一個額外的儲存節點。
* 盡可能均勻地在各個站點間分佈儲存節點。例如，為了支援 6+3 擦除編碼方案，請配置一個包含三個網站的至少三個儲存節點的儲存池。
* 如果您有高吞吐量需求，且網站之間的網路延遲大於 100 毫秒，則不建議使用包含多個網站的儲存池。隨著延遲的增加，由於 TCP 網路吞吐量的下降， StorageGRID創建、放置和檢索物件片段的速率急劇下降。
+
吞吐量的下降會影響物件攝取和檢索的最大可實現速率（當選擇「平衡」或「嚴格」作為攝取行為時）或可能導致 ILM 佇列積壓（當選擇「雙重提交」作為攝取行為時）。看link:what-ilm-rule-is.html#ilm-rule-ingest-behavior["ILM 規則攝取行為"] 。

+

NOTE: 如果您的網格僅包含一個站點，則您將無法使用所有儲存節點StorageGRID池（ StorageGRID 11.6 及更早版本）或擦除編碼設定檔中的所有站點站點。此行為可防止新增第二個網站時設定檔變得無效。


