---
permalink: ilm/how-object-retention-is-determined.html 
sidebar: sidebar 
keywords: how object retention is determined 
summary: StorageGRID為網格管理員和個人租用戶用戶提供了指定儲存物件時間的選項。一般來說，租戶使用者提供的任何保留說明都優先於網格管理員提供的保留說明。 
---
= 如何確定對象保留
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID為網格管理員和個人租用戶用戶提供了指定儲存物件時間的選項。一般來說，租戶使用者提供的任何保留說明都優先於網格管理員提供的保留說明。



== 租用戶用戶如何控制對象保留

租用戶用戶可以使用這些方法來控制其物件在StorageGRID中儲存的時間：

* 如果為網格啟用了全域 S3 物件鎖定設置，則 S3 租用戶用戶可以建立啟用 S3 物件鎖定的儲存桶，然後為每個儲存桶選擇 *預設保留期*。
* 如果為網格啟用了全域 S3 物件鎖定設置，則 S3 租用戶可以建立啟用了 S3 物件鎖定的儲存桶，然後使用 S3 REST API 為新增至該儲存桶的每個物件版本指定保留截止日期和合法保留設定。
+
** 處於合法保留狀態的物件版本無法透過任何方法刪除。
** 在達到物件版本的保留截止日期之前，無法透過任何方法刪除該版本。
** 啟用 S3 物件鎖的儲存桶中的物件將被 ILM「永久」保留。但是，在達到保留期限後，物件版本可能會因客戶端請求或儲存桶生命週期到期而被刪除。看link:managing-objects-with-s3-object-lock.html["使用 S3 對象鎖管理對象"] 。


* S3 租用戶用戶可以向其儲存桶新增指定到期作業的生命週期配置。如果存在儲存桶生命週期， StorageGRID會儲存一個對象，直到滿足到期作業中指定的日期或天數，除非用戶端先刪除該對象。看link:../s3/create-s3-lifecycle-configuration.html["建立 S3 生命週期配置"] 。
* S3 用戶端可以發出刪除物件請求。在決定是否刪除或保留物件時， StorageGRID始終優先考慮用戶端刪除請求，而不是 S3 儲存桶生命週期或 ILM。




== 網格管理員如何控制物件保留

網格管理員可以使用這些方法來控制物件保留：

* 為每個租用戶設定 S3 物件鎖最大保留期。然後，租用戶用戶可以為每個儲存桶設定一個預設保留期。此儲存桶中任何新攝取的物件也必須遵守最大保留期限（物件的保留截止日期）。
* 建立 ILM 放置指令來控制物件的儲存時間。當物件與 ILM 規則相符時， StorageGRID會儲存這些對象，直到 ILM 規則中的最後一個時段過去。如果放置指令指定為“永遠”，則物件將被無限期保留。
* 無論誰控制物件保留多長時間，ILM 設定都會控制儲存哪些類型的物件副本（複製或擦除編碼）以及副本所在的位置（儲存節點或雲端儲存池）。




== S3 儲存桶生命週期和 ILM 如何交互

配置 S3 儲存桶生命週期後，生命週期到期作業將覆寫與生命週期過濾器相符的物件的 ILM 策略。因此，即使放置該物件的任何 ILM 指令已失效，該物件仍可能保留在網格上。



== 物件保留的範例

為了更好地理解 S3 物件鎖、儲存桶生命週期設定、客戶端刪除請求和 ILM 之間的交互，請考慮以下範例。



=== 範例 1：S3 儲存桶生命週期比 ILM 保留物件的時間更長

工業光魔:: 保存兩份，保存期限為1年（365天）
儲存桶生命週期:: 對像在 2 年（730 天）內過期
結果:: StorageGRID儲存該物件 730 天。  StorageGRID使用儲存桶生命週期設定來決定是否刪除或保留物件。



NOTE: 如果儲存桶生命週期指定物件的保存時間應比 ILM 指定的時間長，則StorageGRID會在決定要儲存的副本數量和類型時繼續使用 ILM 放置指令。在此範例中，物件的兩個副本將從第 366 天到第 730 天繼續儲存在StorageGRID中。



=== 範例 2：S3 儲存桶生命週期在 ILM 之前使物件過期

工業光魔:: 保存兩份，保存期限為 2 年（730 天）
儲存桶生命週期:: 對像在 1 年（365 天）內過期
結果:: StorageGRID在第 365 天後刪除該物件的兩個副本。




=== 範例 3：用戶端刪除覆蓋儲存桶生命週期和 ILM

工業光魔:: 在儲存節點上永久儲存兩個副本
儲存桶生命週期:: 對像在 2 年（730 天）內過期
客戶端刪除請求:: 第 400 天發布
結果:: StorageGRID回應用戶端刪除請求，在第 400 天刪除該物件的兩個副本。




=== 範例 4：S3 物件鎖定覆蓋客戶端刪除請求

S3 對象鎖:: 物件版本的保留截止日期為 2026-03-31。合法保留無效。
符合 ILM 規則:: 在儲存節點上永久儲存兩個副本
客戶端刪除請求:: 發佈日期：2024-03-31
結果:: StorageGRID不會刪除物件版本，因為保留截止日期仍為 2 年。

