---
permalink: ilm/managing-objects-with-s3-object-lock.html 
sidebar: sidebar 
keywords: s3 object lock, manage objects with object lock 
summary: 身為網格管理員，您可以為StorageGRID系統啟用 S3 物件鎖定並實作相容的 ILM 策略，以協助確保特定 S3 儲存桶中的物件在指定時間內不會被刪除或覆寫。 
---
= 使用 S3 對象鎖管理對象
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
身為網格管理員，您可以為StorageGRID系統啟用 S3 物件鎖定並實作相容的 ILM 策略，以協助確保特定 S3 儲存桶中的物件在指定時間內不會被刪除或覆寫。



== 什麼是 S3 物件鎖？

StorageGRID S3 物件鎖定功能是一種物件保護解決方案，相當於 Amazon Simple Storage Service (Amazon S3) 中的 S3 物件鎖定。

當為StorageGRID系統啟用全域 S3 物件鎖定設定時，S3 租用戶帳戶可以建立啟用或未啟用 S3 物件鎖定的儲存桶。如果儲存桶啟用了 S3 物件鎖，則需要儲存桶版本控制，並且會自動啟用。

*沒有 S3 物件鎖的儲存桶*只能包含未指定保留設定的物件。任何攝取的物件都不會有保留設定。

*具有 S3 物件鎖定的儲存桶*可以包含由 S3 用戶端應用程式指定的具有或不具有保留設定的物件。一些攝取的物件將具有保留設定。

*配置了 S3 物件鎖定和預設保留的儲存桶*可以擁有指定了保留設定的上傳物件和不帶保留設定的新物件。新物件使用預設設置，因為尚未在物件層級配置保留設定。

實際上，當配置預設保留時，所有新攝取的物件都有保留設定。沒有物件保留設定的現有物件不受影響。



=== 保留模式

StorageGRID S3 物件鎖定功能支援兩種保留模式，以對物件套用不同層級的保護。這些模式相當於 Amazon S3 保留模式。

* 在合規模式下：
+
** 在達到保留截止日期之前，無法刪除該物件。
** 物件的保留截止日期可以增加，但不能減少。
** 在達到該日期之前，不能刪除物件的保留截止日期。


* 在治理模式下：
+
** 具有特殊權限的使用者可以在請求中使用繞過標頭來修改某些保留設定。
** 這些用戶可以在達到保留截止日期之前刪除物件版本。
** 這些使用者可以增加、減少或刪除物件的保留期限。






=== 物件版本的保留設定

如果在建立儲存桶時啟用了 S3 物件鎖定，則使用者可以使用 S3 用戶端應用程式選擇性地為新增至儲存桶的每個物件指定以下保留設定：

* *保留模式*：合規或治理。
* *保留至日期*：如果對象版本的保留至日期在未來，則可以檢索該對象，但不能刪除它。
* *合法保留*：對物件版本套用合法保留會立即鎖定該物件。例如，您可能需要對與調查或法律糾紛相關的對象實施法律保留。合法保留沒有到期日，但會一直有效，直到明確取消。合法保留與保留截止日期無關。
+

NOTE: 如果某個物件處於合法保留之下，則無論其保留模式為何，任何人都無法刪除該物件。

+
有關對象設定的詳細信息，請參閱link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 設定 S3 物件鎖"]。





=== 儲存桶的預設保留設定

如果在建立儲存桶時啟用了 S3 物件鎖定，使用者可以選擇為儲存桶指定以下預設設定：

* *預設保留模式*：合規或治理。
* *預設保留期*：新增至此儲存桶的新物件版本應保留多長時間（從新增之日起）。


預設儲存桶設定僅適用於沒有自己的保留設定的新物件。新增或變更這些預設設定時，現有的儲存桶物件不會受到影響。

看link:../tenant/creating-s3-bucket.html["建立 S3 儲存桶"]和link:../tenant/update-default-retention-settings.html["更新 S3 物件鎖定預設保留"]。



== S3 物件鎖定與舊版合規性的比較

S3 物件鎖定取代了早期StorageGRID版本中提供的合規性功能。由於 S3 物件鎖定功能符合 Amazon S3 要求，因此它棄用了專有的StorageGRID合規性功能，後者現在被稱為「舊版合規性」。


NOTE: 全域合規性設定已被棄用。如果您使用先前版本的StorageGRID啟用此設置，則 S3 物件鎖定設定將自動啟用。您可以繼續使用StorageGRID來管理現有相容儲存桶的設定；但是，您無法建立新的相容儲存桶。有關詳細信息，請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp知識庫：如何在StorageGRID 11.5 中管理舊版相容儲存桶"^]。

如果您在先前版本的StorageGRID中使用了舊版合規功能，請參閱下表以了解它與StorageGRID中的 S3 物件鎖定功能的比較。

[cols="1a,1a,1a"]
|===
|  | S3 對象鎖 | 合規性（遺留） 


 a| 
如何在全球範圍內啟用該功能？
 a| 
從網格管理器中，選擇 *配置* > *系統* > *S3 物件鎖定*。
 a| 
不再支援。



 a| 
如何為儲存桶啟用該功能？
 a| 
使用者在使用租用戶管理器、租用戶管理 API 或 S3 REST API 建立新儲存桶時必須啟用 S3 物件鎖定。
 a| 
不再支援。



 a| 
是否支援儲存桶版本控制？
 a| 
是的。儲存桶版本控制是必需的，並且在為儲存桶啟用 S3 物件鎖定時會自動啟用。
 a| 
不。



 a| 
如何設定對象保留？
 a| 
使用者可以為每個物件版本設定保留截止日期，也可以為每個儲存桶設定預設保留期。
 a| 
使用者必須為整個儲存桶設定保留期。保留期適用於儲存桶中的所有物件。



 a| 
保留期限可以更改嗎？
 a| 
* 在合規模式下，物件版本的保留截止日期可以增加但不能減少。
* 在治理模式下，具有特殊權限的使用者可以減少甚至刪除物件的保留設定。

 a| 
儲存桶的保留期可以增加，但不能減少。



 a| 
合法保留在哪裡管制？
 a| 
使用者可以對儲存桶中的任何物件版本設定合法保留或解除合法保留。
 a| 
對儲存桶實施合法保留，並影響儲存桶中的所有物件。



 a| 
什麼時候可以刪除物件？
 a| 
* 在合規模式下，假設物件未處於合法保留狀態，則可以在達到保留期限後刪除物件版本。
* 在治理模式下，具有特殊權限的使用者可以在達到保留期限之前刪除對象，假設該對像不受合法保留。

 a| 
假設儲存桶未處於合法保留狀態，則可以在保留期到期後刪除物件。物件可以自動或手動刪除。



 a| 
是否支援 bucket 生命週期配置？
 a| 
是的
 a| 
不

|===