---
permalink: ilm/requirements-for-s3-object-lock.html 
sidebar: sidebar 
keywords: requirements, s3 object lock, compliant ilm rule, compliant ilm policy 
summary: 您必須查看啟用全域 S3 物件鎖定設定的要求、建立合規 ILM 規則和 ILM 策略的要求以及StorageGRID對使用 S3 物件鎖定的儲存桶和物件施加的限制。 
---
= S3 物件鎖定的要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須查看啟用全域 S3 物件鎖定設定的要求、建立合規 ILM 規則和 ILM 策略的要求以及StorageGRID對使用 S3 物件鎖定的儲存桶和物件施加的限制。



== 使用全域 S3 物件鎖定設定的要求

* 您必須先使用網格管理器或網格管理 API 啟用全域 S3 物件鎖定設置，然後任何 S3 租用戶才能建立啟用了 S3 物件鎖定的儲存桶。
* 啟用全域 S3 物件鎖定設定允許所有 S3 租用戶帳戶建立啟用了 S3 物件鎖定的儲存桶。
* 啟用全域 S3 物件鎖定設定後，您無法停用該設定。
* 除非所有活動 ILM 策略中的預設規則都符合要求（即，預設規則必須符合啟用了 S3 物件鎖定的儲存桶的要求），否則您無法啟用全域 S3 物件鎖定。
* 啟用全域 S3 物件鎖定設定後，您無法建立新的 ILM 策略或啟動現有的 ILM 策略，除非該策略中的預設規則符合要求。啟用全域 S3 物件鎖定設定後，ILM 規則和 ILM 原則頁面會指示哪些 ILM 規則是合規的。




== 符合 ILM 規則的要求

如果要啟用全域 S3 物件鎖定設置，則必須確保所有活動 ILM 策略中的預設規則都符合要求。合規規則滿足啟用了 S3 物件鎖定的儲存桶以及啟用了舊版合規性的任何現有儲存桶的要求：

* 它必須建立至少兩個複製的物件副本或一個擦除編碼副本。
* 這些副本必須在放置指令的每一行的整個持續時間記憶體在於儲存節點上。
* 物件副本無法保存在雲端儲存池中。
* 放置說明中至少有一行必須從第 0 天開始，使用 *攝取時間* 作為參考時間。
* 放置說明中至少有一行必須是「永遠」。




== ILM 策略的要求

啟用全域 S3 物件鎖定設定後，活動和非活動的 ILM 策略可以同時包含合規和不合規規則。

* 活動或非活動 ILM 策略中的預設規則必須符合。
* 不合規規則僅適用於未啟用 S3 物件鎖定或未啟用舊版合規性功能的儲存桶中的物件。
* 合規規則可套用於任何儲存桶中的物件；儲存桶無需啟用 S3 物件鎖定或舊版合規性。


link:example-7-compliant-ilm-policy-for-s3-object-lock.html["S3 物件鎖定的合規 ILM 策略範例"]



== 啟用 S3 物件鎖定的儲存桶的要求

* 如果為StorageGRID系統啟用了全域 S3 物件鎖定設置，則您可以使用租用戶管理器、租用戶管理 API 或 S3 REST API 建立啟用了 S3 物件鎖定的儲存桶。
* 如果您打算使用 S3 物件鎖，則必須在建立儲存桶時啟用 S3 物件鎖。您無法為現有儲存桶啟用 S3 物件鎖定。
* 當為儲存桶啟用 S3 物件鎖定時， StorageGRID會自動為該儲存桶啟用版本控制。您無法停用 S3 物件鎖定或暫停儲存桶的版本控制。
* 或者，您可以使用租用戶管理器、租用戶管理 API 或 S3 REST API 為每個儲存桶指定預設保留模式和保留期限。儲存桶的預設保留設定僅適用於新增至儲存體桶且沒有自己的保留設定的新物件。您可以透過在上傳每個物件版本時為其指定保留模式和保留截止日期來覆寫這些預設值。
* 啟用 S3 物件鎖的儲存桶支援儲存桶生命週期配置。
* 啟用了 S3 物件鎖的儲存桶不支援 CloudMirror 複製。




== 啟用 S3 物件鎖的儲存桶中的物件要求

* 為了保護物件版本，您可以為儲存桶指定預設保留設置，也可以為每個物件版本指定保留設定。可以使用 S3 用戶端應用程式或 S3 REST API 指定物件級保留設定。
* 保留設定適用於單一物件版本。物件版本可以同時具有保留截止日期和合法保留設置，或者只具有其中之一，或者兩者都不具有。為物件指定保留期限或合法保留設定僅保護請求中指定的版本。您可以建立該物件的新版本，同時該物件的先前版本仍保持鎖定狀態。




== 啟用 S3 物件鎖的儲存桶中物件的生命週期

啟用 S3 物件鎖定後，儲存在儲存桶中的每個物件都會經歷以下階段：

. *物件攝取*
+
當物件版本新增至啟用了 S3 物件鎖定的儲存桶時，將套用下列保留設定：

+
** 如果為物件指定了保留設置，則套用物件層級的設定。任何預設儲存桶設定都將被忽略。
** 如果沒有為物件指定保留設置，則套用預設儲存桶設定（如果存在）。
** 如果沒有為物件或儲存桶指定保留設置，則該物件不受 S3 物件鎖定保護。


+
如果套用了保留設置，則物件和任何 S3 使用者定義的元資料都受到保護。

. *物件保留和刪除*
+
StorageGRID會儲存每個受保護物件的多個副本，並保留指定的期限。物件副本的確切數量和類型以及儲存位置由活動 ILM 策略中的相容規則決定。受保護物件是否可以在達到保留期限之前被刪除取決於其保留模式。

+
** 如果某個物件處於合法保留之下，則無論其保留模式為何，任何人都無法刪除該物件。




.相關資訊
* link:../tenant/creating-s3-bucket.html["建立 S3 儲存桶"]
* link:../tenant/update-default-retention-settings.html["更新 S3 物件鎖定預設保留"]
* link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 設定 S3 物件鎖"]
* link:example-7-compliant-ilm-policy-for-s3-object-lock.html["範例 7：符合 S3 物件鎖定的 ILM 策略"]

