---
permalink: ilm/troubleshooting-cloud-storage-pools.html 
sidebar: sidebar 
keywords: cloud storage pool, troubleshoot 
summary: 使用這些故障排除步驟來協助解決您在建立、編輯或刪除雲端儲存池時可能遇到的錯誤。 
---
= 排除雲端儲存池故障
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用這些故障排除步驟來協助解決您在建立、編輯或刪除雲端儲存池時可能遇到的錯誤。



== 確定是否發生錯誤

StorageGRID透過讀取已知物件對每個雲端儲存池執行簡單的健康檢查 `x-ntap-sgws-cloud-pool-uuid`確保雲端儲存池可以存取並正常運作。當StorageGRID在端點上遇到錯誤時，它會每分鐘從每個儲存節點執行一次健康檢查。當錯誤解決後，健康檢查停止。如果健康檢查偵測到問題，則會在儲存池頁面上的雲端儲存池表的最後一個錯誤欄位中顯示一則訊息。

此表顯示了每個雲端儲存池偵測到的最近錯誤，並指示錯誤發生的時間。

此外，如果運行狀況檢查偵測到過去 5 分鐘內發生了一個或多個新的雲端儲存池錯誤，則會觸發*雲端儲存池連線錯誤*警報。如果您收到此警報的電子郵件通知，請前往儲存池頁面（選擇 *ILM* > *儲存池*），查看上一個錯誤欄位中的錯誤訊息，並參考下方的故障排除指南。



== 檢查錯誤是否已解決

解決所有潛在問題後，您可以確定錯誤是否已解決。從雲端儲存池頁面，選擇端點，然後選擇*清除錯誤*。確認訊息表示StorageGRID已清除雲端儲存池的錯誤。

如果根本問題已解決，則不再顯示錯誤訊息。但是，如果根本問題尚未解決（或遇到其他錯誤），則錯誤訊息將在幾分鐘內顯示在「上次錯誤」列中。



== 錯誤：健康檢查失敗。端點錯誤

當您開始將此儲存桶用作雲端儲存池後，請為 Amazon S3 儲存桶啟用具有預設保留的 S3 物件鎖定時，可能會遇到此錯誤。當 PUT 操作沒有包含有效負載校驗和值的 HTTP 標頭時，就會發生此錯誤，例如 `Content-MD5`。對於啟用了 S3 物件鎖定的儲存桶中的 PUT 操作，AWS 需要此標頭值。

要解決此問題，請按照link:editing-cloud-storage-pool.html["編輯雲端儲存池"]無需做任何改變。此操作會觸發雲端儲存池配置的驗證，該驗證會自動偵測並更新雲端儲存池端點配置上的 S3 物件鎖定標誌。



== 錯誤：此雲端儲存池包含意外內容

當您嘗試建立、編輯或刪除雲端儲存池時，可能會遇到此錯誤。如果儲存桶或容器包含 `x-ntap-sgws-cloud-pool-uuid`標記文件，但該文件沒有具有預期 UUID 的元資料欄位。

通常，只有在建立新的雲端儲存池並且StorageGRID的另一個實例已經在使用相同的雲端儲存池時，才會看到此錯誤。

請嘗試以下步驟之一來修正該問題：

* 如果您正在設定新的雲端儲存池，且儲存桶包含 `x-ntap-sgws-cloud-pool-uuid`文件和附加物件鍵類似於以下範例，建立一個新的儲存桶並使用這個新的儲存桶。
+
附加物件鍵的範例： `my-bucket.3E64CF2C-B74D-4B7D-AFE7-AD28BC18B2F6.1727326606730410`

* 如果 `x-ntap-sgws-cloud-pool-uuid`文件是儲存桶中的唯一對象，請刪除該檔案。


如果這些步驟不適用於您的情況，請聯絡支援人員。



== 錯誤：無法建立或更新雲端儲存池。端點錯誤

您可能會在以下情況下遇到此錯誤：

* 當您嘗試建立或編輯雲端儲存池。
* 當您在配置新的雲端儲存池期間選擇不受支援的平台、驗證或與 S3 物件鎖定的協定組合。看link:../ilm/considerations-for-cloud-storage-pools.html["雲端儲存池的注意事項"] 。


此錯誤表示連線或設定問題阻止StorageGRID寫入雲端儲存池。

若要修正該問題，請查看來自端點的錯誤訊息。

* 如果錯誤訊息包含 `Get _url_: EOF`，檢查用於雲端儲存池的服務端點是否對需要 HTTPS 的容器或儲存桶使用 HTTP。
* 如果錯誤訊息包含 `Get _url_: net/http: request canceled while waiting for connection`，驗證網路配置是否允許儲存節點存取用於雲端儲存池的服務端點。
* 如果錯誤是由於不受支援的平台、身份驗證或協定造成的，請使用 S3 物件鎖定變更為支援的配置，然後嘗試再次儲存新的雲端​​儲存池。
* 對於所有其他端點錯誤訊息，請嘗試以下一項或多項操作：
+
** 建立一個與您為雲端儲存池輸入的名稱相同的外部容器或儲存桶，然後嘗試再次儲存新的雲端​​儲存池。
** 修正您為雲端儲存池指定的容器或儲存桶名稱，然後嘗試再次儲存新的雲端​​儲存池。






== 錯誤：無法解析 CA 憑證

當您嘗試建立或編輯雲端儲存池時，可能會遇到此錯誤。如果StorageGRID無法解析您在配置雲端儲存池時輸入的證書，則會發生錯誤。

若要修正此問題，請檢查您提供的 CA 憑證是否有問題。



== 錯誤：未找到具有此 ID 的雲端儲存池

當您嘗試編輯或刪除雲端儲存池時，可能會遇到此錯誤。如果端點傳回 404 回應，則會發生此錯誤，這可能表示下列任一情況：

* 用於雲端儲存池的憑證沒有該儲存桶的讀取權限。
* 用於雲端儲存池的儲存桶不包括 `x-ntap-sgws-cloud-pool-uuid`標記文件。


請嘗試以下一個或多個步驟來修正該問題：

* 檢查與配置的存取金鑰關聯的使用者是否具有必要的權限。
* 使用具有必要權限的憑證編輯雲端儲存池。
* 如果權限正確，請聯絡支援人員。




== 錯誤：無法檢查雲端儲存池的內容。端點錯誤

當您嘗試刪除雲端儲存池時，可能會遇到此錯誤。此錯誤表示某種連線或設定問題阻止StorageGRID讀取雲端儲存池儲存桶的內容。

若要修正該問題，請查看來自端點的錯誤訊息。



== 錯誤：物件已放入此儲存桶

當您嘗試刪除雲端儲存池時，可能會遇到此錯誤。如果雲端儲存池包含由 ILM 移動到該池的資料、在您配置雲端儲存池之前儲存桶中的資料或在建立雲端儲存池之後由其他來源放入儲存桶中的數據，則您無法刪除該雲端儲存池。

請嘗試以下一個或多個步驟來修正該問題：

* 依照「雲端儲存池物件的生命週期」中的說明將物件移回StorageGRID 。
* 如果您確定剩餘物件未由 ILM 放置在雲端儲存池中，請手動從儲存桶中刪除這些物件。
+

NOTE: 切勿手動刪除 ILM 可能放置於雲端儲存池中的物件。如果您稍後嘗試從StorageGRID存取手動刪除的對象，則將找不到已刪除的對象。





== 錯誤：代理程式在嘗試存取雲端儲存池時遇到外部錯誤

如果您在儲存節點和用於雲端儲存池的外部 S3 端點之間配置了非透明儲存代理，則可能會遇到此錯誤。如果外部代理伺服器無法存取雲端儲存池端點，就會發生此錯誤。例如，DNS 伺服器可能無法解析主機名，或者可能有外部網路問題。

請嘗試以下一個或多個步驟來修正該問題：

* 檢查雲端儲存池的設定（*ILM* > *儲存池*）。
* 檢查儲存代理伺服器的網路配置。




== 錯誤：X.509 證書超出有效期限

當您嘗試刪除雲端儲存池時，可能會遇到此錯誤。當身份驗證需要 X.509 憑證以確保驗證正確的外部雲端儲存池，並且在刪除雲端儲存池配置之前外部池為空時，會發生此錯誤。

請嘗試以下步驟來修正該問題：

* 更新為雲端儲存池身份驗證配置的憑證。
* 確保此雲端儲存池上的任何憑證過期警報都已解決。


.相關資訊
link:lifecycle-of-cloud-storage-pool-object.html["雲端儲存池物件的生命週期"]
