---
permalink: ilm/using-last-access-time-in-ilm-rules.html 
sidebar: sidebar 
keywords: last access time, ilm rule reference time 
summary: 您可以使用上次造訪時間作為 ILM 規則中的參考時間。例如，您可能希望將過去三個月內查看過的物件保留在本地儲存節點上，同時將最近未查看的物件移至異地位置。如果您希望 ILM 規則僅適用於在特定日期最後造訪的對象，您也可以使用上次造訪時間作為進階篩選器。 
---
= 在 ILM 規則中使用上次存取時間
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用上次造訪時間作為 ILM 規則中的參考時間。例如，您可能希望將過去三個月內查看過的物件保留在本地儲存節點上，同時將最近未查看的物件移至異地位置。如果您希望 ILM 規則僅適用於在特定日期最後造訪的對象，您也可以使用上次造訪時間作為進階篩選器。

.關於此任務
在 ILM 規則中使用上次存取時間之前，請檢查以下注意事項：

* 當使用上次造訪時間作為參考時間時，請注意更改物件的上次造訪時間不會觸發立即的 ILM 評估。相反，當背景 ILM 評估物件時，會評估物件的位置並根據需要移動物件。訪問對象後，這可能需要兩週或更長時間。
+
根據上次造訪時間建立 ILM 規則時請考慮此延遲，並避免使用短時間段（少於一個月）的放置。

* 當使用上次存取時間作為進階篩選器或參考時間時，您必須為 S3 儲存桶啟用上次存取時間更新。您可以使用link:../tenant/enabling-or-disabling-last-access-time-updates.html["租戶經理"]或link:../s3/put-bucket-last-access-time-request.html["租戶管理 API"]。
+

NOTE: 預設情況下，S3 儲存桶的上次存取時間更新為停用。

+

NOTE: 請注意，啟用上次訪問時間更新可能會降低效能，尤其是在具有小物件的系統中。效能受到影響的原因是StorageGRID每次檢索物件時都必須使用新的時間戳更新物件。



下表總結了針對不同類型的請求，儲存桶中所有物件的上次存取時間是否更新。

[cols="1a,1a,1a"]
|===
| 請求類型 | 當上次訪問時間更新被停用時，是否更新上次訪問時間 | 啟用上次造訪時間更新時是否更新上次造訪時間 


 a| 
請求檢索物件、其存取控制清單或其元數據
 a| 
不
 a| 
是的



 a| 
請求更新物件的元數據
 a| 
是的
 a| 
是的



 a| 
請求將物件從一個儲存桶複製到另一個儲存桶
 a| 
* 不，對於來源副本
* 是的，對於目標副本

 a| 
* 是的，對於來源副本
* 是的，對於目標副本




 a| 
請求完成分段上傳
 a| 
是的，對於組裝好的物體
 a| 
是的，對於組裝好的物體

|===