---
permalink: ilm/when-to-use-cloud-storage-pools.html 
sidebar: sidebar 
keywords: use cloud storage pool, benefits of cloud storage pools 
summary: 使用雲端儲存池，您可以將資料備份或分層到外部位置。此外，您還可以將資料備份或分層到多個雲端。 
---
= 何時使用雲端儲存池
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用雲端儲存池，您可以將資料備份或分層到外部位置。此外，您還可以將資料備份或分層到多個雲端。



== 將StorageGRID資料備份到外部位置

您可以使用雲端儲存池將StorageGRID物件備份到外部位置。

如果StorageGRID中的副本無法訪問，則可以使用雲端儲存池中的物件資料來滿足客戶端請求。但是，您可能需要發出 S3 RestoreObject 請求來存取雲端儲存池中的備份物件副本。

雲端儲存池中的物件資料也可用於復原因儲存磁碟區或儲存節點故障而從StorageGRID遺失的資料。如果物件的唯一剩餘副本位於雲端儲存池中， StorageGRID會暫時還原該物件並在已復原的儲存節點上建立新副本。

要實施備份解決方案：

. 建立單一雲端儲存池。
. 配置 ILM 規則，同時將物件副本儲存在儲存節點上（作為複製或擦除編碼副本）以及雲端儲存池中的單一物件副本。
. 將該規則新增至您的 ILM 策略。然後，模擬並啟動該策略。




== 將資料從StorageGRID分層到外部位置

您可以使用雲端儲存池儲存StorageGRID系統之外的物件。例如，假設您有大量需要保留的對象，但您預期很少造訪這些對象。您可以使用雲端儲存池將物件分層到成本較低的儲存空間並釋放StorageGRID中的空間。

要實施分層解決方案：

. 建立單一雲端儲存池。
. 配置 ILM 規則，將很少使用的物件從儲存節點移至雲端儲存池。
. 將該規則新增至您的 ILM 策略。然後，模擬並啟動該策略。




== 維護多個雲端點

如果您想要將物件資料分層或備份到多個雲，則可以設定多個雲端儲存池端點。 ILM 規則中的篩選器可讓您指定每個雲端儲存池中儲存的物件。例如，您可能想要將某些租用戶或儲存桶中的物件儲存在 Amazon S3 Glacier 中，將其他租用戶或儲存桶中的物件儲存在 Azure Blob 儲存體中。或者，您可能希望在 Amazon S3 Glacier 和 Azure Blob 儲存之間移動資料。


NOTE: 使用多個雲端儲存池端點時，請記住一個物件一次只能儲存在一個雲端儲存池中。

要實現多個雲端點：

. 最多可建立 10 個雲端儲存池。
. 配置 ILM 規則以在適當的時間將適當的物件資料儲存在每個雲端儲存池中。例如，將儲存桶 A 中的物件儲存在雲端儲存池 A 中，將儲存桶 B 中的物件儲存在雲端儲存池 B 中。或者，將物件在雲端儲存池 A 中儲存一段時間，然後將其移至雲端儲存池 B。
. 將規則新增至您的 ILM 策略。然後，模擬並啟動該策略。

