---
permalink: fabricpool/creating-s3-bucket-and-access-key.html 
sidebar: sidebar 
keywords: fabricPool, S3 bucket, bucket, access key, secret access key 
summary: 在將StorageGRID與FabricPool工作負載結合使用之前，您必須為FabricPool資料建立一個 S3 儲存桶。您還需要取得將用於FabricPool 的租用戶帳戶的存取金鑰和秘密存取金鑰。 
---
= 建立 S3 儲存桶並取得存取金鑰
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在將StorageGRID與FabricPool工作負載結合使用之前，您必須為FabricPool資料建立一個 S3 儲存桶。您還需要取得將用於FabricPool 的租用戶帳戶的存取金鑰和秘密存取金鑰。

有關此任務的詳細信息，請參閱link:../tenant/creating-s3-bucket.html["建立 S3 儲存桶"]和link:../tenant/creating-your-own-s3-access-keys.html["建立您自己的 S3 存取金鑰"]。若要使用FabricPool設定精靈完成此任務，請前往link:use-fabricpool-setup-wizard-steps.html["存取並完成FabricPool設定精靈"]。

.開始之前
* 您已建立供FabricPool使用的租戶帳戶。
* 您具有租用戶帳戶的 Root 存取權。


.步驟
. Sign in租戶管理器。
+
您可以執行下列任一操作：

+
** 從網格管理員中的租戶帳戶頁面中，選擇租戶的 *Sign in* 鏈接，然後輸入您的憑證。
** 在 Web 瀏覽器中輸入租用戶帳戶的 URL，然後輸入您的憑證。


. 為FabricPool資料建立一個 S3 儲存桶。
+
您必須為計劃使用的每個ONTAP叢集建立一個唯一的儲存桶。

+
.. 從儀表板中選擇 *查看儲存桶*，或選擇 *儲存（S3）* > *儲存桶*。
.. 選擇*建立儲存桶*。
.. 輸入要與FabricPool一起使用的StorageGRID桶的名稱。例如，  `fabricpool-bucket` 。
+

TIP: 建立儲存桶後，您無法變更儲存桶名稱。

.. 選擇此儲存桶的區域。
+
預設情況下，所有儲存桶均在 `us-east-1`地區。

.. 選擇*繼續*。
.. 選擇*建立儲存桶*。
+

NOTE: 不要為FabricPool儲存桶選擇「啟用物件版本控制」。同樣，不要編輯FabricPool儲存桶以使用 *Available* 或非預設一致性。  FabricPool儲存桶的建議儲存桶一致性為 *Read-after-new-write*，這是新儲存桶的預設一致性。



. 建立一個存取密鑰和一個秘密存取密鑰。
+
.. 選擇*儲存 (S3)* > *我的存取金鑰*。
.. 選擇*建立金鑰*。
.. 選擇*建立存取金鑰*。
.. 將存取金鑰 ID 和秘密存取金鑰複製到安全位置，或選擇 *下載 .csv* 以儲存包含存取金鑰 ID 和秘密存取金鑰的電子表格檔案。
+
當您將StorageGRID配置為FabricPool雲層時，您將在ONTAP中輸入這些值。

+

TIP: 如果您將來在StorageGRID中產生新的存取金鑰和秘密存取金鑰，請先將新金鑰輸入ONTAP，然後再從StorageGRID中刪除舊值。否則， ONTAP可能會暫時失去對StorageGRID的存取權。




