---
permalink: fabricpool/use-fabricpool-setup-wizard.html 
sidebar: sidebar 
keywords: fabricPool, FabricPool setup wizard, ontap system manager 
summary: 您可以使用FabricPool設定精靈將StorageGRID配置為FabricPool雲層的物件儲存系統。完成設定精靈後，您可以在ONTAP系統管理員中輸入所需的詳細資訊。 
---
= 使用FabricPool設定精靈：注意事項與要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用FabricPool設定精靈將StorageGRID配置為FabricPool雲層的物件儲存系統。完成設定精靈後，您可以在ONTAP系統管理員中輸入所需的詳細資訊。



== 何時使用FabricPool設定嚮導

FabricPool設定精靈將引導您完成設定StorageGRID以與FabricPool一起使用的每個步驟，並自動為您設定某些實體，例如 ILM 和流量分類策略。作為完成精靈的一部分，您將下載一個文件，可以使用該文件將值輸入ONTAP系統管理員。使用精靈可以更快地配置您的系統並確保您的設定符合StorageGRID和FabricPool最佳實務。

假設您擁有 Root 存取權限，您可以在開始使用StorageGRID Grid Manager 時完成FabricPool設定精靈，或者您可以在以後的任何時間存取並完成該精靈。根據您的要求，您也可以手動設定部分或全部所需項目，然後使用精靈將ONTAP所需的值組合到一個檔案中。


TIP: 使用FabricPool設定嚮導，除非您知道您有特殊要求或您的實作需要大量自訂。



== 使用精靈之前

確認您已完成這些先決條件步驟。



=== 回顧最佳實踐

* 您已大致了解link:information-needed-to-attach-storagegrid-as-cloud-tier.html["將StorageGRID附加為雲層所需的信息"]。
* 您已查看了以下FabricPool最佳實務：
+
** link:best-practices-for-high-availability-groups.html["高可用性 (HA) 組"]
** link:best-practices-for-load-balancing.html["負載平衡"]
** link:best-practices-ilm.html["ILM 規則和政策"]






=== 取得 IP 位址並設定 VLAN 介面

如果您要設定 HA 群組，您就會知道ONTAP將連接到哪些節點以及將使用哪個StorageGRID網路。您也知道要為子網路 CIDR、閘道 IP 位址和虛擬 IP (VIP) 位址輸入哪些值。

如果您打算使用虛擬 LAN 來隔離FabricPool流量，則您已經設定了 VLAN 介面。看link:../admin/configure-vlan-interfaces.html["配置VLAN介面"] 。



=== 設定身份聯合和 SSO

如果您打算對StorageGRID系統使用身分聯合或單一登入 (SSO)，則您已啟用這些功能。您也知道哪個聯合群組應該對ONTAP將使用的租用戶帳戶具有 root 存取權。看link:../admin/using-identity-federation.html["使用身分聯合"]和link:../admin/configuring-sso.html["配置單一登入"]。



=== 取得並配置域名

* 您知道要為StorageGRID使用哪一個完全限定網域名稱 (FQDN)。網域名稱伺服器 (DNS) 項目會將此 FQDN 對應到您使用精靈建立的 HA 群組的虛擬 IP (VIP) 位址。看link:../fabricpool/configure-dns-server.html["配置 DNS 伺服器"] 。
* 如果您打算使用 S3 虛擬託管式要求，則link:../admin/configuring-s3-api-endpoint-domain-names.html["配置的 S3 端點域名"]。  ONTAP預設使用路徑樣式 URL，但建議使用虛擬託管樣式請求。




=== 審查負載平衡器和安全性證書要求

如果您打算使用StorageGRID負載平衡器，則您已查看了常規link:../admin/managing-load-balancing.html["負載平衡的注意事項"]。您擁有要上傳的憑證或產生憑證所需的值。

如果您打算使用外部（第三方）負載平衡器端點，則您擁有該負載平衡器的完全限定網域名稱（FQDN）、連接埠和憑證。



=== 確認 ILM 儲存池配置

如果您最初安裝了StorageGRID 11.6 或更早版本，則您已經設定了將使用的儲存池。一般來說，您應該為用於儲存ONTAP資料的每個StorageGRID網站建立一個儲存池。


NOTE: 如果您最初安裝的是StorageGRID 11.7 或 11.8，則此先決條件不適用。當您最初安裝這兩個版本中的任何一個時，都會自動為每個網站建立儲存池。



== ONTAP與StorageGRID雲層之間的關係

FabricPool精靈將引導您完成建立單一StorageGRID雲層的過程，該雲層包括一個StorageGRID租用戶、一組存取金鑰和一個StorageGRID桶。您可以將此StorageGRID雲層附加到一個或多個ONTAP本地層。

將單一雲層附加到叢集中的多個本地層是一般的最佳實踐。但是，根據您的要求，您可能希望在單一叢集中為本地層使用多個儲存桶甚至多個StorageGRID租用戶。使用不同的儲存桶和租戶允許您隔離ONTAP本地層之間的資料和資料訪問，但配置和管理稍微複雜一些。

NetApp不建議將單一雲層附加到多個叢集中的本機層。


NOTE: 有關將StorageGRID與NetApp MetroCluster™ 和FabricPool Mirror 結合使用的最佳實踐，請參閱 https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["TR-4598： ONTAP中的FabricPool最佳實踐"^]。



=== 可選：為每個本地層使用不同的儲存桶

若要在ONTAP叢集中為本機層使用多個儲存桶，請在ONTAP中新增多個StorageGRID雲層。每個雲層共用相同的 HA 群組、負載平衡器端點、租用戶和存取金鑰，但使用不同的容器（ StorageGRID桶）。請遵循以下常規步驟：

. 從StorageGRID Grid Manager 完成第一個雲層的FabricPool設定精靈。
. 從ONTAP系統管理員新增雲層並使用從StorageGRID下載的檔案提供所需的值。
. 從StorageGRID Tenant Manager 登入精靈建立的租用戶，並建立第二個儲存桶。
. 再次完成FabricPool精靈。選擇現有的 HA 組、負載平衡器端點和租用戶。然後，選擇您手動建立的新儲存桶。為新儲存桶建立新的 ILM 規則並啟動 ILM 策略以包含該規則。
. 從ONTAP新增第二個雲層，但提供新的儲存桶名稱。




=== 可選：為每個本地層使用不同的租戶和儲存桶

若要對ONTAP叢集中的本機層使用多個租用戶和不同的存取金鑰集，請在ONTAP中新增多個StorageGRID雲層。每個雲層共用相同的 HA 群組、負載平衡器端點，但使用不同的租用戶、存取金鑰和容器（ StorageGRID桶）。請遵循以下常規步驟：

. 從StorageGRID Grid Manager 完成第一個雲層的FabricPool設定精靈。
. 從ONTAP系統管理員新增雲層並使用從StorageGRID下載的檔案提供所需的值。
. 再次完成FabricPool精靈。選擇現有的 HA 組和負載平衡器端點。建立新的租戶和儲存桶。為新儲存桶建立新的 ILM 規則並啟動 ILM 策略以包含該規則。
. 從ONTAP新增第二個雲層，但提供新的存取金鑰、金鑰和儲存桶名稱。

